### ISSUE TITLE
Installation MYSQL Error "Index column size too large"

### ISSUE THREAD

**Issue by JeremyKeusters** [octobercms/october#3405] opened 2018-02-17 17:54 UTC
##### Expected behavior
I was trying to install OctoberCMS. I expected it to run successfully.

##### Actual behavior
I got an error while installing.
`SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (SQL: alter table 'deferred_bindings' add index 'deferred_bindings_master_type_index'('master_type'))`

##### Reproduce steps
Install OctoberCMS using a MariaDB database engine. (well, I think that it has to do something with MariaDB)

##### October build
v1.0.433

##### Extra info
The installation of OctoberCMS went perfectly some months ago on the same host.
Update: possibly the same bug as #2356

**Comment by danhrrn** [comment] 2018-02-17 18:47
We have identified that this could be an issue with the use of `utf8mb4` on your server. Please check what encoding your installation uses on line 63 in /config/database.php

**Comment by danhrrn** [comment] 2018-02-17 19:05
You need to change line 62 and 63 to…
```
'charset'   => 'utf8',
'collation' => 'utf8_unicode_ci',
```
and report back what happens then.

**Comment by LukeTowers** [comment] 2018-02-17 19:51
Duplicate of https://github.com/octobercms/october/issues/1927

**Closed by LukeTowers** 2018-02-17 19:51 UTC
