### ISSUE TITLE
Media Manager cut file name with cyrillic symbols and spaces

### ISSUE THREAD

**Issue by Trysystems** [octobercms/october#4623] opened 2019-09-18 06:35 UTC
- OctoberCMS Build: 458
- PHP Version: 7.2

### Description:
When upload file with cyrillic name and spaces, the first part of the name is lost. After uploading file with name 'Новый текстовый документ.txt' new file create with name ' текстовый документ.txt'

**Comment by w20k** [comment] 2019-09-25 10:51
@Trysystems can't reproduce your issue anyhow. Could you provide a gif or images on how to reproduce your issue? I'm getting different result.

**Comment by Trysystems** [comment] 2019-09-26 03:05
Problem with spaces and underscores. Situation the same on local storage and s3. The first part of name with cyrillic symbols is lost.

![Аннотация 2019-09-25 205851](https://user-images.githubusercontent.com/12799052/65654973-bb02db00-dfd7-11e9-9c90-f236e5050457.png)

**Comment by Trysystems** [comment] 2019-09-26 03:15
If I creating file manually at storage folder, in Media Manager it showing also without the first part of the name. If I adding latin symbol or number to the start of name in cyrillic ('1Новый текстовый документ.txt') - all working normally.
![Аннотация 2019-09-25 210854](https://user-images.githubusercontent.com/12799052/65655422-65c7c900-dfd9-11e9-9b59-a2be9f5126a5.png)

**Comment by w20k** [comment] 2019-10-10 13:32
@Trysystems sorry to get back to you after a long period of time, but re-test your steps, and for me, in the latest version it's all good.
Could you try with the latest build?
Screenshot:
![Screenshot 2019-10-10 at 16 31 50](https://user-images.githubusercontent.com/1053320/66573533-7fd9dd80-eb7b-11e9-9bde-931468243424.png)

**Comment by Trysystems** [comment] 2019-10-10 16:22
It's so strange, but I have this problem on different hostings with different php versions, and it's not depend of October locale. Now I tried to install fresh ubuntu, lamp, clone october repo and install from command line (composer update & php artisan october:install) - the situation the same. If you want, I can give you access to test domain.

**Comment by w20k** [comment] 2019-10-10 19:51
If you're on the slack ping me @Trysystems. Might be somehow related to OS, because I'm on OSX.

**Comment by Trysystems** [comment] 2019-10-10 20:12
I was registered on slack, but cant find you to write)) I've nerer use it before, sorry. Maybe you can find me. So, I think it's not related to OS, on Android all the same.

**Comment by w20k** [comment] 2019-10-10 20:19
Could you drop me your nickname, tried with `Trysystems` :) Couldn't seem to find you.

You could find me by clicking on the plus sign new `+` new Direct messages:
<img width="207" alt="Screenshot 2019-10-10 at 23 17 54" src="https://user-images.githubusercontent.com/1053320/66603220-6012db80-ebb4-11e9-925c-cfb827edb01f.png">
<img width="507" alt="Screenshot 2019-10-10 at 23 18 01" src="https://user-images.githubusercontent.com/1053320/66603222-6012db80-ebb4-11e9-9ef4-f045db0c4d34.png">

**Comment by Trysystems** [comment] 2019-11-06 19:38
Problem in basepath() function, which not correct works with some symbols, not only cyrillic. 
One of the solutions - change apache config, file /etc/apache2/envvars:
`## Uncomment the following line to use the system default locale instead:
. /etc/default/locale
`
But maybe exist another solution, wich solve this problem without config change? I have web servers where I can't edit config files.

This is another example of this error https://stackoverflow.com/questions/4451664/make-php-pathinfo-return-the-correct-filename-if-the-filename-is-utf-8

**Comment by Samuell1** [comment] 2019-11-06 20:24
@Trysystems Does same error is with nginx?

**Comment by Trysystems** [comment] 2019-11-06 20:31
@Samuell1 I didn't try, maybe no. 
I think good idea to use another function to get basename in places where could be used non latin characters, such as Media Manager.

**Comment by whsol** [comment] 2019-11-07 08:21
For cyrillic you can add `setlocale(LC_ALL, 'ru_RU');` to the begin of a file bootstrap/app.php.

**Comment by Trysystems** [comment] 2019-11-07 22:09
@whsol Yes, it's one of the options, but I hope exist better solution thats will be work out-of-the-box.

**Comment by Trysystems** [comment] 2019-12-08 05:38
Still actual

**Comment by Trysystems** [comment] 2020-02-11 07:19
Thank you for reopen, @w20k ! This bug is still actual. Maybe mark issue with Confirmed bug? This applies not only MediaManager, but all plugins that used MediaManager api to upload and save files.

**Comment by LukeTowers** [comment] 2020-02-14 20:46
This might be a duplicate of #3354

**Comment by bennothommo** [comment] 2020-02-16 14:13
@Trysystems I can confirm the filename working without issue on October installed on Ubuntu 18.04 / PHP 7.4 / Nginx.

**Comment by Trysystems** [comment] 2020-02-16 17:35
Yes, it also works without issue on some Apache servers with property locale setted, but if locale not set - basename() & pathinfo() will have troubles.

**Comment by Blinks44** [comment] 2020-03-07 09:58
I have this problem to. Ubuntu 18.04, nginx, php 7.2, first cyrillic word always disappear in media manager...

**Closed** 2020-04-10 00:06 UTC
Labels: Status: Archived, Status: Response Needed, Type: Unconfirmed Bug
