### ISSUE TITLE
Subject is always "Mailable" for queued mails

### ISSUE THREAD

**Issue by alxy** [octobercms/october#3384] opened 2018-02-06 21:24 UTC
##### Expected behavior
The subject is not correctly processed if mails are queued. Actually it will always be "Mailable". This bug is even present on the octobercms.com website, whenever you get a mail for a subscribed form thread.

##### Actual behavior
The mail should show the correct title.

##### Reproduce steps
``Mail::sendTo('admin@domain.tld', 'acme.blog::mail.message', $params);``
``Mail::sendTo('admin@domain.tld', 'acme.blog::mail.message', $params, null, true); // The last param queues this mail``
Compare these two lines. The first email will have the subject set in the template, whereas the second will have "Mailable" set as subject.

##### October build
(current)

**Comment by xyng** [comment] 2018-02-12 08:47
I experienced the same problem and decided to dig a little:
This only affects subjects set in the template. If you set a subject in the callback function it will be set correctly.
The problem has to be somewhere before serialization for queueing occurs, as the subject will be `null` in the serialized job data when it's only set by the template.

A temporary workaround might be to set the subject in the callback function as that seems to work with queueing.

**Comment by LukeTowers** [comment] 2018-02-12 15:47
@xyng are you able to provide a fix in a PR for this issue?

**Comment by Mr1008** [comment] 2018-02-13 13:29
I have same issue for this one. And indeed it seems that the issue is this code:
```
    public function send(MailerContract $mailer)
    {
        Container::getInstance()->call([$this, 'build']);
        $mailer->send($this->buildView(), $this->buildViewData(), function ($message) {
            $this->buildFrom($message)
                 ->buildRecipients($message)
                 ->buildSubject($message)
                 ->buildAttachments($message)
                 ->runCallbacks($message);
        });
    }
```
and method `buildSubject($message)` taking basename
```
protected function buildSubject($message)
    {
        if ($this->subject) {
            $message->subject($this->subject);
        } else {
            $message->subject(Str::title(Str::snake(class_basename($this), ' ')));
        }

        return $this;
    }
```

**Comment by LukeTowers** [comment] 2018-02-13 16:48
@Mr1008 what can we do to fix it from October's end then?

**Comment by alxy** [comment] 2018-02-13 16:51
@LukeTowers You can at least change the badge to confirmed bug :p I have also started to investigate this issue but wasn't able to fix, as it's not so easy, since October did override some methods of the original laravel Mailer and others not...

**Comment by KonstantinObuhov** [comment] 2018-03-01 12:57
I have the same issue.
In order to hack some cases you can play inside closure)

**Comment by LukeTowers** [comment] 2018-03-01 20:27
@KonstantinObuhov were you able to find a fix for the issue?

**Comment by TimFoerster** [comment] 2018-03-08 22:03
@LukeTowers here are two examples how to fix the issue.

[First one](https://github.com/TimFoerster/library/commit/a5322a95d9882f85a04142f0c3a66b41ba98988f) sets the subject during the queuing the mail.
Disadvantage: When queuing a mail, the mail template will be parsed (for every email!).

[Second one](https://github.com/TimFoerster/library/commit/54c713e2e4d6e25b1bc9971d9090deff7466754c) overrides the subject, when it wasn't set.
Disadvantage: This only works when it's called `Mailable`.

**Comment by TimFoerster** [comment] 2018-03-09 07:45
I create another solution, this one just overrides the laravel method `buildSubject`.
The [laravel code](https://github.com/laravel/framework/blob/d533c04148d1e249a9c56e07eb94a0e132dc6ba0/src/Illuminate/Mail/Mailable.php#L322) didn't checked if there is a `subject` in the `message`.
I simply override this method and [checking for](https://github.com/TimFoerster/library/blob/ea18847dd771bd4bc14b7219e5a98eb0fa1111e9/src/Mail/Mailable.php#L67) the `message` attribute. If both `mailable->subject` and `message->subject` is not set, we take the default value from laravel (which is the class name).

**Comment by LukeTowers** [comment] 2018-03-09 16:12
@TimFoerster why do we even need the check for the message having a subject? Wouldn't this work too:
```php
protected function buildSubject($message)
{
    // Only attempt to set the subject if the message doesn't already have one set
    if (empty($message->getSubject()) {
        parent::buildSubject($message);
    }
    return $this;
}
```

**Comment by TimFoerster** [comment] 2018-03-09 17:30
@LukeTowers This won't work with custom subjects f.e.:
```
Mail::sendTo('admin@domain.tld', 'acme.blog::mail.message', $vars, function($message) {
                $message->subject("My custom subject");
            }, ['queue' => true]);
```
because `$this->subject` is set as `My custom subject` and will be ignored in your solution, since `$message->subject` contains the mail subject.

**Comment by LukeTowers** [comment] 2018-03-09 17:33
@TimFoerster good point. We can still simplify it to make it this instead though:
```php
protected function buildSubject($message)
{
    // Only attempt to set the subject if the message doesn't already have one set
    if ($this->subject) {
        $message->subject($this->subject);
    } elseif (empty($message->getSubject()) {
        parent::buildSubject($message);
    }
    return $this;
}
```

**Comment by TimFoerster** [comment] 2018-03-09 17:33
but this one works
```
protected function buildSubject($message)
{
    // Only attempt to set the subject if the message doesn't already have one set
    if (empty($message->getSubject()) || !empty($this->subject)) {
        parent::buildSubject($message);
    }
    return $this;
}
```

**Comment by LukeTowers** [comment] 2018-03-09 17:35
It would yes, I think the last version I posted is a bit more explicit in what's happening though because it tells you that the local `subject` property is overriding any subject set on the `$message`. Thoughts?

**Comment by TimFoerster** [comment] 2018-03-09 17:38
I don't mind, looks both good for me.

**Comment by LukeTowers** [comment] 2018-03-09 17:43
If you can switch to the one I mentioned (perhaps making the inline comments more clear) and get someone to test it then I can merge this. Thanks for your work on this @TimFoerster!

**Comment by TimFoerster** [comment] 2018-03-09 17:52
No problem @LukeTowers just tell me when you need the PR, doing laundry now :)

**Comment by LukeTowers** [comment] 2018-03-09 17:55
@TimFoerster you can make it any time

**Comment by Verbat** [comment] 2018-03-16 12:51
Can this be merged. 

I had the same problem with the blog and forum plugin when a notification email was send. I applied this fix by myself and it works.

**Comment by LukeTowers** [comment] 2018-03-16 17:58
Fixed by https://github.com/octobercms/library/commit/60ac3b46a79a8c7b9815dfb3ccdf293ba4bb3195. Thanks to @TimFoerster!

**Closed by LukeTowers** 2018-03-16 17:58 UTC
Labels: Status: Review Needed, Type: Bug
