### ISSUE TITLE
Mail::queueOn / Mail::laterOn do not work

### ISSUE THREAD

**Issue by alxy** [octobercms/october#4870] opened 2020-01-07 22:09 UTC
- OctoberCMS Build: 462
- PHP Version: 7.2.3

### Description:
The Mailer functions `Mail::queueOn` and `Mail::laterOn` do not work as described in the docs. I get the following error, which is similar to the one reported [here](https://github.com/octobercms/october/issues/3130):

```
"Type error: Argument 1 passed to Illuminate\Mail\Mailable::queue() must implement interface Illuminate\Contracts\Queue\Factory, string given, called in /home/ploi/public/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php on line 357" on line 134 of /home/ploi/public/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php
```

### Steps To Reproduce:
```
Mail::queueOn('emails', 'acme.blog::mail.welcome', $data,  function ($message) {
     $message->subject('just a test');
     $message->to('me@anothersite.co');
});
```
I borrowed this from the other issue

**Comment by Teranode** [comment] 2020-01-11 23:55
Mail::queue does work for me

Build: 464
PHP: 7.3

been using Mail queue for emails for the longest while

Test function for backend template sending
![](https://i.imgur.com/6ssQCi9.png)

Used in user activation
![](https://i.imgur.com/lz4nGXU.png)

test successfully sent:
![](https://i.imgur.com/kD6yAud.png)

**Comment by alxy** [comment] 2020-01-13 10:02
@Teranode I actually only tested `queueOn` which calls queue under the hood. I thus expected to both be affected. Can you confirm queueOn isn't working?

**Comment by Teranode** [comment] 2020-01-15 06:57
@alxy Can confirm queueOn gives off that error

**Comment by alxy** [comment] 2020-01-15 08:48
Thnaks for confirming the issues. I adjusted the title to be precise and correct.

**Comment by bennothommo** [comment] 2020-01-16 02:49
Confirmed bug.

**Comment by mjauvin** [comment] 2020-01-16 03:27
It's odd since `queueOn()` calls `queue()`:
```
    public function queueOn($queue, $view, $data = null, $callback = null)
    {   
        return $this->queue($view, $data, $callback, $queue);
    }   
```
 and queue does the following:
```
    public function queue($view, $data = null, $callback = null, $queue = null)
    {   
        if (!$view instanceof MailableContract) {
            $mailable = $this->buildQueueMailable($view, $data, $callback);
        }
        else {
            $mailable = $view;
            $queue = $queue ?? $data;
        }

        return parent::queue($mailable, $queue);
    }
```

One would think if queue() works, queueOn() would work as well...

**Comment by bennothommo** [comment] 2020-01-16 04:02
@mjauvin The problem is the `$queue` parameter in the `queue` method. When you use the `queueOn` method and specify `$queue` as a string, it passes that to `$queue` in the `queue` method. When this is passed down to the `Mailable` object, it expects `$queue` to be a `Queue` object, not a string.

What is interesting to me is that the `Illuminate\Mail\Mailer` class from Laravel that we extend and call has the following for the `queue()` method:

```php
    /**
     * Queue a new e-mail message for sending.
     *
     * @param  string|array|MailableContract  $view
     * @param  string|null  $queue
     * @return mixed
     */
    public function queue($view, $queue = null)
    {
        if (! $view instanceof MailableContract) {
            throw new InvalidArgumentException('Only mailables may be queued.');
        }

        return $view->queue(is_null($queue) ? $this->queue : $queue);
    }
```

Their own PHPDoc says that `$queue` can be a string, but as soon as it is passed to the `Mailable` class via its `queue()` method, it is expected to be a `Queue` object.

```php
    /**
     * Queue the message for sending.
     *
     * @param  \Illuminate\Contracts\Queue\Factory  $queue
     * @return mixed
     */
    public function queue(Queue $queue)
```

This is inconsistent, it seems. I can only presume that Laravel (or us) are supposed to resolve a string-based queue to a proper object at some point in this process, but I can't find any evidence of Laravel doing it. :/

**Comment by bennothommo** [comment] 2020-01-16 04:57
@alxy @Teranode Would you mind trying the fix in https://github.com/octobercms/library/pull/454 and see if that resolves the issue for you?

**Comment by bennothommo** [comment] 2020-01-16 07:46
Fixed by https://github.com/octobercms/library/pull/454.

**Closed by bennothommo** 2020-01-16 07:46 UTC
Labels: Status: In Progress, Type: Bug
