### ISSUE TITLE
javascript error on clicking on certain components; it completely blocks the backend

### ISSUE THREAD

**Issue by JanvanCasteren** [octobercms/october#1549] opened 2015-10-23 13:10 UTC
When I click on a component in the CMS area, the following javascript error is thrown: *The select2('destroy') method was called on an element that is not using Select2*. 

After that, the interface is completely blocked, because the popover-overlay doesn't get removed.
![octobercms backend completely blocks](https://cloud.githubusercontent.com/assets/388176/10693389/3179b77c-7998-11e5-81e9-8196621c8e1b.png)

**Comment by alekseybobkov** [comment] 2015-10-24 00:34
Please post instructions for replicating the error. Thanks.

**Comment by JanvanCasteren** [comment] 2015-10-24 21:23
It happens when you click on some (not all) Components, to edit their settings (see screenshot that I provided). Components that are affected are e.g. all the components of the Blog plugin and also the Account component.
The error is caused in a file called storm.min.js. That makes me think that there might be a dependency that doesn't get updated in the update proces of October?

**Comment by alekseybobkov** [comment] 2015-10-27 00:37
We still can't reproduce the error. Please confirm that:

* You can reproduce the problem in another browser.
* You can reproduce the problem after clearing cache and refreshing the CMS area in your default browser.
* There are no other JavaScript errors logged before this error occurs.

Thanks

**Comment by JanvanCasteren** [comment] 2015-10-27 21:28
Is happening in Chromium on a linux machine (Version 45.0.2454.101 on Ubuntu 14.04 (64-bit)). 

I cannot reproduce the error in Firefox on the same machine. In Firefox it works fine.

I don't have more time now, but next week I will try to find some time to find out what is going on in Chromium.

**Comment by daftspunk** [comment] 2015-10-28 20:33
Hey there,

This has been fixed in dca9effec04dd08a00b92f9ce797afc7f69d2a59, please confirm by updating your copy of October. Here are some instructions on how to test the fix:
- enable `edgeUpdates` in your configuration
- update to build 308

**Comment by JanvanCasteren** [comment] 2015-10-29 11:04
Problem solved! I think you can close this issue.

**Closed** 2015-10-31 06:04 UTC
Labels: unconfirmed bug
