### ISSUE TITLE
No redirects for trailing slash URLs

### ISSUE THREAD

**Issue by jan-vince** [octobercms/october#2218] opened 2016-07-16 20:16 UTC
##### Expected behavior

I have Page with URL `/contact`.
If I try in browser `www.domain.com/contact/`, it should be redirected to `www.domain.com/contact` automatically.

_And vice versa if URL is set to `/contact/`._

Router **should respect** the URL I actually set in Pages' URL field. It's NOT about simply remove trailing slash.
##### Actual behavior

Same Page is rendered on both variants (with OR without trailing slash) - so this has a very bad impact on SEO.

_It can be partially solved by adding rel="canonical", but this is not a real solution._
##### Reproduce steps

If Page's URL is set to `/contact`, visiting `www.domain.com/contact/` will not redirect to expected `www.domain.com/contact`.
##### October build

349

---

This problem was mentioned several times before here: #1023, #1022, #1044

There is even a commit octobercms/library@690b4d5 (from May 16, 2015) where this problem was (partially) solved.

But this changes are gone now.

_And also 'enableRedirects' param is not anymore mentioned in config/cms.php._

---

_I have edited this issue to better suit octobercms guidelines._

**Comment by daftspunk** [comment] 2016-07-18 21:14
We determined this might be too opinionated and it isn't really a big issue, for example

This URL: https://github.com/octobercms/october
Is the same as this: https://github.com/octobercms/october/

GitHub allows it, and it probably isn't a problem so long as all URLs are generated in a consistent fashion, which they are. So this would leave it up to the web server configuration, or even a plugin, to handle the desired redirection logic.

Didn't know about the `rel="canonical"` trick, cool!

**Comment by jan-vince** [comment] 2016-07-19 06:30
You are right, this is not a big deal.

There is a [Google's blog post about this](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html). [Nibbler](http://nibbler.silktide.com) points this as a problem if both pages (with or without trailing slash) exists and return same content.

*But to be true, [specification doesn't help here much](https://tools.ietf.org/html/rfc3986#section-6.2.3) and consider both variants equal as it preserves schema semantics.*

#### Possible solutions

1. Use .htaccess to redirect `contact/` -> `contact`
 - I haven't found working Rewrite rule for subfolders sites :(
 - This prevents me from using some pages in site with trailing slash if I need it.

2. Use `rel="canonical"`
 - Right now the only way how to tell browsers, which URL's are preferred ones.

3. **[Feature request]** Extend October's settings to allow `strict URL schema` like this:

 - add configuration option `strictUrlSchema` to `config/cms.php`
 - modify core files to check for this option

*BTW it would be great if we can control HTTPS with some configuration options. I do not expect this to be some `magic`, but if I need some parts (backend) to be SSL secured, I would like to be able to control this from CMS - not from .htaccess.*

----

I think this is not so important right now, there are real bugs in that 200 open issues.

I will try to learn Laravel ASAP to be able to send some PR with possible solution.

**Comment by LukeTowers** [comment] 2017-10-18 21:36
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-18 21:36 UTC
Labels: Priority: Low, Type: Conceptual Enhancement

**Comment by hackolein** [comment] 2021-09-17 15:00
Ia there any Update on this? Because of Duplicate content.

**Comment by Samuell1** [comment] 2021-09-17 17:33
@hackolein you can handle this with htaccess or nginx configurations if "/" is on end present redirect without it.

**Comment by jan-vince** [comment] 2021-09-17 18:08
After 4 years I still think we should have a (optional) way to prevent duplicated URLs for single pages. 

`.htaccess` rules can be quite tricky when on shared hosting. 

I still use `canonical` and hope this to be solved one day :)

**Comment by Samuell1** [comment] 2021-09-17 20:51
@jan-vince there is no other way then redirecting in apache or nginx without causing too much pain, even laravel default routing doesnt solve this. Even github doesnt care about that or any other big websites :D

**Comment by daftspunk** [comment] 2021-09-18 06:04
The application should not really be concerned with server policy. The problem is, you end up in a situation where the webserver fights with the application logic. For example, where the URL has a collision with the existing directory structure, Apache will get confused with a URL such as `/plugins` where the directory called `plugins` also exists. In this case, it will force a trailing slash, and if the application wants to force no trailing slash, the application conflicts with the server and causes an error. 

Nonetheless, please submit this concern to the [multi-site roadmap feature](https://portal.octobercms.com/c/28-native-multi-site-support). It is possible we can introduce this type of policy as part of a site definition.

**Comment by flyingbaba** [comment] 2023-03-07 07:45
I was always solving this issue with a very simple mod_rewrite rule: 

    ## 301 Redirects with no trailing slashes 

    RewriteCond %{REQUEST_FILENAME} !-d 
    RewriteRule ^(.*)/$ /$1 [L,R=301]
