### ISSUE TITLE
artisan october:install fails withe SQLite database

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3359] opened 2018-01-15 11:09 UTC
##### Expected behavior
Installs October CMS correctly

##### Actual behavior
PDO Error

In Connection.php line 664:

  SQLSTATE[HY000]: General error: 1 no such table: system_settings (SQL: select * from "system_settings" where "item"  = system_log_settings limit 1)

In PDOConnection.php line 79:

  SQLSTATE[HY000]: General error: 1 no such table: system_settings

In PDOConnection.php line 77:

  SQLSTATE[HY000]: General error: 1 no such table: system_settings

##### Reproduce steps
composer create-project october/october MyWebsite
cd MyWebsite
php artisan october:install

Choose database type 2 when prompted
Accept default database location

##### October build
1.0.432

**Comment by buuug7** [comment] 2018-01-15 12:14
this need be fixed, caused by recent 432build, under processing

**Comment by LukeTowers** [comment] 2018-01-15 16:27
@SeriousKen this is because the default is set to MySQL in .env, and .env is generated on project creation with Composer as of Build 432. @buuug7 is working on a Regular Expression for the ConfigWriter class to handle env() values for configs, but in the meantime you can change the config in .env to point to your SQLite database and then run `php artisan october:up` to run the migrations.

**Comment by daftspunk** [comment] 2018-01-24 07:10
Should be fixed in Build 433+

**Closed by daftspunk** 2018-01-24 07:10 UTC
Labels: Status: In Progress, Type: Bug

**Comment by jordila** [comment] 2018-05-15 18:06
yet, same issue happened here ... on version 
```
Installing october/october (v1.0.435)
```

> i find it quite confusing that there's Database choice being offered on one hand ... and MySQL choice is default on the other?

**Comment by LukeTowers** [comment] 2018-05-17 06:53
@jordila was it the same issue? Build 435 shouldn't generate the .env file on install anymore so you shouldn't have the same issue.
