### ISSUE TITLE
Allow use of folder to be used for different scripts

### ISSUE THREAD

**Issue by nyxzryu** [octobercms/october#2534] opened 2016-12-02 03:19 UTC
Hi,

Also needed this to be done. What i want is i want to exclude some folder (/test, /chat, /shortener). I wanted that folder to use another script that's not october part like, my own shortener, using chat script, etc). However, for accessing php files, it returns blank pages.
What i already did is :

1.    Editing my .htaccess in the folder where my october is installed, i added :

```
    RewriteEngine On
    RewriteRule ^(test|test2|test3|test4|test5)($|/) - [L]
```

But when i access /test/myfiles.php it returns blank page, while i access /test/myfiles.html it works

2.    Editing my .htaccess in the folder where i need to exclude the folder (for ex: /test ) is installed, i added :

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule !index\.php$ /index.php [L]
```

Stll no luck, and returns blank page.

Any solution ?

#Build : 
382

**Comment by jBOKA** [comment] 2016-12-02 15:26
Maybe you should move these files to a plugin in case of scripts and assets.

Why do you need these folders in the root?

**Comment by nyxzryu** [comment] 2016-12-02 16:32
I mean like this, 

So i installed October in root /, then i want install another script, ex wordpress in /profile dir. So what i want is how to make /profile to be work for the wordpress ?
So i have 2 cms installed, october in my root /, and wordpress in /profile.
Because like my setting above, the php files are not readable (only shows blank page).

**Comment by jBOKA** [comment] 2016-12-02 16:35
This is not supposed to work like this. I don't think it's a good idea to mix to different systems on the file level. Maybe create virtual hosts on webserver level to reserve the /profile url for wordpress.

See october handles the routing through the root index.php. Take a different approach...

**Comment by nyxzryu** [comment] 2016-12-03 12:51
Its not only for WP, my native php scripts that i made are wont work too. It's native php CRUD, which i used for different things outside of october .-.
Also i dont familiar with october blogging system although i have already saw the video tutorial about making blog, maybe because it's only showed us the very basic how to implement blogging system with blog plugin .-.

**Comment by jBOKA** [comment] 2016-12-03 15:31
StGB

**Comment by jBOKA** [comment] 2016-12-03 15:40
Either you can wrap these functions in classes and integrate them into October via the plugin structure or you have to ask yourself what you need October for... I don't understand your whole approach.

**Comment by leocavalcante** [comment] 2016-12-06 19:04
Have you tried to add theses folders to the `## White listed folders` section of [October's .htaccess](https://github.com/octobercms/october/blob/master/.htaccess#L28)?

**Comment by daftspunk** [comment] 2016-12-10 06:58
There are several layers of protection at work here, the layer you are hitting here is the statement that says

> Block all PHP files

If you remove this line, a layer of security will be removed, but it will allow the PHP files to execute 

```
RewriteCond %{REQUEST_FILENAME} \.php$
```

(This looks like a duplicate of #1615)

**Closed by daftspunk** 2016-12-10 06:58 UTC
