### ISSUE TITLE
Frontend form - action missing "/"

### ISSUE THREAD

**Issue by sulazix** [octobercms/october#1112] opened 2015-05-07 05:16 UTC
Hi, Got an issue with {{form_open() }} on apache server; It Works perfectly on local but when I push my plugin in Prod (on Apache server) I got an issue with the generated form header :

    <form method="POST" action="https://www.domain.ch/intranet" accept-charset="UTF-8" id="rembform" enctype="multipart/form-data">

The form don't work without an extra "/" slash at the end of action :

      <form method="POST" action="https://www.domain.ch/intranet/" accept-charset="UTF-8" id="rembform" enctype="multipart/form-data">

Hope it's clear enough ;-)

**Comment by daftspunk** [comment] 2015-05-09 03:07
Duplicate of #634

**Closed by daftspunk** 2015-05-09 03:07 UTC
