### ISSUE TITLE
Taglist value safed as php array

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2717] opened 2017-02-27 19:27 UTC
##### Expected behavior
Loading the taglist value without errors.

##### Actual behavior
Get this error: 
explode() expects parameter 2 to be string, array given.

It looks like the settings model is populated with a php array as the field value. 

##### Reproduce steps
Create settings model with a taglist field. 

##### October build
Latest

**Comment by LukeTowers** [comment] 2017-02-28 00:22
Please include detailed replication instructions with what your code looks like and where it is.

**Comment by surahmans** [comment] 2017-02-28 00:34
I have got the same error and I found there was my mistakes. But
unfortunately I forgot what the mistakes is. :D

So give us your steps please to reproduce the error.

**Comment by SebastiaanKloos** [comment] 2017-03-15 22:46
1. Create a backend settings controller with form
2. Add a taglist formwidget
3. Try to save your data entered

**Comment by surahmans** [comment] 2017-03-15 23:24
Could you give your snippet code in fields.yaml?

**Comment by daftspunk** [comment] 2017-04-05 21:53
Something here doesn't add up. This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by daftspunk** [comment] 2017-04-05 21:53
Something here doesn't add up. This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by florin-postolache** [comment] 2017-06-13 09:26
Even if the mode is set to string, the value saved as an array, so a hotfix I ended up with is this
 return ($this->mode === static::MODE_STRING <b> && !is_array($value)</b>)
            ? explode($this->getSeparatorCharacter(), $value)
            : $value;
in TagList.php inside getLoadValue()

**Comment by jrnski** [comment] 2017-06-22 08:02
fix from @florin-postolache works for me in string and array mode.

**Comment by LukeTowers** [comment] 2017-06-22 14:59
@florin-postolache @jrnski do one of you want to make a PR to the develop branch to fix this? Then I can get it merged so this issue can be closed.

**Comment by LukeTowers** [comment] 2018-08-06 02:42
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Closed by LukeTowers** 2018-08-06 02:42 UTC
Labels: Status: Revision Needed, Type: Unconfirmed Bug
