### ISSUE TITLE
Repeater in tab

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2511] opened 2016-11-25 09:36 UTC
##### Expected behavior
Repeater working in tabs

##### Actual behavior
You get an error

##### Reproduce steps
Add a repeater field to a primary tab

##### October build
382

**Comment by daftspunk** [comment] 2016-11-28 21:05
Repeater seems to be working fine in tabs in the [test plugin](https://github.com/daftspunk/oc-test-plugin) .

This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by SebastiaanKloos** [comment] 2016-11-28 21:22
I guess it only occurs when you do not have a field in the upper section of the form. So you only have repeaters in tabs and no other fields.

**Comment by daftspunk** [comment] 2016-12-02 19:56
Still unable to replicate this. Need complete instructions.

**Comment by SebastiaanKloos** [comment] 2016-12-02 20:38
I will add it to the test plugin so you can see it yourself.

**Comment by LukeTowers** [comment] 2017-01-28 06:57
@SebastiaanKloos Will you be adding the test case to the test plugin for our review?

**Comment by SebastiaanKloos** [comment] 2017-01-28 07:46
Sory for the late reaction. I will add it as soon as possible.

**Comment by LukeTowers** [comment] 2017-03-01 21:28
Addressed in #2481, fixed in https://github.com/octobercms/october/commit/f4f7355bf23d786937bc6b454dc7bdc1a4dba911

**Closed by LukeTowers** 2017-03-01 21:28 UTC
Labels: Status: Revision Needed, Type: Unconfirmed Bug
