### ISSUE TITLE
Renamed folder stays in filesystem 

### ISSUE THREAD

**Issue by suntrop** [octobercms/october#2281] opened 2016-08-03 09:35 UTC
##### Expected behavior

Renamed folder 
##### Actual behavior

Folder is kept and new folder is created
##### Reproduce steps

Using the CMS backend:
1. Create a page and use folder/page as filename
2. Rename "folder" to "foldernew"
3. In your file system is an empty "folder" and a new "foldernew"
##### October build

351

**Comment by daftspunk** [comment] 2016-08-03 09:57
This is fine. Not really a bug, I suppose?

**Comment by suntrop** [comment] 2016-08-03 11:39
How can this be fine?
That way you collect a lot of unwanted folders and the user is not aware of them, because he doesn't see them.

**Comment by jan-vince** [comment] 2016-08-03 15:20
And you would  expect a folder to be renamed/moved when a single file path is changed?
What about other files in that folder?

But it would be great if we can click on a folder name in pages/partials/.. tree and have options to rename it (maybe with form in right pane ?).

**Comment by suntrop** [comment] 2016-08-04 11:08
There are no other pages, see Reproduce steps above

**Comment by daftspunk** [comment] 2016-08-04 11:11
This is simple to fix, delete the directory if it is empty after deleting the CMS template. We just need to be careful and think about circumstances when the directory should not be deleted. There is no easy way to tell if it was created by the CMS or by the user manually.

**Comment by tschallacka** [comment] 2016-08-23 11:30
I would be against deleting folders when renamed by user.
Some plugins might have saved files in those folders which are referenced by a varaible in the database. 

Plugins could be broken by such unexpected behaviour. If there were to be auto deletion/actual rename there also needs to be an system wide event which can be hooked in to update the database paths that contain that for the plugin devs.

**Comment by daftspunk** [comment] 2016-09-02 22:42
I tend to agree. Orphaned folders isn't an Armageddon scenario.

**Comment by LukeTowers** [comment] 2017-10-18 21:28
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-18 21:28 UTC
Labels: Priority: Low, Type: Maintenance
