### ISSUE TITLE
Possibility to set permissions for fields into backend Forms.

### ISSUE THREAD

**Issue by Samorai** [octobercms/october#3129] opened 2017-09-22 10:05 UTC
Hi. 

@LukeTowers  what are you thinking about some enhancement for backend forms?

I've propose to create some way to possibility for set permissions for any field into backend forms.

**Comment by LukeTowers** [comment] 2017-09-22 16:11
There's already an issue / PR open for this. Duplicate of #1837

**Closed by LukeTowers** 2017-09-22 16:11 UTC
