### ISSUE TITLE
Flash message will be shown twice

### ISSUE THREAD

**Issue by kealsera** [octobercms/october#2869] opened 2017-05-16 20:14 UTC
##### Expected behavior
Flashmessage shows each message once.

##### Actual behavior
Userinteraction will lead to a Flashmessage. After Pagerefresh this message is shown once. If the user refreshes the page again (or visits another one) the same message will be shown once more. It will not show up a third time.

Here's a video showing the bug in action using the rainlab user login:
https://youtu.be/nk8jGKkGNiE

##### Reproduce steps
I have multiple occasions where this happens, even with the UserLogin Plugin.
Thise code will show 2 messages,regardless what happens

```
public function onBannerSave()
    {
        if(Input::file('banner') != null)
        {
            try
            {
                //[..not relevant..]
                Flash::success('Banner updated successfully!');
            }
            catch(Exception $e)
            {
                Flash::error($e->getMessage());
            }
            finally
            {
                return Redirect::refresh();
            }
        }
        else
        {
            Flash::warning('No Banner provided!');
        }
    }
```

This code will show only one message 

```
public function onBannerSave()
    {

            try
            {
                //[..not relevant..]
                Flash::success('Banner updated successfully!');
            }
            catch(Exception $e)
            {
                Flash::error($e->getMessage());
            }
            finally
            {
                return Redirect::refresh();
            }
    }
```

This is my errorhtml:

```
<div class="fixed-top container" style="z-index:9999999;top:5%">
    <div class="row">

        {% flash %}
        <div class="errorMSG col-12 alert alert-{%if type == 'error'%}danger wow shake{%else%}{{type}}{%endif%}">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <strong>{{type|capitalize}}</strong> {{ message }}
        </div>
        {% endflash %}
    </div>

</div>


  jQuery(document).ready(function () {
        if (jQuery(".errorMSG") == null)
            return;
        jQuery(".errorMSG").alert();
        jQuery(".errorMSG").fadeTo(3000, 500).slideUp(500, function () {
            jQuery(".errorMSG").slideUp(500);
        });

    });
```

##### October build
419

**Comment by daftspunk** [comment] 2017-06-23 11:00
Perhaps you could prepare a simple theme that demonstrates the issue.

**Comment by SebastiaanKloos** [comment] 2017-06-23 14:07
I had this problem too. I had the framework js two times in my theme. Perhaps you have the same.

**Comment by kealsera** [comment] 2017-06-23 14:27
@SebastiaanKloos you mean the framework tag?

That's unfortunetly not the case:
![image](https://user-images.githubusercontent.com/10854875/27486410-c0830266-5830-11e7-998e-00958f717b95.png)


I'll try to get the theme thing done throughout the weekend.

**Comment by daftspunk** [comment] 2017-06-23 22:51
Thanks @kealsera, the code provided in the original post looks fine. A theme would help us understand what's going on here.

**Comment by kealsera** [comment] 2017-07-03 08:55
@daftspunk Took me a lil longer to compile that theme, sorry for that.

https://www.dropbox.com/s/edcej26mnmszdtg/clean.zip?dl=0

I've created a page which will create an error - this error will show up if you go to home a second time before it disappears.

https://www.dropbox.com/s/aeee5o33bafje7i/clean.zip?dl=0

**Comment by mkelcik** [comment] 2017-07-20 12:47
In class October\Rain\Flash\FlashBag you can override parent method getMessages()
``public function getMessages()
    {
        $messages = $this->messages;
        $this->forget();
        return $messages;
    }``

**Comment by mkelcik** [comment] 2017-07-20 13:20
I think, problem is in Cms\Twig\FlashNode on line ``foreach (Flash::getMessages() as $type => $messages) {``. Method getMessages() do not forget Flash messages, so they are visible after next refresh (than purge in October\Rain\Flash\FlashBag constructor happen)

Quick fix is to create method  `` public function getMessagesAndForget()
    {
        $messages = $this->messages;
        $this->forget();
        return $messages;
    }`` in October\Rain\Flash\FlashBag and use this one instead.

**Comment by saleksin** [comment] 2017-09-04 17:23
I can confirm, that this issue is still present. Can anybody provide example of theme, where this problem does not exist? In my theme I display flash messages like this:
```
{% flash %}
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="alert alert-{{ type }}">
                    {{ message }}
                    </div>
                </div>
          </div>

        </div>
    </div>
{% endflash %}
```
Is it ok?

**Comment by frank-beta** [comment] 2017-11-03 00:47
still present, attached sample theme:


[foo.zip](https://github.com/octobercms/october/files/1439789/foo.zip)

**Comment by LukeTowers** [comment] 2017-11-03 06:05
@saleksin because those theme authors haven't implemented it.
@frank-beta could you look into making a PR to fix the issue?

**Comment by frank-beta** [comment] 2017-11-08 13:50
@LukeTowers a total newbie here, the PR is to confirm the bug? obviously I don't know how to fix it...

**Comment by LukeTowers** [comment] 2017-11-08 15:01
@kealsera @mkelcik Could you two look into making a PR to fix it as well?
@frank-beta the Pull Request is to fix the bug :) Nobody here knows how to fix the bug until they actually try to do so. If they did, it would already be fixed. I'd encourage you to dig in and read the code and try to understand fully what's going on enough to provide a fix for the issue, it'd be a very educational experience.

**Comment by jordanplamondon** [comment] 2018-06-20 15:10
Adding this in Flashbag.php fixes the issue :

```
public function getMessages()
{
        $messages = $this->messages();
        $this->purge();
        return $messages;
 }
```

**Comment by gregkasmark** [comment] 2018-11-05 21:49
This could also be caused by not using data-request-flash tag on the element requesting ajax.

**Comment by gregkasmark** [comment] 2018-11-05 21:52
Messages can be shown twice if you're requesting ajax from an element (ex: button or link) and haven't specified the **data-request-flash** attribute.

**Comment by LukeTowers** [comment] 2019-04-19 19:25
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Closed by LukeTowers** 2019-04-19 19:25 UTC
Labels: Status: Revision Needed, Type: Unconfirmed Bug
