### ISSUE TITLE
Update partial with ValidationException 

### ISSUE THREAD

**Issue by Alex360hd** [octobercms/october#3507] opened 2018-04-15 09:27 UTC
Hello,

I'm working with form validation and I wonder if it's possible to update a partial when using ValidationException.

I really like the inline field error that the ValidationException provide with data-request-validate feature, the problem is that I would also update a partial in addition to the inline error on fields.

Could do it without problem with AjaxException (but I lose the inline validation of fields). How can I combine both ?

**Comment by LukeTowers** [comment] 2018-04-16 00:24
@Alex360hd hook into the events directly through the [JS API](http://octobercms.com/docs/ajax/javascript-api); you want the `ajaxValidation` event: https://github.com/octobercms/october/blob/master/modules/system/assets/js/framework.js#L239

**Comment by Alex360hd** [comment] 2018-04-16 06:54
Hello, 

Thank you for your reply, but I'm not sure it answer the question.

I know about ajaxValidation event, the problem is that you loose inline field validation by using it.

My goal is to combine both, being able to keep the october cms feature to display errors on field level **AND** to update a partial.

**Comment by Alex360hd** [comment] 2018-04-16 07:34
I'm working with Magic form plugin and I try to improve it.

In the ajax handler function, there is that code : 

            // THROW ERRORS
            // inline_errors == 'display' is a component option to display october cms inline error system
            if ($this->property('inline_errors') == 'display') {
                throw new ValidationException($validator);
            } else {
                throw new AjaxException($this->_exceptionResponse($validator, [
                    'type'    => 'danger',
                    'title'   => $message,
                    'list'    => $validator->messages()->all(),
                    'jscript' => $this->property('js_on_error'),
                ]));
            }

The plugin works by inserting a partial in a div on the form, that partial handle all form feedback (insert an alert on error or success, inject somme javascript that you would like to trigger on error or success etc....)

If I check to display inline validation (and so, ValidationException is triggered instead of AjaxException), I see that the partial is no longer injected, and that's normal, because ValidationException don't provide the same parameters than AjaxException to inject partial.

That's why I'm asking here what would be the best solution ?

**Comment by Alex360hd** [comment] 2018-04-16 09:03
Hello,

Yes I created an [issue on it's plugin page](https://github.com/skydiver/october-plugin-forms/issues/102).

I try to create PR to make it's maintainer job easier, but, after analyzing the code, I see that it correctly used the core october validation system, and that the ValidationException don't allow to embed a partial like AjaxException.

So I'm not sure where the job is. Does october should be updated to allow partial with ValidationException, or does MagicForm needs to find a way to manually inject the partial to the form before triggering ValidationException cause this one can't inject partials.

**Comment by LukeTowers** [comment] 2018-04-16 19:03
So are you saying that you need it to handle flash messages as well as inline field validation?

**Comment by LukeTowers** [comment] 2018-04-17 16:39
Can you use the pull method of updating partials: http://octobercms.com/docs/ajax/update-partials#pulling-updates?

**Comment by LordBuzzard** [comment] 2018-05-11 13:19
@Alex360hd Hi Alex,

Hi recently had to face this issue and the following is what I have done to unable inline errors.

Very often you will have to look at the code to get the full capabilities and internal logic behind October CMS as it's documentation isn't complete (even if they have documented a lot)
By digging into the exception handling when using AjaxHandlers you will realise that VaidationExceptions (when combined with a Validator instance) will instanciate fields and messages for these fields : 
```
    /**
     * Evaluate errors.
     */
    protected function evalErrors()
    {
        foreach ($this->errors->getMessages() as $field => $messages) {
            $this->fields[$field] = $messages;
        }

        $this->message = $this->errors->first();
    }
```

Then when you throw your ValidationException to the AjaxHandler controller ( `execAjaxHandlers()` ) it uses the fields and messages from the ValidationException to create and thow an AjaxException (which is the correct thing to do because we are executing Ajax calls) : 

```
                /*
                 * Handle validation errors
                 */
                $responseContents['X_OCTOBER_ERROR_FIELDS'] = $ex->getFields();
                $responseContents['X_OCTOBER_ERROR_MESSAGE'] = $ex->getMessage();
                throw new AjaxException($responseContents);
```

Now, you have reproduce this behaviour when using the plugin MagicForm at the appropriate time.
For me it was while building the exception response : 

```
    private function exceptionResponse($validator, $params)
    {

        // FLASH PARTIAL
        $flash_partial = $this->property('messages_partial', '@flash.htm');

        // EXCEPTION RESPONSE
        $response = ['#' . $this->alias . '_forms_flash' => $this->renderPartial($flash_partial, $params)];

        // INCLUDE ERROR FIELDS IF REQUIRED
        if ($this->property('inline_errors') != 'disabled') {
            $ex = new ValidationException($validator);
            $response['X_OCTOBER_ERROR_FIELDS'] = $ex->getFields();
            $response['X_OCTOBER_ERROR_MESSAGE'] = $ex->getMessage();
        }

        return $response;
    }
```

Hope it can help you & other people with similar issues.

**Comment by LukeTowers** [comment] 2018-05-11 15:51
@LordBuzzard if there are any improvements to the October documentation that you think could be made after digging into the code I would greatly appreciate PRs to the [documentation repository](https://github.com/octobercms/docs)

**Comment by LukeTowers** [comment] 2018-08-22 21:29
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Closed by LukeTowers** 2018-08-22 21:29 UTC
Labels: Type: Question
