### ISSUE TITLE
Datatable Not Saved When Inside Repeater

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#4063] opened 2019-01-15 14:29 UTC
- OctoberCMS Build: 446
- PHP Version: 7.1
- Database Engine: mysql
- Plugins Installed: 

### Description:
Adding a `datatable` form widget inside a `repeater` doesn't save the data.

### Steps To Reproduce:
https://github.com/octoberrain/test-plugin/pull/61

**Comment by LukeTowers** [comment] 2019-01-15 19:08
@bennothommo this something you'd be interested in looking into?

**Comment by bennothommo** [comment] 2019-01-16 00:58
@LukeTowers no worries, will have a look.

**Comment by bennothommo** [comment] 2019-01-16 14:05
I'd say it's a confirmed bug. It appears the Datatable widget is not following the same form key structure that other fields inside the repeater use on form submit.

![screenshot from 2019-01-16 21-57-55](https://user-images.githubusercontent.com/15900351/51253719-16f17a80-19da-11e9-8b11-7ad893dbb495.png)

eg. The suburb field inside the repeater has the form key `Country[states][0][item][1][subtitle]` whereas the safety datatable just starts with `safetyTableData`.

The way that data tables return their data lead me to believe they are not set up to be used more than once on a page.

**Comment by LukeTowers** [comment] 2019-01-16 15:38
This https://github.com/octobercms/october/blob/master/modules/backend/widgets/Table.php#L81-L86 is probably the problem. It might need to be changed to use `$this->alias` instead

**Comment by LukeTowers** [comment] 2019-01-16 15:41
@bennothommo the `alias` property is usually the one used to construct the actual `name` attributes for the inputs on a form, and this alias gets passed around by the [Repeater](https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/Repeater.php#L268) and the [Nested Form](https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/NestedForm.php#L47) and the [Relation Controller](https://github.com/octobercms/october/blob/master/modules/backend/behaviors/RelationController.php#L725). The `alias` property is used for generating the field names and for namespacing the AJAX handlers

**Comment by bennothommo** [comment] 2019-01-17 00:40
@LukeTowers The `alias` is already fed through this line here I believe:
https://github.com/octobercms/october/blob/master/modules/backend/widgets/Table.php#L61

I feel It might have something to do with the `arrayName` value that is defined in the `FormField` class encasing the widget - it doesn't seem to feed down into the `Table` widget, or doesn't seem to be handled in any way. When I added the `arrayName` to the `fieldName` of the `Table` widget, it did actually save the table data in the database - although it contains said data in a TableData JSON object. It also couldn't *load* the data after save.

**Comment by LukeTowers** [comment] 2019-01-17 02:50
Interesting, are you able to continue digging into it further @bennothommo or do you need me to take a longer look at it?

**Comment by bennothommo** [comment] 2019-01-17 03:03
I'll be happy to continue looking into it, but I anticipate my spare time over the next couple of weeks will be very limited.

I have noticed that the data tables in the Builder plugin are being processed via JS first in which the data is extracted from the table. This is before it ever reaches the AJAX handlers. I have yet to actually see it used in a standard form context yet.

Maybe throw the "Help wanted" label on this one, as I'd be keen to hear from anyone who has used the datatable in a project or plugin and if they did just add it through a form config and used the standard save functionality or if they require some extra handling in place first.

**Comment by bennothommo** [comment] 2019-01-27 06:34
@LukeTowers I've continued to look into this a bit further. I might have set it up incorrectly, but I've found the datatable doesn't really save correctly even outside of a repeater because of the way it renames the field data to `<fieldName>TableData`, so unless you've set up a model to specifically handle the data with that name, you can't just simply the use the datatable as is.

I've noticed with the datatable widgets in the Builder plugin, the data is extracted via JS and saved in an AJAX call. It's possible that this was the intended way of using it when it was built.

We could potentially rewrite this to use a standard field name on save, but I am concerned it may cause a BC break for anyone currently using it.

**Comment by LukeTowers** [comment] 2019-01-27 17:50
@bennothommo isn't that the purpose of the getSaveValue() method, to interpret the data that gets sent to the server and return it in a useful form to the Form widget? https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/DataTable.php#L108

**Comment by seanthepottingshed** [comment] 2019-01-31 13:47
@LukeTowers @bennothommo

https://www.bountysource.com/issues/68728539-datatable-not-saved-when-inside-repeater

**Comment by LukeTowers** [comment] 2019-02-04 18:52
Fix will be in the next build (448). @seanthepottingshed please release the bounty to @bennothommo

**Comment by bennothommo** [comment] 2019-02-04 23:50
@LukeTowers I'm happy for the bounty to go to the October war chest :)

**Comment by LukeTowers** [comment] 2019-02-05 04:39
@bennothommo thanks, I appreciate that and the code contributions!

**Closed** 2019-02-05 04:40 UTC
Labels: Status: Completed, Type: Bug

**Comment by LukeTowers** [comment] 2019-02-05 08:03
Appreciate it @seanthepottingshed. If you don't mind, I'd prefer bounties were run straight through PayPal, bountysource takes a 10% fee for not really that much added value in my opinion.

**Comment by seanthepottingshed** [comment] 2019-02-06 07:13
@LukeTowers 

Sorry I wasn't aware of the 10% tax - absolutely no problem going forwards, should I just totally bypass Bountysource in the future? 

I'll DM you on Slack when I see you're about.
