### ISSUE TITLE
[FeatureRequest]: Warn users when uploading duplicate file names to the media manager

### ISSUE THREAD

**Issue by buuug7** [octobercms/october#3124] opened 2017-09-20 05:48 UTC
## description
if upload two same name files into media manager, the files uploaded later will  auto overwrite the previous file without prompt.   what did i do for prevent  auto overwrite? i have many files in one directory,about 5000, when i upload new files into media manager, i must check the file name first, but this become more difficulty when the numbers of files getting more and more .  

did there have any good solutions?

**Comment by korneliuskristianr** [comment] 2017-09-20 06:13
@buuug7  Just Create a folder then upload the same file into that folder

**Comment by buuug7** [comment] 2017-09-20 06:24
@korneliuskristianr if you editor a article and add  images  with richeditor with 
![image](https://user-images.githubusercontent.com/12119289/30629442-691db092-9e0e-11e7-8f47-36917b909ba8.png)
it will auto upload image into `uploaded-files` directory, when you add a second article , also with a same name image, it will overwrite the previours images. when you see your article, first article and second article have a sample image. but people need it different.   

want i need do?

**Comment by buuug7** [comment] 2017-09-20 06:33
if uploaded files generate a random string name , it will prevent this problem. for same image ,user can manager manually, like below, just delete the same images. 
![ef](https://user-images.githubusercontent.com/12119289/30629872-abfb172c-9e10-11e7-9f1d-8e1ad177dbb7.png)

**Comment by tgz-cz** [comment] 2017-09-20 07:15
I have same problem with the media manager.

I override important file (that was uploaded in past) with newer file with same filename.
None prompt or error or warning was displayed.

I have few questions:

1. Is there any configuration for change this behaviour to raise error in this case or auto-rename newly uploaded file?

2. Or is it possible change this behaviour via events/extensions/plugins of MediaManager?

3. Another way is using my own model with related "File Attachments" ('System\Models\File') instead of MediaManager. There is not problem with overriding existing files, but if user downloads the file then original filename is lost and the filename is 558ab0f0aa231581256800.xls instead.
It is possible download this file with original filename?

Thank you for answers

**Comment by buuug7** [comment] 2017-09-20 07:33
@tgz-cz i have not best solutions, it seems only by modifying the source code of `modules/cms/widgets/MediaManager.php` line 1098 ,as follows 
```
    protected function checkUploadPostback()
    {
        $fileName = null;
        $quickMode = false;

        if (
            (!($uniqueId = Request::header('X-OCTOBER-FILEUPLOAD')) || $uniqueId != $this->getId()) &&
            (!$quickMode = post('X_OCTOBER_MEDIA_MANAGER_QUICK_UPLOAD'))
        ) {
            return;
        }

        try {
            if (!Input::hasFile('file_data')) {
                throw new ApplicationException('File missing from request');
            }

            $uploadedFile = Input::file('file_data');
            // remove this line
            $fileName = $uploadedFile->getClientOriginalName();
            // add this line 
            $fileName = str_random(40);
```

**Comment by LukeTowers** [comment] 2017-09-20 19:11
@buuug7 feel free to submit a PR to add a warning popup if the file is going to get overwritten.

**Comment by buuug7** [comment] 2017-09-21 06:27
@LukeTowers how to determin the two files the same ?   
+ just for filepath and filename
+ check the two files MD5
the `MediaLibarary` have a method `exists`, it just detemines a file with the specified path exists in the library.  
so it not necessary to give the prompt when two files have a same filename, if upload file have  the same name with already updated files. just rename the filename. it was simple.  this is also work when use richeditor upload file.

```
            // only throw a exception
            if(MediaLibrary::instance()->exists($filePath)){
                throw new ApplicationException(Lang::get('cms::lang.media.file_exists'));
            }

            // rename with random name
            if(MediaLibrary::instance()->exists($filePath)){
                $fileName = File::name($uploadedFile->getClientOriginalName()) . '-' . str_random(40) . '.' . $extension;
                $filePath = $path . '/' . $fileName;
            }
```

**Comment by LukeTowers** [comment] 2017-09-21 16:11
I think the exception is better for now, until we get around to providing a popup that would let the user choose to rename the file on upload.

**Comment by buuug7** [comment] 2017-09-22 01:41
@LukeTowers Ok

**Comment by LukeTowers** [comment] 2017-10-16 18:59
Duplicate of #1117, closing that one and keeping this one open.

**Comment by MaxNozhkin** [comment] 2019-06-19 10:20
@daftspunk can you add some event before file upload or when filename is generating?

**Comment by LukeTowers** [comment] 2019-06-19 15:33
@MaxNozhkin there's the after upload event: https://octobercms.com/docs/api/media/file/upload. You could make a PR to propose a beforeUpload event if you'd like

**Comment by pavelmgn** [comment] 2019-09-09 17:12
I found a solution to rename and return the renamed file to the richeditor.
```
public function boot()
	{
		Event::listen('media.file.upload', function($widget, $filePath, $uploadedFile) {
			$originalName = $uploadedFile->getClientOriginalName();
			$sanitizedFileName = str_replace(' ', '-', $originalName);
			$user = BackendAuth::getUser();
			$sanitizedFileName = Carbon::now()->format('dmYHis') . $user->login . '.' . $uploadedFile->getClientOriginalExtension();
			$filePathChunks = explode(DIRECTORY_SEPARATOR, $filePath);
			$filePathChunks[(count($filePathChunks) - 1)] = $sanitizedFileName;
			$newPath = implode(DIRECTORY_SEPARATOR, $filePathChunks);
			$isRename = true;
			MediaLibrary::instance()->moveFile($filePath, $newPath, $isRename);
			header('Content-Type: application/json');
			echo json_encode(['result' => 'success', 'link' => MediaLibrary::url($newPath)]);
			exit();
		});
	}
```

**Comment by LukeTowers** [comment] 2019-09-09 18:18
@pavelmgn submit a PR to pass the $filePath argument as a reference instead, 

```php 
header('Content-Type: application/json');
echo json_encode(['result' => 'success', 'link' => MediaLibrary::url($newPath)]);
exit();
```

is a pretty hacky solution that is unnecessarily brittle. I don't think changing the event argument for this case to pass by reference instead is going to cause any breaking changes so submit a PR and I'll merge it in.

**Comment by pavelmgn** [comment] 2019-09-10 02:24
@LukeTowers #4612 
Sorry, if I did something wrong, the first time I did PR. Did that mean?

**Comment by bennothommo** [comment] 2019-10-14 00:51
#4616 makes `$filePath` a referenced variable, allowing the filePath to be changed via the `media.file.upload` event and providing a mechanism to prevent duplicate images. This will be released with build 460.

**Comment by LukeTowers** [comment] 2019-10-14 23:03
Note that #4616 does not solve this issue, it just makes it possible for a plugin to solve this issue instead. We can still consider a core solution to this specific issue.

**Comment by setianke** [comment] 2020-03-17 22:40
What about changing line 1533 and 1540 in /modules/backend/widgets/MediaManager.php

`$fileName = $fileNameClean . '.' . $extension;`

to 

`$fileName = $fileNameClean.date('YmdHi').'.'.$extension;`

Would be an easy fix and preventing files to be overwritten or is the file being overwritten the desired behavior?

**Comment by LukeTowers** [comment] 2020-03-18 06:54
@setianke the problem in my eyes is the current behaviour not giving the user the choice. I personally don't like including the upload date in the filename, so I would prefer that users on uploading a duplicate file were presented with the option to either cancel, replace, or keep both (in which case a (1), (2), etc) gets added to the latest upload's filename.

**Comment by setianke** [comment] 2020-03-18 16:36
@LukeTowers agreed, imo an option in the Settings enabling the automatic date in filename on/off or show warning with cancel/replace/keep both would be a good solution (just my 2cents)

**Comment by daftspunk** [comment] 2021-03-08 04:21
This is a good pickup. I have recorded this to be addressed in the next iteration of media manager. Thanks @buuug7!

**Closed by daftspunk** 2021-03-08 04:21 UTC
Labels: Priority: Low, Type: Conceptual Enhancement, help wanted
