### ISSUE TITLE
October upgrade from 419 to 428

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#3268] opened 2017-11-28 09:44 UTC
##### Expected behavior
a proper upgrade to the latest build

##### Actual behavior
Update failed

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>500 Internal Server Error</title> </head><body> <h1>Internal Server Error</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator, you@example.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.</p> <p>More information about this error may be available in the server error log.</p> </body></html>

##### Reproduce steps
upgrade the system page and confirm the upgrade

##### October build
419

**Comment by ametad** [comment] 2017-11-28 11:03
Major changes in OC updates can lead to these errors. Please read http://octobercms.com/support/article/rn-9

Perhaps one of the plugins you use are not compatible with the changes? 

Or:

> Known issues
> First update fails: When updating to Build 420 via the backend, the first update will fail with message Update failed. Simply refresh the page and run the update process a second time.

**Comment by LukeTowers** [comment] 2017-11-28 12:59
@chrisvidal what was the information available in the server logs?

**Comment by angelodmrch** [comment] 2017-11-29 13:15
I had the same issue, in my case the problem was that I still running with PHP 5.6 , updating to PHP 7.1 solve it.

**Comment by Samorai** [comment] 2017-12-01 12:37
@LukeTowers 
I had try to update from 419 to 428, and got `500 internal server error.`
Into server logs had: 
```
PHP message: PHP Fatal error:  Uncaught Error: Class 'Predis\Client' not found in *********/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PredisConnector.php:25
```
But I have QUEUE_DRIVER=redis

Steps to fix it:

1. Change env variables to
```
CACHE_DRIVER=array
QUEUE_DRIVER=file
SESSION_DRIVER=file
```
2. Update build
3. `composer require predis/predis`
4. Change back env variables, if you're using Redis.

@chrisvidal can you give your .env file?

**Comment by LukeTowers** [comment] 2017-12-01 15:55
@Samorai don't add dependencies to your project's composer.json, use the Drivers plugin instead. I have no idea how your site was working without it and using redis before. http://octobercms.com/plugin/october-drivers

**Comment by chrisvidal** [comment] 2017-12-02 01:36
OK I got it.
OC does mot upgrade if you are trying to upgrade the plugins RainLab.User at the same time.
So, skip the upgrade of RainLab.user first. Perform OC upgrade. Then perform upgrade of RainLab.User and it should work

thanks All

**Comment by Samorai** [comment] 2017-12-03 11:46
@LukeTowers ok, thanks. I have many dependencies which I added to composer.json, now I'll moving it to Drivers plugin.

**Comment by LukeTowers** [comment] 2017-12-03 18:50
@Samorai if your dependencies aren't included in the drivers plugin don't add them yourself. Read https://luketowers.ca/blog/how-to-use-laravel-packages-in-october-cms-plugins/

**Comment by gregorskii** [comment] 2018-01-08 00:15
I have this same issue. Should the updater be smart and know that it cannot update to a version that requires a different PHP version that the system supports? Seems like a bad practice to bomb the system when the admins have not installed PHP 7.

I would imagine it would update to the last version which supports the PHP version the system is on, which is version 1.0.419.

I have explicitly installed 419 in my vagrant install. I can't even attach a project without the server bombing with a 500.

**Comment by LukeTowers** [comment] 2018-01-08 01:52
@gregorskii could you detail exactly what is occurring to "bomb the system"?

**Comment by gregorskii** [comment] 2018-01-08 03:15
Before I update everything is fine, after server 500s every request. The update fails with a 500 as well.

I would have to rebuild the system to grab the exact error.

The server stack in question is using php 5.7.

**Comment by LukeTowers** [comment] 2018-01-08 05:16
So you've installed 419 and it's erroring when you try to attach a project?

**Comment by gregorskii** [comment] 2018-01-08 05:42
Yes, server does not have php 7 so I can not install anything newer.

**Comment by LukeTowers** [comment] 2018-01-08 14:41
@gregorskii when you tried to update to build >=420, you should have had to manually confirm the new requirements of PHP7: https://octobercms.com/changelog

**Comment by gregorskii** [comment] 2018-01-08 15:58
It will work without it 7.0, assuming one follows the instructions and fixes the known issues? Also I did not try to update the second time, I just tried to attack the project, does that trigger an update as well?

**Comment by LukeTowers** [comment] 2018-01-08 16:49
@gregorskii attaching a project will trigger an update to grab the plugins associated with the project. However, it's not going to serve you outdated versions of plugins that are compatible with 419. 

I cannot understate how much I recommend that you simply update to at least PHP 7 given the performance and security improvements in general of 7 and the fact that you will be missing out on any future security or performance improvements in October, not to mention bug fixes and future features. We will not be backporting any fixes for 419, so I highly recommend you upgrade to PHP 7 so that you can remain stable on this LTS release of Laravel.

**Comment by gregorskii** [comment] 2018-01-08 19:31
Understood that is my goal too, we manage quite a lot of projects and this is not one of mine. I am updating a related system and getting pulled into a world of hurt here. :)

I'll update it and let you know what I find.

**Comment by gregorskii** [comment] 2018-01-09 01:45
Think I was able to update PHP 7 in this projects Vagrant install.

Ran into #3321.

**Comment by LukeTowers** [comment] 2018-01-09 03:25
@gregorskii that's not a huge issue, just rerun `php artisan key:generate` after running `php artisan october:env`

**Comment by gregorskii** [comment] 2018-01-09 04:05
Yes, but the issue is it fails on composer new. That’s how the ansible job is creating the instance.

**Comment by gregorskii** [comment] 2018-01-09 07:05
Done. I had a few things I had to update:

cipher type, update the APP_KEY to new cipher
used locked composer.json file which removes the post install command to generate the key -> rather than using composer new to create a new october project in the container
install php7.2-zip
updated configs to .env type removing most custom configs in config/ (not required, but seems to make sense)
lots of other vagrant and ansible changes specific to this environment

Thanks for the help :)

**Comment by LukeTowers** [comment] 2018-01-09 13:06
Not a problem @gregorskii, glad I could help you update!

**Closed** 2018-01-09 13:06 UTC
Labels: Status: Response Needed, Type: Unconfirmed Bug
