### ISSUE TITLE
config relation toolbarButtons support for create on pivot data

### ISSUE THREAD

**Issue by jpruiz114** [octobercms/october#2786] opened 2017-03-30 17:21 UTC
##### Expected behavior
You as a developer for the October CMS should be able to use the create option on the **toolbarButtons** for pivot data.

Related ticket:

https://github.com/octobercms/october/issues/1553

##### Actual behavior
When you use the create option in the **toolbarButtons** on the config relation yaml file, and you try to create a new entity you will get a new error.

##### Reproduce steps
Use a pivot entity and add it to the config relations yaml file and use the create option for the **toolbarButtons**. You will get an error:

local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getId() on null in modules/backend/Behaviors/relationcontroller/partials/_manage_form.htm:1

**Comment by LukeTowers** [comment] 2017-03-30 17:30
Duplicate of #1409 and #1803. Eventually we'll get around to it, but there is a lot of stuff to do, and only three people at the core of the project. If you want it done faster, then post a bounty or implement it yourself and make a pull request.

**Closed by LukeTowers** 2017-03-30 17:30 UTC

**Comment by daftspunk** [comment] 2017-03-31 04:51
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by daftspunk** [comment] 2017-03-31 04:51
I think this may relate to pivot data not supported in deferred binding but I'm not sure. If you can show an example in the test plugin, this can be confirmed.

**Comment by mihailbishkek** [comment] 2019-04-16 19:40
What about attach image in pivot models?
