### ISSUE TITLE
RE: Allowed memory size of 134217728 bytes exhausted (tried to allocate 9796480 bytes) in https://github.com/rainlab/user-plugin Plugin

### ISSUE THREAD

**Issue by jason-migz** [octobercms/october#3752] opened 2018-09-04 04:57 UTC
##### Expected behavior
- I will redirect to UserPage when Log-in Authentication is valid

##### Actual behavior
When i try to login this Error is displayed Allowed memory size of 134217728 bytes exhausted (tried to allocate 9796480 bytes)
![44974908-9e8e9d80-af93-11e8-97da-11c53653e2dd](https://user-images.githubusercontent.com/21366028/45010790-c6d4d580-b041-11e8-996c-f2f6393cf08d.JPG)
![capture](https://user-images.githubusercontent.com/21366028/45010832-fc79be80-b041-11e8-92a7-ef2ac77ad9c2.JPG)

##### Reproduce steps
- Seed the RainLab.User Plugin for 10000 User
- Log-in with Username and password from the Seeded User Data

##### October build
442

**Comment by LukeTowers** [comment] 2018-09-04 06:50
Duplicate of #3747. Please be more careful.

**Closed by LukeTowers** 2018-09-04 06:50 UTC
