### ISSUE TITLE
Mail::fake() not working as expected

### ISSUE THREAD

**Issue by 4nik3t** [octobercms/october#4942] opened 2020-02-14 15:45 UTC
- OctoberCMS Build: v1.0.464
- PHP Version: 7.4.2
- Database Engine: MYSQL 5.7 InnoDB
- Plugins Installed: Rainlab.User

### Description:
I am trying to test some  functionality related to mails in my plugin. But the Mail::fake() does not work as expected as mentioned [here](https://laravel.com/docs/5.5/mocking#mail-fake) .

My testCase
```php
    public function testEmployerApplicationsNotification()
    {
        $user = factory(User::class)->states('activated')->create();
        Auth::login($user);

        $company = factory(Company::class)->create();
        $category = factory(Category::class)->create();

        $job = Job::create([
            'title' => 'Senior Software Engineer',
            'description' => 'Manage our big php applications',
            'positions' => 10,
            'company_id' => $company->id,
            'category_id' => $category->id
        ]);

        Mail::fake();

        $job->apply();

        Mail::assertSent('aniketmagadum.jobmanager::mail.candidate_applied', 1);
    }
```
The apply method where I have sent the mail.
```php
    public function apply()
    {
        $user = Auth::getUser();
        $this->applicants()->attach($user->id);
        Mail::send('aniketmagadum.jobmanager::mail.candidate_applied', [], function ($message) {
            $message->to('admin@domain.tld', 'Admin Person');
            $message->subject('This is a reminder');
        });
    }
```
I always get a error saying 
The expected ['aniketmagadum.jobmanager::mail.candidate_applied'] mailable was not sent.

But the email gets logged correctly If I use the Mail::pretend(); 

### Steps To Reproduce:
I will attach a PR to the test plugin soon

**Comment by alxy** [comment] 2020-02-25 11:16
I also encoutered this bug. October overrides how mails are send, but do not change the pretend method accordingly. I started building a working MailFaker, which I have never really finished: https://gist.github.com/alxy/6e74d306be7bd0c9d1f134f34d547a44

here is how you would use a custom Mail faker:
```php
public function testNewFakeMailer()
{
    Mail::swap(new MailFake());

    // These variables are available inside the message as Twig
    $vars = ['name' => 'Joe', 'user' => 'Mary'];

    Mail::send('backend::mail.invite', $vars, function($message) {
        $message->to('admin@domain.tld', 'Admin Person');
        $message->subject('This is a reminder');
    });

    Mail::assertSent('backend::mail.invite', function (Mailable $mailable) use ($vars) {
        return $mailable->viewData['name'] === 'Joe' &&
            $mailable->viewData['user'] === 'Mary' &&
            $mailable->hasTo('admin@domain.tld');
    });
}
```

**Comment by mjauvin** [comment] 2020-02-25 19:59
@alxy Would you be interested in completed this work? From what I can glance, you were very close.

**Comment by bennothommo** [comment] 2020-08-27 02:35
@4nik3t @alxy is this still an issue with the Laravel 6 update in `develop`?

**Comment by aniket-magadum** [comment] 2020-08-27 14:44
@bennothommo I will check and get back on this

**Comment by aniket-magadum** [comment] 2020-08-30 10:12
@bennothommo  the problem is still there.

**Comment by bennothommo** [comment] 2020-08-30 15:44
Thanks for letting us know @4nik3t.

**Comment by mjauvin** [comment] 2020-10-30 13:24
@LukeTowers or @bennothommo Can you reopen this, I'm planning on addressing this in the coming weeks.

**Comment by bennothommo** [comment] 2020-11-02 01:53
@mjauvin this might be fixed by adding Mockery to the October CMS `composer.json`, as we have done for the library recently, and ensuring `Mail::fake()` is using that.

**Comment by mjauvin** [comment] 2020-11-02 04:18
@bennothommo I still want to investigate why it works in Laravel and not in october. I might end up using mockery, depending on what I find.

Thanks.

**Closed** 2020-11-23 07:11 UTC
Labels: Type: Bug
