### ISSUE TITLE
[EROR]"Call to undefined method Less_Tree_Call::toHSL()"

### ISSUE THREAD

**Issue by audio99** [octobercms/october#1122] opened 2015-05-11 11:48 UTC
when im trying to save changes in backend colors customization i got this error message,anybody knows?,im stuck here. @daftspunk 
![capture](https://cloud.githubusercontent.com/assets/9496025/7564171/3bef9994-f80e-11e4-91a0-388579d68c3d.PNG)

**Comment by daftspunk** [comment] 2015-05-13 08:14
What build are you using?

**Comment by audio99** [comment] 2015-05-14 11:25
latest build (257)
i use apache

**Comment by daftspunk** [comment] 2015-05-15 14:26
Duplicate of #1137

**Closed by daftspunk** 2015-05-15 14:26 UTC
Labels: missing detail
