### ISSUE TITLE
Richeditor generates html with absolute file urls

### ISSUE THREAD

**Issue by fresswolf** [octobercms/october#4711] opened 2019-10-22 10:34 UTC
### Summary:
The html of file references generated by the richeditor contains absolute URLs. This breaks the possibility to change a page's domain as the page will contain entries with links to the domain that was active at the time the file has been uploaded.
This can also create issues with mixed content when adding SSL to a page after editing content.

### Reproduce steps:

1. Create a Model and Controller with a richeditor field.
2. Create a new entry of that model.
3. Insert an image through the richeditor widget

### Expected behavior: 
The generated html for an image test.jpg looks like
`<img src="/storage/app/media/uploaded-files/test.jpg" style="width: 300px;" class="fr-fic fr-dib">`

### Actual behavior:
The generated html for an image test.jpg looks like
`<img src="http://example.com/storage/app/media/uploaded-files/test.jpg" style="width: 300px;" class="fr-fic fr-dib">`

If I want to migrate the domain from example.com to foo.com I'll get a image not found error everywhere that field's html is rendered. If I add an SSL certificate to example.com the site will reference to an http resource, creating mixed content warnings and errors in the browser.

**Comment by LukeTowers** [comment] 2019-10-22 15:58
Duplicate of https://github.com/octobercms/october/issues/4082. Please add your thoughts there.

**Closed by LukeTowers** 2019-10-22 15:58 UTC
