### ISSUE TITLE
Add support lang for translate Theme options

### ISSUE THREAD

**Issue by Cryden** [octobercms/october#4717] opened 2019-10-25 07:12 UTC
Themes do not support translation of theme options, unlike plugins. Please add support for theme localization.
`
fields: 
    label: theme_name::lang.your_options
`

**Comment by bennothommo** [comment] 2019-10-25 07:13
Duplicate of https://github.com/octobercms/october/issues/4308.

**Closed by bennothommo** 2019-10-25 07:13 UTC
Labels: duplicate
