### ISSUE TITLE
create:plugin not working correctly on Unix

### ISSUE THREAD

**Issue by trsh** [octobercms/october#1955] opened 2016-04-23 14:53 UTC
php artisan create:plugin Foo.Bar creates structure:

/plugins/foo/bar/foo/bar$ 

what of course does not work (have to fix manually).

System: Ubuntu 16.04

**Comment by marcoskubis** [comment] 2016-05-03 17:31
Same problem here. 
System: Windows 10. 
Did you solve this issue?

**Comment by daftspunk** [comment] 2016-05-03 19:01
Duplicate of #1945

**Comment by samuelmolinski** [comment] 2016-05-15 19:55
I see lots of referencing of this as a duplicate issue. Where is the original issue and has it been resolved?

**Comment by daftspunk** [comment] 2016-05-15 19:56
Sure, it was fixed in https://github.com/octobercms/library/commit/9db58ff6d3345855d4539e44960b1afb2314dcd0

**Comment by trsh** [comment] 2016-05-17 05:15
Thanks

**Closed** 2016-07-02 21:46 UTC
Labels: duplicate, Status: Completed, Type: Bug
