### ISSUE TITLE
Not clear error message at plugin install or update

### ISSUE THREAD

**Issue by haegemon** [octobercms/october#1802] opened 2016-02-24 15:15 UTC
Hi. I tried create plugins with dependence of another plugin and get frustrate error when i did spelling error at plugin name:

`Plugin "* not found`

I believe that plugin manger should write reason why it can't install plugin. It'll be very usefully for plugin developers. 
For example if plugin can't install by not resolving dependence:
`Plugin * shouldn't be install because of PluginManager can't resolve dependence`

**Comment by haegemon** [comment] 2016-02-24 21:45
It's enough easy realize through different classes of Exception

**Comment by daftspunk** [comment] 2016-02-25 19:41
Is this a duplicate of #1787?

**Closed** 2016-02-25 19:41 UTC
Labels: duplicate
