### ISSUE TITLE
Installer is not installing the config/develop.php file

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4864] opened 2020-01-04 18:32 UTC
Been installing over a dozen more october websites in the last 24 hours and I've noticed they all have the same error.

Been using the `install-master.zip` installer as I prefer the cgi than the command line - so I don't know if the same error carries over to installing via the command line.

The following file is not getting installed everytime and I don't understand why as it's still being listed in the develop branch of this repo.

The file location: https://github.com/octobercms/october/blob/develop/config/develop.php

See screenshot of what I'm seeing each time October is installed:

![image](https://user-images.githubusercontent.com/57409060/71770067-749b1180-2f20-11ea-99bd-1ad6f9fd3ed2.png)

[edit] It is installing version 462 by the way.

**Comment by bennothommo** [comment] 2020-01-06 09:19
Confirmed that the Zip downloaded from the October servers is missing the `develop.php` file. @daftspunk will hopefully be able to take a look at it at some stage. In the mean-time, you may need to manually create the file as required.

**Comment by bennothommo** [comment] 2020-05-04 07:37
Confirmed this is still occurring.

**Comment by bennothommo** [comment] 2020-07-26 06:25
I'm gonna close this, simply because anyone who will actually need to use the file (people who are doing development on October itself) will get the file when they clone the repo. There's probably no need for this file to be available from the Wizard installer.

**Closed by bennothommo** 2020-07-26 06:25 UTC
Labels: Type: Bug, Website / Marketplace / Docs

**Comment by summercms** [comment] 2020-09-05 15:51
The following config files are not being installed:

- `develop.php` - I opened an issue for this here.

- `hashing.php` - first time issue has been raised.

- `logging.php` - first time issue has been raised.

p.s. I opened issue in the `installer` repo - see here: https://github.com/octobercms/install/issues/112
