### ISSUE TITLE
Yaml 'colon in unquoted mapping' error should provide file URL

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#2097] opened 2016-06-06 06:40 UTC
A few users have been getting the below error upon updating. It's often pretty confusing where the error is actually coming from because the linked line on the screen isn't the correct file. Could we get the YAML filepath added to the end of the error message to make things clearer?

![screenshot from 2016-06-05 23-25-25](https://cloud.githubusercontent.com/assets/334808/15813786/1b4b1f2a-2c05-11e6-8b4a-2d69ec9b812f.png)

**Comment by daftspunk** [comment] 2016-06-06 06:58
This was fixed this morning in d6d5a37ab11a9c32fb415b2c07b603d917141910 and is a duplicate of #1950

**Closed by daftspunk** 2016-06-06 06:58 UTC
Labels: duplicate
