### ISSUE TITLE
database query cache remember() not working

### ISSUE THREAD

**Issue by sgreener** [octobercms/october#2639] opened 2017-01-30 16:56 UTC
In one of my pages (in the backend cms) I perform a database query like so..

```
function onStart()
{
    $this['numz'] = Db::table('backend_users')->select('id')->count();
}
```
This works as expected and returns me a value that I can use in the page like so

> There are a total of {{ numz }} ppl.

Now according to [the documents](https://octobercms.com/docs/database/query#caching-queries) we should be able to do ...

```
function onStart()
{
    $this['numz'] = Db::table('backend_users')->select('id')->remember(10)->count();
}
```
However when ever I try this, I get the following error;

> Call to undefined method Illuminate\Database\Query\Builder::remember()

Looking at [this post](https://laracasts.com/discuss/channels/general-discussion/laravel-5-remember-missing-from-query-builder) it looks like its been removed. Some linked to a possible solution in the comments, [another package](https://github.com/dwightwatson/rememberable).

**Comment by SebastiaanKloos** [comment] 2017-01-30 17:02
I thought that this method is nog available in Laravel 5.

**Comment by LukeTowers** [comment] 2017-01-30 17:10
You can use the [Cache service](https://octobercms.com/docs/services/cache#cache-usage) to roll your own version

**Comment by sgreener** [comment] 2017-01-30 17:50
so is this a bug with the documentation or a bug with the application?

**Comment by LukeTowers** [comment] 2017-01-30 17:52
Bug with a documentation I'd say. Feel free to submit a PR or issue to octobercms/docs to resolve it.

**Comment by SebastiaanKloos** [comment] 2017-01-31 21:14
Note this piece of code:

    /**
     * Indicate that the query results should be cached.
     *
     * @param  \DateTime|int  $minutes
     * @param  string  $key
     * @return $this
     */
    public function remember($minutes, $key = null)
    {
        $this->cacheMinutes = $minutes;
        $this->cacheKey = $key;

        return $this;
    }

located in vendor/october/rain/src/Database/QueryBuilder.

**Comment by LukeTowers** [comment] 2017-01-31 21:34
@SebastiaanKloos Thanks for checking. @sgreener The problem is that you're using Laravel's DB facade then; try using October's or just using the `Backend\Models\User` model to initialize a query object utilizing October's QueryBuilder.

**Comment by daftspunk** [comment] 2017-02-04 19:54
To clarify, Laravel killed this feature and October brought it back from the dead.

**Comment by daftspunk** [comment] 2017-02-04 20:12
This is a legit problem, `Db` returns a Laravel-flavored `QueryBuilder`, whereas `Model` returns an October-flavored `QueryBuilder`.

**Comment by daftspunk** [comment] 2017-02-04 20:33
Fixed in https://github.com/octobercms/library/commit/2c09ee2c7b3150190adcbea7cb9984fae9ff95e4

Thanks! This should be available in Build 398+

**Closed by daftspunk** 2017-02-04 20:33 UTC
Labels: Priority: High, Status: Accepted, Type: Bug
