### ISSUE TITLE
Rich editor behaves strangely when inserting media manager link by pressing enter in Safari

### ISSUE THREAD

**Issue by fresswolf** [octobercms/october#1733] opened 2016-01-28 16:55 UTC
Happens when using Safari:

1. Navigate to a richeditor field
2. Type some text
3. Click "Insert link from media manager"
4. Select a file and press the Enter/Return key

After some time with the infamous Mac spinning wheel, the link is inserted at the very top of the editor

Tested in Safari OS X 9.0.2 and October Build 314

**Comment by alekseybobkov** [comment] 2016-03-03 05:13
I can't find the root cause of the problem. Pressing Enter and double click on an item in the Media Manager causes endless recursion in the rich editor third-party code. For now I disabled the Enter key and double click support in Safari. Hopefully this will be eventually fixed in newer versions of the rich editor.

**Comment by daftspunk** [comment] 2016-05-24 19:28
This should no longer be necessary with the new third party code used in rich editor. Please re test using the new changes from #2005 and If the issue still exists, please log a new issue for it.

**Closed by daftspunk** 2016-05-24 19:28 UTC
Labels: Priority: Low, Status: Completed
