### ISSUE TITLE
Extend form fields bug

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#2131] opened 2016-06-17 13:02 UTC
I extended my plugin (Content Plus) to repeater and mediafinder fields (http://octobercms.com/docs/backend/forms#extend-form-fields) via other plugin. When I click on the original repeater field, the extended fields appear the bottom of the repeater field too.

![bug](https://cloud.githubusercontent.com/assets/2959112/16151263/4bbd4ce2-349c-11e6-9d4d-921d971b3b29.jpg)

**Comment by daftspunk** [comment] 2016-07-01 09:20
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by mitjarobic** [comment] 2016-08-09 12:22
The problem i have is that any field you add using addTabFields method shows up in repeater widget. Might be the same problem.

**Comment by daftspunk** [comment] 2016-08-10 09:11
Duplicate of #2257

**Closed by daftspunk** 2016-08-10 09:11 UTC
Labels: Status: Revision Needed
