### ISSUE TITLE
Taglist don't display a nested relation correctly

### ISSUE THREAD

**Issue by ghost** [octobercms/october#3055] opened 2017-08-23 08:24 UTC
##### Expected behavior
The taglist form widget element should indent children when it deals with a NestedTree relation. The default dropdown already do that correctly.

##### Actual behavior
Actually, the taglist element render all element of the relation in the same level, without indenting children.

##### Reproduce steps
- Create a relation to a model that use NestedTree, use taglist as form widget to render the 'parent' relation.

##### October build
419

**Comment by LukeTowers** [comment] 2017-08-25 03:10
Could you provide screenshots of ideal behaviour vs current behaviour?

**Comment by Alex360hd** [comment] 2017-08-25 06:11
Sure.

(Here is my hierarchy)[https://ibb.co/mcd6rk]

(Here is the normal relation field in a many to many relation)[https://ibb.co/m7jeBk]
You can see that the hierarchy is visible and children correctly indented. It's also the case in a simple dropdown list when it handle a one to many relation.

(Here is the relation as a taglist)[https://ibb.co/nJivj5]
You can see that all elements are on the same level, so you can't distinguish your hierarchy, which is a problem.

(Photoshoped : The taglist should be like that when displaying a relation with nested tree)[https://ibb.co/gxA2Wk]

Best regards,

Alex

**Comment by LukeTowers** [comment] 2017-08-29 16:37
Thanks. 

The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by SebastiaanKloos** [comment] 2017-08-30 12:33
@LukeTowers I guess this is not a bug. Maybe the best tag would be Enhancement

**Comment by Alex360hd** [comment] 2017-09-01 08:12
@LukeTowers I would be happy to help the october CMS to growth as we I will use it more and more for my next projects.

I can't convince my boss to make a financial contribution without getting something in return (it sucks, I know) but we are definitely interested by some "premium" features like Pond, so we will subscribe when it will be released.

Another idea, that we would pay for it : the possibility to have private plugins / themes / projects on your website. Our actual nightmare is that we developped a lot of module that we use internally, combined with a starter theme. It can't be publicly released as it hardly depend on our internal development process.

It's a real pain actually to be obliged to manually copy plugins / themes and to trigger october:up to initialize them.

If we could release them on october website as private project and themes in order to associate them to a project to be able to install all plugins / themes we need with one click on new october install, we would definitely pay for it !

So, what I'm trying to explain is that you could probably make some money by releasing some premium features like that in order to have some fund to spend more time on improving that CMS that is alreay excellent !

**Comment by munxar** [comment] 2017-09-01 08:30
@Alex360hd If you like your projects private, check all your stuff into git. have some ci to run the needed migration commands like october:up or cache:clear and your done.
I do this on several projects where the code is closed source.

**Comment by Alex360hd** [comment] 2017-09-01 08:35
Hi,

I'm new to git and I don't know yet how to do what you describe.

Anyway, I would like something as easy as the project system. You install october CMS, you fill your project ID, and it install all themes and plugins you need. I'm not sure, even with an intensive knowledge of github if you can reach this level of integration.

**Comment by munxar** [comment] 2017-09-01 08:49
@Alex360hd If you don't know git, then you could setup a local environment (laravel valet, xamp, ...) and install everything there (themes, plugins, and custom plugins). then just move the folder to your server and execute a post deploy script (e.g october:up, cache:clear). done.

**Closed** 2019-10-19 00:06 UTC
Labels: Status: Archived, Status: Review Needed, Type: Unconfirmed Bug
