### ISSUE TITLE
The installer fails when the MySQL user password contains a dollar sign and an apostrophe

### ISSUE THREAD

**Issue by iSWORD** [octobercms/october#3054] opened 2017-08-22 23:47 UTC
##### Expected behavior
The installer should have worked fine.

##### Actual behavior
The installer reports an error "Undefined variable: smth" when "Building configuration files"

##### Reproduce steps
1. Create MySQL user & db
2. Set the MySQL user password to something that contains a dollar sign (say pass$smth'word)
3. Run the installer

##### October build
WHERE DO I FIND THE BUILD NUMBER?
I'm going to make it equally difficult for you to figure it out. I downloaded & ran the installer about an hour ago from https://octobercms.com/download

##### P.S.
Finding such a naive bug in a CMS that's labeled as *Stable* will definitely make me avoid using it for any production apps. Your definition of a stable release is disturbing.

**Comment by iSWORD** [comment] 2017-08-23 02:10
Don't get me wrong. October might be a great piece of software but I can't trust it with my clients' data now that I know what counts as stable to the devs behind it.

P.S. if you haven't figured out what went wrong yet;
The password is probably stored somewhere in a PHP script like this
define ("DB_PASS", "pass$smth'word");
Quoted using double quotes, without being escaped or encoded.

```bash
$ php -a
Interactive mode enabled

php > define ("DB_PASS", "pass$smth'word");
PHP Notice:  Undefined variable: smth in php shell code on line 1
php > echo DB_PASS;
pass'word
php > 
```

**Comment by rajakhoury** [comment] 2017-08-23 04:15
Did you try to install it from the CLI ? Keep in mind the installer is just a small script to help you get started and its not the cms. It installs by default build 419 ( laravel 5.1) if you have edgeupdates on will install L5.5.

**Comment by Samorai** [comment] 2017-08-23 05:51
@iSWORD This is not oc issue. 
You're using double quotes http://php.net/manual/en/language.types.string.php#language.types.string.syntax.double .
If you want to have dollar sign into your db password, you should to use \ (bsckslash) before $. 
Like this: 
`define ("DB_PASS", "pass\$smth'word");`

**Comment by iSWORD** [comment] 2017-08-23 11:25
@Samorai That piece of code was to demonstrate the bug in October.

**Comment by Samorai** [comment] 2017-08-23 11:33
There are not october bug.
There are correct php interpretation.
You're using $ (dollar sign) inside double quotes, php has search the variable.

```
➜  ~ php -a
Interactive shell

php > $foo = "bar";
php > define("FOO_1", "$foo");
php > echo FOO_1;
bar
php > define("FOO_2", '$foo');
php > echo FOO_2;
$foo
php >
```

**Comment by iSWORD** [comment] 2017-08-23 12:15
Please read my original bug report. I entered my db password in the **installer**, I did **not** modify any PHP scripts myself. The installer decided that my input should be inserted into PHP scripts without being sanitized or escaped.

**Comment by jan-vince** [comment] 2017-08-23 12:35
Hi @iSWORD , 

I can confirm that it is impossible to install OctoberCMS using a MySQL password **containing apostrophe**. The input is not correctly escaped.

*I have tried web install and the same from console.*

This should be working as many people can be discouraged to try OctoberCMS having problems even installing it.

Until fixed you should use a password without apostrophe or manually enter escaped apostrophe in ````/config/database.php```` file.

**Comment by jimcottrell** [comment] 2017-08-24 21:48
@iSWORD The October project has its issues like any complex project does, and the apparent lack of installer config sanitization is a silly oversight if true, but do you honestly think no one but you is familiar with escaping string content? Your general air of superiority and that you felt your second comment was necessary are giving me a chuckle over here.

"P.S. if you haven't figured out what went wrong yet" followed by a review of something basic is going to be my new go-to move when I file bug reports. If I'm not as condescending as possible, how will people know how much smarter I am than they are?

**Comment by LukeTowers** [comment] 2017-08-25 02:47
This is a duplicate of #2361. 

@iSWORD You're making it equally difficult for me to care about your problems at all with your condescending remarks. Please remember that this project is developed and maintained with a significant amount of volunteer development time on behalf of the project creator, maintainers, and community members. We don't need disparaging comments that add nothing to the discussion.

**Comment by daftspunk** [comment] 2019-12-10 08:49
The issue in #2361 appears to have been fixed. This is a different issue that may require further attention.

**Comment by iSWORD** [comment] 2019-12-13 23:20
Since this was reopened. Please accept my apologies for the harsh language in the original report. I should have been more patient and understanding.

Thank you to all maintainers of October ❤️

**Comment by bennothommo** [comment] 2020-04-01 00:58
Fixed by https://github.com/octobercms/october/pull/4986.

**Closed** 2020-04-01 00:58 UTC
Labels: Status: Completed, Type: Bug
