### ISSUE TITLE
Media library files selection: Shift and Ctrl

### ISSUE THREAD

**Issue by side-by-side** [octobercms/october#2130] opened 2016-06-17 11:51 UTC
Hello.
I have searched for the same issues or pull request, as it quite obvious, but found nothing. If i missed some, sorry.

In the Media Library we can't select several files using Ctrl or Shift keys, that is the basic functionality of any file manager. Am i wrong?

**Comment by gabsource** [comment] 2016-06-17 12:27
I can use drag to select multiple files.
Shift allows multiple selection too : 
- Shift+Click add a single file to the selection list
- Shift+Arrow Down/Up add the next file to the selection list

**Comment by side-by-side** [comment] 2016-06-17 15:25
Yes, thank you for the answer.
But it is still not the expected behaviour. Each of us know how to select range of files using Shift and how to select different files using Ctrl in Windows, in any system, in most of good web-based filemanagers too.

File manager in the October CMS realy good, but this is definetly an issue, I think.

**Comment by LukeTowers** [comment] 2017-05-12 21:02
Duplicate of https://github.com/octobercms/october/issues/1658

**Closed by LukeTowers** 2017-05-12 21:02 UTC
Labels: Priority: Low, Type: Conceptual Enhancement

**Comment by LukeTowers** [comment] 2018-04-11 20:38
Support added in https://github.com/octobercms/october/commit/0c6735f624c82870b918da02c9a103eadf94d9a5
