### ISSUE TITLE
Twig parse gives unknown partial error in laravel mailable

### ISSUE THREAD

**Issue by jacobdekeizer** [octobercms/october#4955] opened 2020-02-25 10:26 UTC
- OctoberCMS Build: 464
- PHP Version: 7.4
- Database Engine: MySql

### Description:

Twig::parse() function gives an error in a mailable object.

```
Twig\Error\SyntaxError: Unknown "partial" tag in "__string_template__870071e787b36ec5846a2e883824933855de74ec2619cb3bbc6176357239bc9e" at line 16. in /Users/jacob/Sites/sampe-member/vendor/twig/twig/src/Parser.php:175
```

### Steps To Reproduce:

1. Create a mailable

```php
use Illuminate\Mail\Mailable;

final class Invoice extends Mailable
{
    public function build(): self
    {
        $this->view('vendor.plugin::mail.invoice');

        $content = October\Rain\Support\Facades\Twig::parse('test {{ example }}', [
               'example' => 'test'
        ]); // produces error

        $this->attachData($content, 'test.txt');

        $this->to('example@example.com', 'name');

        $this->subject('Invoice');

        return $this;
    }
}
```
2. Send mail

```php
/** @var Illuminate\Mail\Mailer */
$mailer = resolve(Illuminate\Mail\Mailer);
$mailer->send(new Invoice());
```

### Temporary solution
Instead of Twig::parse() use this:

```php
$twig = new Twig\Environment(new Twig\Loader\ArrayLoader([
    'content' => 'test {{ example }}',
]));

$parsedContent = $twig->render('content', [
    'example' => 'test'
]);
```

Edit: Probably the same issue as #4874

**Comment by LukeTowers** [comment] 2020-02-28 17:08
Duplicate of #4874

**Closed by LukeTowers** 2020-02-28 17:08 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug

**Comment by yvgorshkov** [comment] 2022-10-25 17:51
Why I can`t see issue #4874?

**Comment by daftspunk** [comment] 2022-10-26 01:22
Hi @yvgorshkov 

Please contact us if you need support with October CMS: https://octobercms.com/contact
