### ISSUE TITLE
[Bug] File Upload Widget

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1080] opened 2015-04-24 09:02 UTC
Hi,

After updating to build 248 and using the new media manager (which is fantastic by the way - well done guys!), the existing File Upload widget doesn't honour any images uploaded by it

i.e

I have a gallery plugin that utilises the file upload widget, if I now upload images in the gallery, the images are uploaded to the ```storage/app/media``` folder as expected, but no previews are being shown in the gallery & the images then disappear from the gallery.

Have also noticed that no reference to the uploaded images are recorded in the ```system_files``` database table anymore, attaching them to the model.

I understand that the media manager is a great new addition, but may plugins still utilise the existing File Upload widget - any help would be greatly appreciated as always.

Thanks

**Comment by daftspunk** [comment] 2015-04-24 09:03
Fixed in Build 249
Duplicate of https://github.com/rainlab/blog-plugin/issues/79

**Comment by DanielHitchen** [comment] 2015-04-24 09:03
Wow that was quick! Thanks @daftspunk - great stuff :)

**Comment by daftspunk** [comment] 2015-04-24 09:03
=)

**Closed by daftspunk** 2015-04-24 09:03 UTC

**Comment by DanielHitchen** [comment] 2015-04-24 09:37
@daftspunk quick question, I've already built a plugin that accesses the files uploaded via the File Upload widget into the ```system_files``` DB table, and displays them in a kind of media manager - are there any plans to integrate these files into the media manager also so we can manage those files too?

I only ask because we now have 2 folders, one for uploads & one for media, and they're pretty much the same thing but in 2 locations.

I only ask because if there aren't I will keep my existing plugin for managing File Uploads via the File Upload widget, and use the Media Manager for everything else.

**Comment by jonpxpx** [comment] 2015-04-24 14:07
I'd be keen to know this too, as pointing the media manager to the uploads directory means you are stuck  with the generated filenames that the old uploader created and besides that I have around 5000 + images so finding things at the moment with the 3 or 4 level deep folders is a nightmare. Is there plans for a media manager model that does something similar to the system_files as @DanielHitchen mentioned above?
