### ISSUE TITLE
Multisite trait loosing sync after record deletion

### ISSUE THREAD

**Issue by fgschafer** [octobercms/october#5669] opened 2022-11-17 16:28 UTC
Hi.  I'm trying to figure it out how to handle different records per site (for a same model).  And I think the multisite trait is precisely for this.  When you create a record for one site, and after saving you change the site the usual prompt to create a new record for selected site pops up.  So I create a record for that site.  The issue is when you delete one of them and for some reason you need it back.  I mean, you can delete it but then you are no able to "recreate it" if you need it again.  When you go to the record that remains and change to the other site, instead of asking again to create the record, there's an error: "Form record with an ID of ... could not be found."
I think it's a pretty common situation to delete a record and then needing it back.

Having said this, I still can't avoid getiting confused about the concept "overlapping" of multisite trait and translatable... I think the limits are still blurred on what is a site and what a locale.  In the previous explanation of the issue, there might even cases when both havo to coexist (translatable and multisite).

**Comment by daftspunk** [comment] 2022-11-21 00:38
> When you go to the record that remains and change to the other site, instead of asking again to create the record, there's an error: "Form record with an ID of ... could not be found."

I could not reproduce this. Are you using the `SoftDelete` trait?

> Having said this, I still can't avoid getting confused about the concept "overlapping" of multisite trait and translatable

Yes, there are examples where these two might co-exist. For example, a site about Cats and Dogs in 2 different languages. You may use Multisite to separate the Cats and Dogs, and Translate to divide the content across the two languages.

**Comment by fgschafer** [comment] 2022-11-22 16:03
Yes, I was using the SoftDelete trait

**Comment by daftspunk** [comment] 2022-11-25 00:11
Thanks for the report, @fgschafer. This will be fixed in v3.1.26: When toggling sites and trashed records are encountered, the confirmation prompt is displayed, and the model is restored.

Related https://github.com/octobercms/library/commit/8379e0c646af686e03d37737c09baa95773b856a

**Closed as completed by daftspunk** 2022-11-25 00:11 UTC
