### ISSUE TITLE
Repeater field did not save data

### ISSUE THREAD

**Issue by huynhnamegal** [octobercms/october#4229] opened 2019-04-01 09:19 UTC
- OctoberCMS Build: 447
- PHP Version: 7.0.26
- Database Engine: MySQL

### Description:
In morning, I try to run command "composer update" and composer update modules of OctoberCMS, it change some files. After updating, all of my repeater fields did not save any data.
I rollbacked to before updating and my repeater fileds still working. But now, I tried "composer update" again, no changes in modules folders. Is Build 450 changes?

**Comment by cheb60** [comment] 2019-04-01 09:23
I can confirm this bug. It only saves an JSON string containing empty arrays.

**Comment by LukeTowers** [comment] 2019-04-01 09:27
Duplicate of #4223 and #4226. Fixed in the latest library dev branch, fix will be available in build 451.

**Comment by tfprado** [comment] 2019-04-02 15:21
@LukeTowers When will build 451 be available?

**Comment by w20k** [comment] 2019-04-02 15:36
Should be fixed soon ;)

**Comment by LukeTowers** [comment] 2019-04-02 16:28
Already out @tfprado https://packagist.org/packages/october/backend#v1.0.451, https://octobercms.com/changelog.

**Closed** 2019-07-22 15:05 UTC
Labels: Status: Completed, Type: Bug
