### ISSUE TITLE
MediaFinder - List 'Render' Glitch

### ISSUE THREAD

**Issue by AydievMansur** [octobercms/october#4630] opened 2019-09-20 09:53 UTC
- OctoberCMS Build: from 439 to 458 
- PHP Version: 7.2 x64
- Database Engine: Mysql 5.7 x64
- Plugins Installed: Noplugins

### Description:
When you open Mediafinder(Page,ModalWindow) in any browser,any project,we even try different PC and different october version.
Page of MefiaFinder list being glitch and u can`t able to click to any elements.
[Click here to watch GIF](https://drive.google.com/file/d/1U7qWdEHnipRxFu3oS7zCZoWr19u3u38z/view)

### Steps how to fix:
Go to backend personalization
and paste code below
`div[data-control="media-manager"] [data-control="item-list"] {
    display: flex;
    height: 100%;
}`

**Comment by bennothommo** [comment] 2019-09-21 13:59
This is likely a duplicate of https://github.com/octobercms/october/issues/4621 or https://github.com/octobercms/october/issues/4601.

**Closed by bennothommo** 2019-09-21 13:59 UTC
Labels: duplicate

**Comment by ayumihamasaki2019** [comment] 2019-09-22 20:45
Ok PR submitted.

There were two issues causing the error, these are as follows:

1. The issue was the `position` using `absolute` and not `sticky`, which caused a forever scrolling action. `Position: sticky` has fixed this issue.

2. The issue here was because the scrollbar javascript in the media manager needs to have the right sidebar displayed and the css was using `display: none`, switching it over to `opacity: 0` allows the javascript to scroll the container. If you set the `display` to `none` you will see the `data-visible` attribute keep trying to set it to `true` and the screen starts flickering! The right sidebar in the media manager is the place where the media file previews are displayed.

Please can some people test out my PR and shout at me - when needed, pr is here: https://github.com/octobercms/october/pull/4632

**Comment by Samuell1** [comment] 2019-09-23 07:40
Sticky isnt support that well. https://caniuse.com/#feat=css-sticky @ayumihamasaki2019

**Comment by ayumihamasaki2019** [comment] 2019-09-23 10:18
@Samuell1 Thanks for your comment, going to add a polyfill to sort that out. 👍

**Comment by Samuell1** [comment] 2019-09-23 10:55
I think you can polyfill it pretty simply with media query for IE11 @ayumihamasaki2019
