### ISSUE TITLE
Update to 3.7.0 will not finish

### ISSUE THREAD

**Issue by Hlusta** [octobercms/october#5823] opened 2024-10-10 13:11 UTC
I tried to update (3x = 2x local | 1x remote) to version 3.7.0 but it does not finish at all. I used the webbrowser:
https://october3.test/backend/system/updates

Result after refreshing the endless progressbar:

`
Warning: require(/Users/username/Sites/october3/vendor/composer/../symfony/polyfill-php72/bootstrap.php): Failed to open stream: No such file or directory in /Users/username/Sites/october3/vendor/composer/autoload_real.php on line 41

Fatal error: Uncaught Error: Failed opening required '/Users/username/Sites/october3/vendor/composer/../symfony/polyfill-php72/bootstrap.php' (include_path='.:') in /Users/username/Sites/october3/vendor/composer/autoload_real.php:41 Stack trace: #0 /Users/username/Sites/october3/vendor/composer/autoload_real.php(45): {closure}('25072dd6e247008...', '/Users/username/S...') #1 /Users/username/Sites/october3/vendor/autoload.php(25): ComposerAutoloaderInit2016da643dd7d2d293b1cff3e9b42c61::getLoader() #2 /Users/username/Sites/october3/bootstrap/autoload.php(36): require('/Users/username/S...') #3 /Users/username/Sites/october3/index.php(18): require('/Users/username/S...') #4 /Applications/Herd.app/Contents/Resources/valet/server.php(167): require('/Users/username/S...') #5 {main} thrown in /Users/username/Sites/october3/vendor/composer/autoload_real.php on line 41
`

**Comment by daftspunk** [comment] 2024-10-10 22:56
Hi @Hlusta 

This is a [known issue](https://talk.octobercms.com/t/problem-installing-latest-october-cms/2913/13) caused by a symfony package update. It can be resolved by running `composer update` in the command line. Otherwise, the following patch can be used to prevent the error. Unfortunately, it is a chicken and egg problem since we can't deliver this patch without performing an update.

The following patch can be manually applied to ensure the patched files are available:
https://github.com/octobercms/library/commit/0ba30958a7ddb8b53b23f5841d9a10e03d97c226

I have also included a zip file that you can upload to the website that will patch the files as well.

- [v3.6.30 manual patch zip file](https://octobercms.com/storage/app/media/release-notes/october-rain-3-6-30-patch.zip)

Best regards

**Closed as completed by daftspunk** 2024-10-10 22:56 UTC

**Comment by Hlusta** [comment] 2024-10-11 05:47
Thank you @daftspunk!
