### ISSUE TITLE
Nested list relations only working 1 deep

### ISSUE THREAD

**Issue by ChadStrat** [octobercms/october#2486] opened 2016-11-14 01:01 UTC
##### Expected behavior
Model A has many model B.  Model B has many model C.

If you have list relation that has a list relation(child) that has a third list relation (grandchild), in the create backend form you should then see model A with an empty list of model B, wherein you can "add one" that contains an empty list for model C wherein you may add grandchildren.

##### Actual behavior
relating a grandchild list breaks create/update modals for the child list.

##### Reproduce steps
download https://github.com/ChadStrat/nestedrelation-plugin 

1.  Click on the 'nested relation' nav item and click on 'new thing'
2. You should see model B "Stuff" List related to "Thing"
3. Click on "Create Stuff" and you will see an error as "More Stuff" model is not related correctly.

There may be some yaml-foo I am neglecting in some way?  But it is not immediately clear to me what that would be.  The plugin linked above is created specifically to make this as plain as possible in both structure and naming.  Please feel free to PR to the repo if I have missed something rather obvious.

##### October build
381

**Comment by ChadStrat** [comment] 2016-11-14 01:03
this very well may be resolved with documentation?  I will feel really stupid if so. :-P

**Comment by daftspunk** [comment] 2016-11-14 20:38
That was almost too easy, fixed in PR:
https://github.com/ChadStrat/nestedrelation-plugin/pull/1

I'm sure there is something else.... please revise the reproduce steps to uncover the true problem. (Unless that was really it?)

**Comment by ChadStrat** [comment] 2016-11-30 22:38
So yes..that allows the first dialog to come up.  But then the nested list inside of that for the next step is a duplicate 'stuff' object dialog instead of 'more stuff'.

**Comment by daftspunk** [comment] 2016-12-05 21:07
Sorry dude I'm not following. Here's what I need you to do:

- [Accept and merge this PR](https://github.com/ChadStrat/nestedrelation-plugin/pull/1) so the first bug is resolved
- Rewrite the replication instructions to produce the underlying/actual issue.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by daftspunk** [comment] 2017-01-13 22:26
Duplicate of #1959 

Just a heads up, nested relations probably won't be supported. Behaviors are designed to be helpful in speeding up development, not as the answer to every possible implementation.

We are working on a series of screencast tutorials that describe this in more detail. See the following repo for more details: https://github.com/daftspunk/oc-formist-plugin

**Closed by daftspunk** 2017-01-13 22:26 UTC
Labels: Priority: High, Status: Revision Needed, Type: Bug
