### ISSUE TITLE
Add SVG support in Media Manager

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#3986] opened 2018-12-16 13:44 UTC
Idea for Media Manager improvement - add SVG support (as image beside current JPEG, PNG...)

**Comment by LukeTowers** [comment] 2018-12-16 15:34
Duplicate of #3106. Resubmit that PR with my recommendations implemented if you would like to see this.

**Closed by LukeTowers** 2018-12-16 15:34 UTC

**Comment by Rike-cz** [comment] 2018-12-17 10:07
Sorry, my bad.

**Comment by Rike-cz** [comment] 2018-12-17 12:11
@datune Are you able to resubmit your PR?

**Comment by w20k** [comment] 2018-12-17 15:00
@Rike-cz, you could make a revision of his PR and resubmit it with regards to the author.

**Comment by Rike-cz** [comment] 2018-12-22 16:33
Little question when I am trying to solve SVG problem: Why every thumbnail in Media Manager is PNG, if original image is JPEG? It's purpose or bug?
