### ISSUE TITLE
The Tailor pagefinder field does not adopt the link when we change the language on a multilingual site

### ISSUE THREAD

**Issue by haralake** [octobercms/october#5703] opened 2023-03-09 10:09 UTC
The Tailor pagefinder field does not adopt the link when we change the language on a multilingual site.
In the admin in the primary language you see this:
![Screenshot_2](https://user-images.githubusercontent.com/18325407/223989097-100e6c11-ff3c-4952-807f-3c317347b323.png)

and in the secondary language this:
![Screenshot_3](https://user-images.githubusercontent.com/18325407/223989111-64be20ea-b175-4cac-9d86-82df602cddd6.png)

The result is that on multilingual sites you cannot work with the pagefinder field.

Another thing I noticed is that in every record you create with the pagefinder field in the admin interface and with "multisite:sync" enabled in the blueprint, you see all the entries (which are created depending on the languages you use) in the "Parent" field.
![Screenshot_4](https://user-images.githubusercontent.com/18325407/223989251-b4df1cb2-bc9a-46c2-9539-a12541461ece.png)

**Comment by daftspunk** [comment] 2023-03-09 23:33
Hi @haralake 

We could not reproduce the first issue; the link resolves for both sites, including across different themes. In your screenshot, the link has been set successfully, however, the URL is not displayed since it cannot resolve to any usable link.

Check to make sure that page selected exists in the theme for the selected site. It is possible for a link to be propagated from Site A using Theme A and when Site B uses Theme B the link can be unresolvable if the page name does not exist.

**Comment by daftspunk** [comment] 2023-03-10 02:44
The second issue will be fixed in v3.2.22 when it is released.

Thanks!

**Comment by haralake** [comment] 2023-03-10 11:25
> Hi @haralake
> 
> We could not reproduce the first issue; the link resolves for both sites, including across different themes. In your screenshot, the link has been set successfully, however, the URL is not displayed since it cannot resolve to any usable link.

Hi @daftspunk !
I investigated it more and found that it happens when you have "multisite: sync" enabled in the blueprint that is responsible for creating records (pages). The problem has to do with the records that have been automatically created by the multisite: sync option. If you manually create the records that will be selected by the pagefinder, the problem does not occur.

**Comment by daftspunk** [comment] 2023-03-15 22:06
With this information, we still cannot reproduce this using a clean installation of October CMS:

0. Ensure a secondary site exists
1. Update the sitemap.yaml blueprint to use `multisite: sync`
2. Navigate to Settings → Sitemap
3. Create a record, select the homepage
4. Navigate to the second site
5. The Reference (pagefinder) field is populated normally

**Comment by haralake** [comment] 2023-03-21 12:52
> With this information, we still cannot reproduce this using a clean installation of October CMS:
> 
> 0. Ensure a secondary site exists
> 1. Update the sitemap.yaml blueprint to use `multisite: sync`
> 2. Navigate to Settings → Sitemap
> 3. Create a record, select the homepage
> 4. Navigate to the second site
> 5. The Reference (pagefinder) field is populated normally

Using a clean installation of latest October CMS v3.2.23:
When i use multisite: sync
![pagefinder](https://user-images.githubusercontent.com/18325407/226605671-d66799bc-2dc5-4139-9ace-c05d127843e2.gif)
I'm still having this issue.

When i use multisite: true
![pagefinder2](https://user-images.githubusercontent.com/18325407/226611278-3288e9b5-e28f-4eb6-b96e-ec00f8c0e32a.gif)
Is working ok

**Comment by haralake** [comment] 2023-03-21 13:06
> With this information, we still cannot reproduce this using a clean installation of October CMS:
> 
> 0. Ensure a secondary site exists
> 1. Update the sitemap.yaml blueprint to use `multisite: sync`
> 2. Navigate to Settings → Sitemap
> 3. Create a record, select the homepage
> 4. Navigate to the second site
> 5. The Reference (pagefinder) field is populated normally

Using a clean installation of latest October CMS v.3.2.23:
With "multisite: sync"
![sync](https://user-images.githubusercontent.com/18325407/226614829-f8dc24f6-0d03-4f1c-8189-efe7835acb11.gif)
i'm getting the same issue

With "multisite: true" and manually creating records:
![true](https://user-images.githubusercontent.com/18325407/226614865-66d2f722-bba6-4229-982e-ff291757cf54.gif)

**Comment by daftspunk** [comment] 2023-03-21 22:31
Can you share your site configuration? It might be related to this.

**Comment by haralake** [comment] 2023-03-23 13:23
> Can you share your site configuration? It might be related to this.

I'm using LEMP stack on Ubuntu server 20.04.3 with PHP 8.1.14 and Maria db v1:10.5.12 on windows Hyper-V virtual machine.

This is my composer.json:

```
{
    "name": "october/october",
    "description": "Built using October CMS: The Laravel-Based CMS Engineered For Simplicity",
    "type": "project",
    "homepage": "https://octobercms.com",
    "license": "proprietary",
    "require": {
        "php": "^8.0.2",
        "october/rain": "^3.2",
		"october/all": "^3.0",
        "laravel/framework": "^9.0",
        "rainlab/translate-plugin": "^2"
    },
    "require-dev": {
        "phpunit/phpunit": "^8.5|^9.0"
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate --ansi"
        ],
        "post-autoload-dump": [
            "System\\Console\\ComposerScript::postAutoloadDump"
        ],
        "post-update-cmd": [
            "System\\Console\\ComposerScript::postUpdateCmd"
        ],
        "pre-package-uninstall": [
            "System\\Console\\ComposerScript::prePackageUninstall"
        ],
        "test": [
            "phpunit --stop-on-failure"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "allow-plugins": {
            "composer/installers": true
        }
    },
    "autoload": {
        "psr-4": {
            "System\\Console\\": "modules/system/console"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": {
        "octobercms": {
            "type": "composer",
            "url": "https://gateway.octobercms.com"
        }
    }
}
```

**Comment by daftspunk** [comment] 2023-03-23 21:55
Sorry. Please navigate to **Settings → Manage Sites** and show the site configuration are you using.

**Comment by haralake** [comment] 2023-03-24 15:29
> Sorry. Please navigate to **Settings → Manage Sites** and show the site configuration are you using.

![Screenshot_1](https://user-images.githubusercontent.com/18325407/227569665-f07e4260-580e-4106-8f8a-e81b47f70763.png)


Ok, i forgot to mention important information.

- Put "multisite:sync" on wiki/article.yaml
- Put "multisite:sync" on site/sitemap.yaml
- Create a new article with Content -> Article
- Go to Settings -> Sitemap
- Create new sitemap entry and choose the article name you created before with pagefinder, then save.
- You will see that the pagefinder link is ok on the first language but if you change the language there is no link on pagefinder .

The issue happens only if you use "multisite:sync" on both wiki/article.yaml and site/sitemap.yaml

**Comment by daftspunk** [comment] 2023-04-06 07:11
Hello

I still can't reproduce this using identical settings on the demo site and a fresh installation. It is possible if the "Edit theme" (set via Editor) is set to a theme that doesn't have the page, it will show empty like this, but it is harmless. Click the "Replace" button and you might see that the page does not appear in the dropdown.

**Comment by uitlaber** [comment] 2024-03-23 00:51
Hello, I realized that when selecting Reference in the list, the elements have the wrong id (In the dropdown itself). Because of this, the correct URL is not displayed on the multisite. (/default)

**Comment by daftspunk** [comment] 2024-10-15 01:35
I've taken looked at this today, the ID should contain the `site_root_id` which will often be different to the translated model's primary key. So it may look like the wrong ID, but the lookup should use `site_root_id` + `site_id` to locate the correct record. I hope this makes sense.

**Closed as completed by daftspunk** 2024-10-15 01:35 UTC
