### ISSUE TITLE
[solved] Installation broken?

### ISSUE THREAD

**Issue by ttrepper** [octobercms/october#2928] opened 2017-06-16 07:35 UTC
Hi all, 

I have tried to install October via the describes various path and I am running into troubles in all of them. 

1) Downloaded master-zip: Installation went fine, but I was unable to open Ajax (404), Plugin FW (404) and the backend (404) (installation done without a theme) (chown -R for www-data & chmod -R 777 done)

2) Installed via composer. Works fine, but on first access to index.php I get the following stacktrace:

`[Fri Jun 16 09:22:38.936195 2017] [:error] [pid 3939] [client 192.168.0.232:59999] PHP Fatal error:  Uncaught exception 'Twig_Error_Runtime' with message 'The "Cms\\Facades\\Cms" extension is not enabled in "/var/www/domain1/octoberComposer/themes/demo/layouts/default.htm" at line 14.' in /var/www/domain1/octoberComposer/vendor/twig/twig/lib/Twig/Environment.php:884\nStack trace:\n#0 /var/www/domain1/octoberComposer/storage/cms/twig/df/df74462c930e3a51f36459e066b4de58e5d3dbd59f39aeb7019a60d2872faaee.php(52): Twig_Environment->getExtension('CMS')\n#1 /var/www/domain1/octoberComposer/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_4f7945998b3e75cc3568a7e3012aa216751ca3ece486f18852f5867b2b07dfd9->doDisplay(Array, Array)\n#2 /var/www/domain1/octoberComposer/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#3 /var/www/domain1/octoberComposer/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)\n#4 /var/www/domain1/octoberComposer/modules/cms/classes/Controller.p in /var/www/domain1/octoberComposer/vendor/twig/twig/lib/Twig/Environment.php on line 884`

Have I missed something? Thx & cheers,
Thomas

**Comment by ttrepper** [comment] 2017-06-16 13:47
Solved by adding "twig/twig": "1.33.*", to the require section in composer.json and running composer update

**Comment by LukeTowers** [comment] 2017-06-16 21:10
Duplicate of #2908

**Closed by LukeTowers** 2017-06-16 21:10 UTC

**Comment by tashpemhiwa** [comment] 2018-04-22 13:58
In my case I had to ensure that my VirtualHost had `AllowOverride All` in order for this to work.
