### ISSUE TITLE
[Bug] Dropdown not properly displayed with V8 JavaScript Engine on Windows 8+

### ISSUE THREAD

**Issue by cyril-oria** [octobercms/october#1328] opened 2015-07-30 08:55 UTC
**Bug summary:**
There is an error JavaScript when you click on a dropdown in the backend, within Chrome & Firefox on Windows 8 & 10 (but it works perfectly on Windows 7).

**Actual result:**
A JavaScript error is thrown with the following message : _The select2('focus') method was called on an element that is not using Select2
Uncaught TypeError: Cannot read property 'focus' of undefined_
(in october-min.js line 1503 -> it's most likely related to the following file : october/modules/system/assets/ui/js/select.js)
However, the select works even so and displays the list of options, but there is no CSS and the search bar included on the top of the list is not available.

**Expected result:**
The searchbar in the dropdown is shown and the list is stylized.

**Comment by dotgreg** [comment] 2016-03-24 04:00
Same problem here

On a vanilla octobercms installation, here is the debug log on firefox on windows 8

`TypeError: instance is undefined
 storm-min.js:1621:54
The select2('focus') method was called on an element that is not using Select2. storm-min.js:1620:1002
S2</</$.fn.select2() storm-min.js:1620
<anonyme> storm-min.js:2202
.proxy/f() jquery.min.js:2`

**Comment by thenguyenit** [comment] 2016-07-16 11:07
You can fix append code:
For initiating select2 for all input select
`$(document).ready(function() {
$('.custom-select').select2();
});`

**Comment by daftspunk** [comment] 2016-08-13 03:06
Needs replication instructions. How do we get this error to appear by navigating the admin area?

**Comment by axomat** [comment] 2016-09-10 08:12
I have noticed the same issue. It works fine on Firefox 42 latest version on Linux but same error described above is produced on any backend dropdown (select2 dropdown) when using Chromium V52 on Linux. I had not noticed this on earlier versions of chromium, 52 was just installed this week.

**Comment by daftspunk** [comment] 2016-09-14 10:31
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by axomat** [comment] 2016-09-14 11:57
Not sure what more to say really, every single dropdown displayed in the backend does not operate normally and produces the error shown in the first post. You do not have to do anything to reproduce it other than use an affected version of a browser which is why I gave the exact versions I use.

**Comment by axomat** [comment] 2016-09-14 12:04
Further information:
Working correctly on IE 11.0.22 and Windows Chrome 51.0.2704.103

**Comment by daftspunk** [comment] 2016-09-18 04:59
Unable to replicate this. Select dropdowns are working fine over here. Please submit a PR fix or provide instructions that can be successfully replicated. Make sure testing is performed on a clean install of October, as it may be caused by another plugin.

Tested across all latest browsers in Windows 10.

**Comment by LukeTowers** [comment] 2017-10-18 21:45
Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment] 2017-10-18 21:45
In theory perhaps solved by https://github.com/octobercms/october/commit/d788b7e03f351e960df1b993a52e91e9c0f9f99d

**Closed by LukeTowers** 2017-10-18 21:45 UTC
Labels: Type: Unconfirmed Bug
