### ISSUE TITLE
Registering plugin schedules in test environment can cause DB error

### ISSUE THREAD

**Issue by jimcottrell** [octobercms/october#3208] opened 2017-10-27 18:53 UTC
##### Expected behavior
Plugin test cases should be able to be completely isolated from the app environment.

##### Actual behavior
If a plugin accesses the DB in its `registerSchedule` function-- say, via a settings model to determine when or whether to schedule a task--this access happens while bootstrapping the test app's console kernel, which is before the app is configured to use in-memory SQLite by `PluginTestCase`.

In the first test that runs there will be no error, I believe because for the first app bootstrap the plugin manager isn't yet aware of the plugin being tested. But any further tests will trigger the error `PDOException: SQLSTATE[HY000] [2002] No such file or directory` when the settings model attempts to load while registering the schedule.

When I initially noticed this, the errors were actually triggering while testing a plugin other than the one registering a schedule, which was a little hard to figure out at first. So, I know that it's even possible to disrupt another plugin's tests. I assume that was just because in my case the one plugin requires the other that registered the schedule and this wouldn't happen just because the other plugin is installed.

##### Reproduce steps
- Create a plugin with a settings model
- Add a `registerSchedule` function to the plugin where you access a value on the settings model.
- Add a test case extending `PluginTestCase` with a couple of dummy tests (has to be more than one).
- Run PHPUnit on the plugin's tests

##### October build
426

I'm not sure what the best answer is. Perhaps there should be a check for the app environment that doesn't register schedules if testing?

**Comment by LukeTowers** [comment] 2017-10-27 19:09
@jimcottrell is this related to https://github.com/octobercms/october/pull/3156 at all?

**Comment by jimcottrell** [comment] 2017-10-27 20:40
I hadn't seen that issue. In my case, I don't boot or register any plugins, so it's not exactly the same situation, but it seems like it could share the root cause. If I modify `October\Rain\Support\Traits\Singleton` to let me forget a singleton instance and create a test `tearDown` that uses that for `PluginManager`, I don't see my error. It seems like state persisting between app boots in externally-managed singletons could be leading to both issues.

**Comment by LukeTowers** [comment] 2017-10-27 22:07
@jimcottrell what would you recommend as a fix for this issue then?

**Comment by jimcottrell** [comment] 2017-10-27 22:58
If `PluginTestCase` could either completely reset the `PluginManager` instance's state or had a way to force that instance to be forgotten after tests, that would be a fairly simple change that I think would fix my schedule issue and should eliminate the need to unregister all plugins after a test as in #3156. I can make a PR if you'd like. I'd probably go with forgetting the singleton on teardown.

**Comment by LukeTowers** [comment] 2017-10-27 23:08
Sure, a PR would be helpful. Thanks!

*Luke Towers*
email: luke@luketowers.ca
mobile: (306) 537 - 1725 <13065371725>
web: LukeTowers.ca <http://luketowers.ca/>

**Comment by jimcottrell** [comment] 2017-10-28 00:35
I suppose there's an argument that `PluginManager` and `UpdateManager` would be more appropriately handled via the app container, but this is a simple change that I believe takes care of the issue discussed.

**Comment by munxar** [comment] 2017-11-01 05:45
@LukeTowers @jimcottrell 
This is a big issue with plugins that are checked in into git. If you clone a fresh repo and try to run artisan to create your .env or do other operations, it will run the registerSchedule which accesses a model and then fail.
I had to 'fix'/modify several third plugins that we checked into git in the following way:
```php
class MyPlugin extends Plugin {
...
   function registerSchedule($schedule) 
   {
      // don't access your models here
      App::before(function() {
         // save to access settings (?)
         $settings = Settings::instance()
         $schedule->command('my:command')->chron($settings->chron_settings);
      });
   }
...
}
```
The 'App::before' delays the execution lifecycle. I'm not sure if this is the solution, but it worked for my plugins. But i think we should delay this call by default.

**Comment by LukeTowers** [comment] 2017-11-01 06:24
@munxar I'm unclear what your issue is, could you explain in more detail?

**Comment by munxar** [comment] 2017-11-01 08:07
@LukeTowers 
The effect is the same as @jimcottrell described, but the cause is not a running unit test, it's the artisan command itself.
There are two workflows which I try to describe too make it more clear:
### 1. Default OctoberCMS installer, then install plugins (from store)
here we have no problem, because:
a) october is installed before any plugin is installed (therefor e.g. Settings model and table exist)
b) the migrations are always up() never down()

### 2. October is checked into a git repo with all needed plugins (from shop, and custom)
This is due to continuous delivery to a dev.domain automatically or a one click install of a tag to a stage or production environment. Everything is automated. (This includes running tests automatically)

We ignore 1 for now, because the problem (beside running tests, which nobody does here) doesn't occur.
For Scenario 2, if you clone such a repo (new developer joins team, or just a different machine) we do this:
> git clone myrepo
> cd myrepo
> php artisan october:env
// alter .env to match e.g. db settings
> php artisan october:up

BUT:  php artisan october:env invokes all plugins registerSchedule() methods. If at this point in time (no db set up) you try to access e.g. Settings (which is a db model) you'll get an error that the table doesn't exist (which is correct). 

So back to @jimcottrell original issue: the same happens if you run integration tests, because they migrate up a fresh db each time a new test is run. which results in the same error and as far as I can see has the same cause.

**Comment by LukeTowers** [comment] 2017-11-01 15:42
@munxar What would you suggest as a better fix to this issue?

**Comment by jimcottrell** [comment] 2017-11-02 18:45
Just thinking about this more with @munxar's issue, it's actually kind of unnecessary that Laravel wants the schedule defined on every console kernel boot. As far as I can see, it's only used if you run the `schedule:finish` or `schedule:run` commands, which makes sense. I get why they do it this way, but they could pretty easily make a lazy scheduling call only when the schedule is needed. Of course, it's probably more of an issue for something like October's situation than for the usual Laravel app.

**Comment by jimcottrell** [comment] 2017-11-02 18:50
If we're interested in a workaround, we could wait to register plugin schedules until `Illuminate\Console\Events\CommandStarting` fires and we've verified it's not `october:up` running. The delay would presumably also fix the testing issue since it shouldn't ever even fire in that situation. The persistent state between app boots would likely still cause issues like #3156 though, so that still should be considered.

**Comment by LukeTowers** [comment] 2017-11-02 18:51
@jimcottrell do you have any ideas for a better implementation within October?

**Comment by LukeTowers** [comment] 2017-11-02 18:53
@jimcottrell could you explain why it is necessary to define the schedule on every console boot instead of only when it's called directly?

**Comment by jimcottrell** [comment] 2017-11-02 19:00
@LukeTowers That's just it though. Unless I'm missing something, I don't think it really should be necessary, so I can't explain why it should be. Laravel just calls the kernel's `schedule` function on every boot, probably because it's simple and they haven't run into an issue like this to make them decide differently.

**Closed** 2019-05-09 08:27 UTC
Labels: Status: Completed, Type: Maintenance
