### ISSUE TITLE
Date Validation & Attribute casting

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#3008] opened 2017-08-02 02:22 UTC
I posted this [question on SO](https://stackoverflow.com/questions/45449792/laravel-5-1-date-validation-attribute-casting)  (with code sample ) not sure if it is related to October, Laravel or my logic.  I am posting here after looking at the event logs. Shouldn't the validation run before a value is passed to Carbon ? 

E.g add a date field ( not datetime ) to `protected $dates` or `protected $casts as 'hire_date'     => 'date' `  , then add a `date_format:Y-m-d` validation rule, submit an invalid date format `e.g 2017-08-AA` - Throws a Carbon exception instead of a validation exception that the string is not a valid date format.

Now if I remove the field from  `$protected $dates` or `$casts` and submit again the same value then it throws a validation exception as expected. 

As I mentioned on SO i was looking for a way to validate a date input without defining mutators.

Thanks!

![chrome_2017-08-01_21-09-18](https://user-images.githubusercontent.com/4506434/28854690-4237df02-76fe-11e7-983b-2c3dcc78a8b5.png)

##### Expected behavior
Validate Input format before passing to Carbon 

 

##### October build
419

**Comment by LukeTowers** [comment] 2017-10-19 16:12
Closing as it has been over a month since any activity on this occurred.

**Comment by msimkunas** [comment] 2020-05-30 18:32
I'm experiencing this bug as well. October build 465.

**Comment by LukeTowers** [comment] 2020-05-30 21:17
@msimkunas can you switch to the L6 branch and test if the issue is still present there?

**Comment by bennothommo** [comment] 2020-07-30 02:12
@rajakhoury @msimkunas This still happens with the Laravel 6 branch, however, I believe it's intended functionality. The casting of types would need to happen *before* validation so that the expected type of data is validated - for example, if I cast an attribute as a boolean, I would then set up my rules under the pretense that the value being validated will be a boolean, so I would perhaps have a rule that ensure that the value will be `false` and not `0` or a string `"false"` or something similar. The same would apply for dates - it would expect that the attribute is a `DateTime` object before passing it through the validation rules.

**Closed by bennothommo** 2020-07-30 02:12 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
