### ISSUE TITLE
Static page Repeater fields data doesn't saved properly after a field is deleted.

### ISSUE THREAD

**Issue by haralake** [octobercms/october#4402] opened 2019-06-21 12:36 UTC
- OctoberCMS Build: ### 455
- PHP Version: 7.2
- Database Engine: MySQL
- Plugins Installed: Rainlab.StaticPages

### Description:
I'm using a simple repeater variable on static page:   
```
{repeater name="content_sections" prompt="Add another content section"}
<h3>
{text name="content_header" label="Content section" placeholder="Type in a heading and enter some content for it below"}{/text}
</h3>
<div>
{richeditor name="content_body" size="large"}{/richeditor}
</div>
{/repeater}
```
On static pages backend i create one static page and using repeater field i create 2 fields. Everything works ok, but if i delete one field and create a new one i get wrong data on save. As you can see on sample video, the problem starts when you delete one field. **If you delete one field you have to close the page and reopen it to be able to add more fields without a problem**. I test it on a clean install with latest build.    

I also noticed that after you delete the first field, the new field you create has filled fields and the data are the same with the first one. You can see it clearly on the video sample.   

![Screenshot](http://webik.gr/images/octobercms/repeater-issue.gif)

### Steps To Reproduce:
1. Create one repeater variable on static page layout
2. Create one static page
3. Create 2 repeater fields and save page
4. Delete first repeater field
5. Create a new repeater field and save page
6. Wrong data saved on content file. Only one field data saved.

**Comment by bennothommo** [comment] 2019-06-23 08:54
Confirmed. This will have to fixed in the Blog plugin, I believe.

**Comment by haralake** [comment] 2019-06-23 09:03
Do you mean Static Pages Plugin?

**Comment by bennothommo** [comment] 2019-06-23 09:12
@haralake Sorry, brain snap! :P Yep, the Static Pages plugin.

**Comment by haralake** [comment] 2019-06-23 09:39
To many plugins out there i guess.. : ) .So do i have to create a new issue for Static Pages plugin?

**Comment by bennothommo** [comment] 2019-06-23 11:27
@haralake That's fine, I know where the issue is. Will hopefully sort it out soon.

**Comment by haralake** [comment] 2019-06-23 15:20
@bennothommo that's great news!

**Comment by bennothommo** [comment] 2019-06-28 09:25
@haralake Would you mind testing PR #4424 and see if this resolves the issue for you?

**Comment by haralake** [comment] 2019-06-28 10:06
@bennothommo I test PR #4424 and i confirm it resolves the specific issue.

**Comment by bennothommo** [comment] 2019-06-28 10:53
@haralake thanks for confirming :D

**Comment by bennothommo** [comment] 2019-06-29 05:43
Fixed as of 3eac212.

**Comment by maartenmachiels** [comment] 2019-07-11 08:00
Hi guys, thanks for your extended work on this bug. When would the bugfix be available as an update in the backend of October CMS?

**Comment by w20k** [comment] 2019-07-11 08:06
By using a Dev build or on the next release - v1.0.457 (should be soon). We're currently working on the issues/prs to make it happened!

**Closed** 2019-07-11 13:29 UTC
Labels: Status: Completed, Type: Bug
