### ISSUE TITLE
Proxy fields relation id null on create

### ISSUE THREAD

**Issue by RedMarlin** [octobercms/october#2845] opened 2017-04-26 15:31 UTC
I have an issue with proxy fields. They were working previously (in test plugin and in my own plugin) correctly but I discovered few days ago that they are not working anymore.

Proxy fields configuration according to:
http://octobercms.com/forum/post/howto-create-two-models-on-a-single-form-a-guide-to-proxy-fields

Test plugin: latest (downloaded today), It works OK with October build 317 but not with 415.

Steps using daftspunk/oc-test-plugin for better reference.
##### Reproduce steps
1.Click on Create New Person
2.Change view to Proxy Fields
3. Fill in all the necessary data for phone proxy fields and person
4. Create person

##### Expected behavior
New Person will be created related to new Phone with all the details you have filled in.

##### Actual behavior
- The new person will be created correctly
- New phone will be created but without any relation to person.
- person_id column in october_test_phones table is saved as NULL

It works perfectly with Relation Controller, this only happens with Proxy Fields.

Is there a new method to make proxy fields work with current October build or is this a bug?

##### October build
October build: 415

**Comment by daftspunk** [comment] 2017-05-14 05:08
:+1: Replicated this. This seems to be something with the create context only, as it doesn't seem to occur when updating a person. The related model is created, just the relationship is lost or never established. Will need further investigation.

**Comment by RedMarlin** [comment] 2017-08-25 10:17
Any progress on this one? I tried to compare Oc versions(between the last working version and the current one) to see when the problem occurred and where it can be located, but found nothing.
I think it can be related to some vendor library changes.

**Comment by LukeTowers** [comment] 2017-08-29 16:41
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by alxy** [comment] 2017-10-03 22:03
This is really a tough one, but I think I figured it out.
We can clearly see all data does to the database and is correctly saved, however, the association procedure does not appear to work correctly. This is because the related model is associated ( https://github.com/octobercms/library/blob/master/src/Database/Relations/BelongsTo.php#L70 ) in the case of creation via this (deferred) event. All is good so far, but the crux is now, that the parent need to be saved again to make this ``associate()`` call effective. And this is never the case in ``FormController``. In fact it saves any of the models exactly once, first the parent, and after that the relations.

So give me some code to fix it. Sure, just open the [FormController](https://github.com/octobercms/october/blob/master/modules/backend/behaviors/FormController.php#L249-L253) and add this piece of code:

```
Db::transaction(function () use ($modelsToSave) {
            foreach ($modelsToSave as $modelToSave) {
                $modelToSave->save(null, $this->formWidget->getSessionKey());
            }

            if(count($modelsToSave) > 1) { // If there are multiple models, we can assume the first one to be the parent
                array_shift($modelsToSave)->save(null, $this->formWidget->getSessionKey());
            }
        });
```
This will solve the issue temprorarily, but I'm not sure if this introduces some side problems/bugs.
Maybe we can use these finding to come up with a better solution.

**Comment by LukeTowers** [comment] 2017-10-03 23:03
I appreciate you digging into this deeper @alxy, great examination of the problem! Knowing the problem is half of finding the solution so perhaps this will help push us closer to a solid fix :)

**Comment by daftspunk** [comment] 2017-10-04 13:44
Man I wish I had more time to look at these things. Thanks for your patience guys. Thanks @alxy too for spending over 2 hours trying to solve it, I hope you learned some valuable insight in to the inner workings of October.

**Comment by daftspunk** [comment] 2017-10-04 13:46
Note this issue was caused by fixing another issue

Refs https://github.com/octobercms/october/issues/1986

**Comment by alxy** [comment] 2017-10-04 19:09
@daftspunk Unfortunatly, I have to report that this fix is not working for me. My relations are actually ``belongsTo`` relation, as in ``Order belongsTo Address``, where the address fields are proxy fields in the order form.

However, I think I got a fix for this one.
While the other Relations do explicitly save their state ( https://github.com/octobercms/library/blob/master/src/Database/Relations/HasOne.php#L84 ), this is for ``BelongsTo`` not the case (https://github.com/octobercms/library/blob/master/src/Database/Relations/BelongsTo.php#L70). I would think that you thought ``associate`` would actually do the query to the database, but it doesn't.

I will provide a fix to this situation.

**Comment by daftspunk** [comment] 2017-10-05 17:14
The OP issue is fixed using the test plugin. Can you provide further instructions on how it is still broken, using the test plugin? A PR to that plugin may be required.

Need to test and fix against a real usage case.

**Closed** 2017-11-16 22:36 UTC
Labels: Priority: High, Status: Completed, Type: Bug
