### ISSUE TITLE
Limit the items in backend form repeater

### ISSUE THREAD

**Issue by joelamltc** [octobercms/october#2649] opened 2017-02-03 07:04 UTC
Is there any way to limit the repeater items?

Let say I use repeater plus media finder to be a image slider, and I only want user to upload maximum 5 images. Is is possible to limit the items in repeater?
Temporary, I just check the items in repeater on Model Event only.

Thank you.

##### October build
v1.0.390

**Comment by seanthepottingshed** [comment] 2017-02-03 07:17
@joelamltc good question! I would like to know this too ;)

**Comment by SebastiaanKloos** [comment] 2017-02-04 14:34
I guess this is currently not supported. After you added this, feel free to request a PR.

**Comment by joelamltc** [comment] 2017-02-04 17:50
Unluckily, my experience is not enough to update the core.

**Comment by SebastiaanKloos** [comment] 2017-02-04 17:58
@joelamltc I'll give it a try when I have some time.

**Comment by joelamltc** [comment] 2017-02-04 18:00
@SebastiaanKloos Thank you so much.

**Comment by LukeTowers** [comment] 2017-03-01 02:47
Duplicate of #1710, fixed by #2723

**Closed by LukeTowers** 2017-03-01 02:47 UTC
