### ISSUE TITLE
Disabled widget fileupload from filterFields() not working

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#3444] opened 2018-03-11 21:34 UTC
When i disabled fileupload widget from filterFields function, widget not disabled; But dump return disabled: true;

![default](https://user-images.githubusercontent.com/8817759/37258669-03662182-259d-11e8-98ea-fc8247a7acd2.JPG)
![2](https://user-images.githubusercontent.com/8817759/37258670-03884d34-259d-11e8-9647-5a319cc49959.JPG)

##### October build
434

**Comment by LukeTowers** [comment] 2018-03-12 04:40
Odd, this should have been fixed in https://github.com/octobercms/october/commit/5f91c45f7997571290b3cbc1307a69b642d6c6e6#diff-1ed71bcf1b00cec1209c03574555ff54. Is filterFields too late?

**Comment by LukeTowers** [comment] 2018-07-12 12:22
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by joakimbo** [comment] 2018-07-16 13:40
@LukeTowers Bump, it does seem that filterFields is too late to change (atleast) the fileupload widget

**Comment by LukeTowers** [comment] 2018-07-16 14:15
@joakimbo are you able to look into how we could work around or fix that?

**Comment by LukeTowers** [comment] 2018-07-16 14:16
Duplicate of #3639, switching to that one instead because it has better information

**Closed by LukeTowers** 2018-07-16 14:16 UTC
Labels: duplicate
