### ISSUE TITLE
SqlServerConnection Not Compatible With Illuminate\Database\ConnectionInterface

### ISSUE THREAD

**Issue by ibanks** [octobercms/october#3200] opened 2017-10-25 18:16 UTC
Hello. This is the error that I'm getting when specifying sqlsrv as one of my database drivers:

`Declaration of October\Rain\Database\Connections\SqlServerConnection::transaction(Closure $callback) must be compatible with Illuminate\Database\ConnectionInterface::transaction(Closure $callback, $attempts = 1)` 

What can I do to solve this? Thanks in advance.

**Comment by LukeTowers** [comment] 2017-10-25 18:41
@ibanks please post detailed replication instructions.

**Comment by ibanks** [comment] 2017-10-25 18:52
Okay. I believe below is what you are talking about:

##### Expected behavior
A valid database connection.

##### Actual behavior
When I run a query through my model the error that I'm getting is:
`Declaration of October\Rain\Database\Connections\SqlServerConnection::transaction(Closure $callback) must be compatible with Illuminate\Database\ConnectionInterface::transaction(Closure $callback, $attempts = 1)`

##### Reproduce steps
I changed the database connection from `pgsql` to `sqlsrv`. Then I updated the username and password respectively. Nothing else needed to be changed.

##### October build
October CMS Version 1.0.1

**Comment by LukeTowers** [comment] 2017-10-25 19:32
The issue is because the SqlServerConnection in October was copied over from Laravel, however Laravel changed their implementation.
October's version: https://github.com/octobercms/library/blob/master/src/Database/Connections/SqlServerConnection.php
Laravel's version: https://github.com/laravel/framework/blob/master/src/Illuminate/Database/SqlServerConnection.php
@daftspunk would need to weigh in on whether we need to replicate Laravel's connection class or not, perhaps we can just switch to using Laravel's connection straight up.

**Comment by ibanks** [comment] 2017-10-25 19:56
Okay. Thanks for looking into this and please keep me updated.

**Comment by daftspunk** [comment] 2017-10-25 20:01
This relates to https://github.com/octobercms/october/issues/2639

We have to duplicate this because it is an edge case and Laravel doesn't quite allow us to change the default Query Builder object that is returned.

The issue is part of the framework upgrade and is expected since the Laravel internals have changed. If anything we need more unit testing.

**Comment by daftspunk** [comment] 2017-10-25 20:01
Fixed in Build 427+

**Closed by daftspunk** 2017-10-25 20:01 UTC
Labels: Priority: High, Type: Bug

**Comment by LukeTowers** [comment] 2017-10-25 20:06
Awesome, thanks @daftspunk!

**Comment by ibanks** [comment] 2017-10-25 20:17
Okay. So what should I do at this point?

**Comment by LukeTowers** [comment] 2017-10-25 20:20
Implement the changes from https://github.com/octobercms/library/commit/d90996850cec16133b308772a7468d2e9a28b2d1 manually or wait for Build 427 to be released and update to that @ibanks

**Comment by ibanks** [comment] 2017-10-25 20:30
Okay. Good. I'll just implement the changes myself. Thank you very much.

**Comment by ibanks** [comment] 2017-10-25 22:21
Just out of curiosity. How long will it take Build 427 to be released?

**Comment by LukeTowers** [comment] 2017-10-25 22:43
Within a week I'd say @ibanks

**Comment by ibanks** [comment] 2017-10-26 13:58
Will I need to upgrade my version of October for these updates or will it be available for all versions?

**Comment by LukeTowers** [comment] 2017-10-26 15:04
It'll be available from Build 427 and up, it's not going to be backported to 419
