### ISSUE TITLE
Error when use a Rainlab builder plugin

### ISSUE THREAD

**Issue by devalexandre** [octobercms/october#3219] opened 2017-11-02 12:57 UTC
##### Expected behavior
create a model for  my plugin

##### Actual behavior
Error in method of plugin

BadMethodCallException: Call to undefined method RainLab\Builder\Widgets\ModelList::getCollapseStatus() in /srv/http/octobercms/vendor/october/rain/src/Extension/ExtendableTrait.php:388

##### Reproduce steps

Install RainLab Builder plugin
Create a plugin name Featured
create database tabel indev_featured
fields 
id integer primary key
name  string 100
content text
image text

after I try create a model, here is error

##### October build
419

**Comment by LukeTowers** [comment] 2017-11-02 14:18
@devalexandre do not cross post. This relates to the Builder plugin, so only post it in the builder plugin repository. If it's determined that it needs to be in this repository then we'll let you know. Creating two issues in two different places isn't going to get it looked at any faster. Duplicate of https://github.com/rainlab/builder-plugin/issues/193

**Closed by LukeTowers** 2017-11-02 14:18 UTC
