### ISSUE TITLE
ErrorException: count(): Parameter must be an array

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#4178] opened 2019-03-03 17:28 UTC
- OctoberCMS Build: 448
- PHP Version: 7.2 & 7.3

### Description:
When attempting to change the translation of a repeater an error popup appear.

```ErrorException: count(): Parameter must be an array or an object that implements Countable in modules/backend/formwidgets/Repeater.php:210```

### Steps To Reproduce:
Create a repeater, with a translation. Attempt to change the language - you are presented with this error.

**Comment by w20k** [comment] 2019-03-03 17:34
@AugmentBLU it was already addressed by @bennothommo. Could you test this PR to see if it helps (https://github.com/octobercms/october/pull/4160)?

**Comment by AugmentBLU** [comment] 2019-03-03 17:41
@w20k A new error appears now.

```
Undefined offset: 3
```

```
ErrorException: Undefined offset: 3 in /home/forge/why/releases/20190303173327/modules/backend/formwidgets/Repeater.php:206
Stack trace:
#0 /home/forge/why/releases/20190303173327/modules/backend/formwidgets/Repeater.php(206): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/home/forge/why...', 206, Array)
```

**Comment by w20k** [comment] 2019-03-03 17:42
@bennothommo I guess it's not over yet 😄 Could you look at it?

**Comment by AugmentBLU** [comment] 2019-03-03 17:45
This bug is breaking several sites. Any idea when it was introduced so I can roll back? It wasn't happening on my local setup with 447 on PHP 7.2.

**Comment by w20k** [comment] 2019-03-03 17:47
@AugmentBLU I guess with a new release... But it should be an edge build 448.

**Comment by bennothommo** [comment] 2019-03-03 17:52
@AugmentBLU Could you provide us with your form configuration (ie. `form_config.yml`) that you are using  as well as the POST data you used when the error occurred? It might be a particular widget inside the repeater which is causing this.

**Comment by AugmentBLU** [comment] 2019-03-03 17:54
Wow, data is being removed from the database on save. I don't have time to read in to this deeper as I now need to restore stuff.

**Comment by Rike-cz** [comment] 2019-03-03 18:16
The same problem. I added to line 210 condition...
`if (empty($widgetValue) || (is_iterable($widgetValue) && !count($widgetValue))) {`

**Comment by bennothommo** [comment] 2019-03-04 04:56
@Rike-cz are you using the Translate plugin as well?

@AugmentBLU Does the same issue happen if the Translate plugin is not enabled?

**Comment by Rike-cz** [comment] 2019-03-04 07:29
@bennothommo In that case (ver. 448) not. I think that issue happen because of custom (?) form widget. I use improved mediafinder and I found that mediafinder value causes that error. My mediafinder returns string - it's not empty but also not countable.

**Comment by bennothommo** [comment] 2019-03-04 07:43
@Rike-cz thanks for the info. How about with PR #4160 in place? Does that cause any issues for you? Just trying to determine what caused @AugmentBLU 's data loss.

**Comment by Rike-cz** [comment] 2019-03-04 08:08
@bennothommo PR #4160 works fine for me without Translate plugin. With Translate plugin I have 2 filled forms in repeater (indexes 0 and 1) and try to switch language. It throws `"Undefined offset: 0" on line 206 of C:\dev\web\www\icestudio\brancoreality\modules\backend\formwidgets\Repeater.php`.

**Comment by bennothommo** [comment] 2019-03-04 14:32
@Rike-cz Are you using the MLRepeater widget provided through the Translate plugin in this instance, or just a normal Repeater widget?

**Comment by tobias-kuendig** [comment] 2019-03-04 14:49
This is my fields config:

```
    downloads:
            label: Downloads
            span: auto
            type: repeater
            tab: Details
            form:
                fields:
                    download_name:
                        label: Bezeichnung
                        span: auto
                        type: text
                    download_file:
                        label: Datei
                        mode: file
                        span: auto
                        type: mediafinder
```

I am using RainLab.Translate as well and the whole `downloads` field is marked as translatable. 

What I noticed is that if I change the repeater to an other language I can save just fine (even changes made on other languages are saved). The countable error only appears if I have the primary language active in the repeater.

**Comment by Rike-cz** [comment] 2019-03-04 18:46
@bennothommo I am using repeater in [RainLab.Pages](https://github.com/rainlab/pages-plugin/#custom-page-fields) and I think it's automatically changed to MLRepeater through RainLab.Translate event hooks.

**Comment by bennothommo** [comment] 2019-03-05 03:50
Thanks all. It appears to be an incompatibility with the Translate plugin, specifically how the MLRepeater widget handles internal form widgets. I'll have to investigate further and possibly submit a PR for that too. In the mean time, I've added a fix to PR #4160 so that if the form widgets aren't available, it won't try to process them. It should at least fix the current issue.

**Comment by jonpxpx** [comment] 2019-03-06 17:43
I was getting the error without the use of Rainlab.Translate but using the custom fields within a template.

Fields seemed to be saving when applying the original PR - do we have an estimated timescale of when this might be fixed as we were about to upload 7 client sites (luckily, we didn't).

**Comment by w20k** [comment] 2019-03-06 18:19
@jonpxpx could you provide us with your configuration (from_config.yaml)? To test your use case and find the cause. 
Also, have you tested @bennothommo PR https://github.com/octobercms/october/pull/4160

**Comment by jonpxpx** [comment] 2019-03-08 15:14
@w20k To confirm, the PR did fix the issue. For now, I will have to stick with that as we have a site to get out quickly.

**Comment by w20k** [comment] 2019-03-08 15:35
@LukeTowers I guess PR #4160  from @bennothommo could be merged now as it fixed the issue.

**Comment by bennothommo** [comment] 2019-03-08 16:00
@w20k I might suggest holding off for another day or 2, so I can see if issue #4175 from @seanthepottingshed is related to this. I was also hoping @AugmentBLU might be able to let us know if their issue was resolved by the latest changes to the PR as well.

**Comment by MC1010** [comment] 2019-03-10 01:46
@w20k This bug exists in 447 as well. Specifically, I encountered it a few minutes ago when using a colorpicker inside a repeater. I am not using the Translate plugin. PR #4160 solved the issue. Thank you! @bennothommo

**Comment by bennothommo** [comment] 2019-05-23 14:48
This issue has likely been sorted by the recent Repeater updates (#4234, #4334). Please re-open or re-submit this issue if this is not the case.

**Closed by bennothommo** 2019-05-23 14:48 UTC
Labels: Type: Bug
