### ISSUE TITLE
polyfill-php72 required after OctoberCMS 3.7 update

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5824] opened 2024-10-13 19:03 UTC
After updating to OctoberCMS 3.7 through the backend update button a 500 error message is returned and the full back- and front-end is broken. the error message in the background is:
 `PHP Warning:  require(/vendor/composer/../symfony/polyfill-php72/bootstrap.php): Failed to open stream: No such file or directory in /vendor/composer/autoload_real.php on line 41`
This folder was not present in previous octoberCMS either but now it seems to be required. I have looked up this polifill package and when I place it in the vendor/synfony folder manually, October works again and the update seems to have completed. 
I have seen this happen with every installation I attempted an update. They all ran on PHP 8.2 or 8.3. Is there anything I can do to prevent this from happening?

**Comment by daftspunk** [comment] 2024-10-13 21:49
Hi @Dahfrenk

This is a [known issue](https://talk.octobercms.com/t/problem-installing-latest-october-cms/2913/13) caused by a symfony package update. It can be resolved by running `composer update` in the command line. Otherwise, the following patch can be used to prevent the error. Unfortunately, it is a chicken and egg problem since we can't deliver this patch without performing an update.

The following patch can be manually applied to ensure the patched files are available:
https://github.com/octobercms/library/commit/0ba30958a7ddb8b53b23f5841d9a10e03d97c226

I have also included a zip file that you can upload to the website that will patch the files as well.

- [v3.6.30 manual patch zip file](https://octobercms.com/storage/app/media/release-notes/october-rain-3-6-30-patch.zip)

Best regards

**Closed as completed by daftspunk** 2024-10-13 21:49 UTC
