### ISSUE TITLE
Number field takes string value

### ISSUE THREAD

**Issue by jaska27** [octobercms/october#3206] opened 2017-10-27 13:22 UTC
##### Expected behavior
Form field type 'number' should take only numbers.

##### Actual behavior
1. Form field type 'number' takes numbers and strings, parses it and returns '0' in case of fail. After saving the 0 value is visible in form field and in db.
2. If the form field type 'number' is jsonable as the element of repeater widget, the input value isn't parsed - just saved as it is as json in db.

##### Reproduce steps
1. Add number field to form.
2. Insert string value to input field.
3. Save the form.

##### October build
Build unknown - installed the newest version 24.10.2017 (with Laravel 5.5.13)

**Comment by LukeTowers** [comment] 2017-10-27 16:06
Duplicate of #2311

**Closed by LukeTowers** 2017-10-27 16:06 UTC
