### ISSUE TITLE
Relation view filter widget has not been bound to the controller

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#5056] opened 2020-04-28 17:37 UTC
- OctoberCMS Build: 465
- PHP Version: 7.3

### Description:
![tags](https://user-images.githubusercontent.com/4247582/80518770-38843480-8987-11ea-9eee-3aa7f494a026.gif)

### Steps To Reproduce:
- relation Category hasMany Articles
- render relation view widget in category preview page with custom filter scopes.
- type something to search fields of any group type scope.

**Comment by LukeTowers** [comment] 2020-04-28 17:54
@alxy is this related to the stuff you did?

**Comment by alxy** [comment] 2020-04-30 15:09
Probably yes, but does the filtering work, just the search doesn't?
@Rike-cz Maybe you can look into it, I have started a new job and don't have too much time now.

**Comment by LukeTowers** [comment] 2020-04-30 17:04
@Rike-cz my guess is that since the popover DOM nodes are technically at the root of the document and not inside the parent form element the required `relation` POST variable is not being sent with the search AJAX request which means that the relationcontroller isn't initializing the required widgets.

**Comment by Rike-cz** [comment] 2020-04-30 20:26
> Probably yes, but does the filtering work, just the search doesn't?
@alxy Yes, filtering works only search does not.
It looked like simple one line missing problem but what I inspected and @LukeTowers wrote, it is not so simple...

**Comment by LukeTowers** [comment] 2020-04-30 21:23
It shouldn't be too difficult, you just need to be able to provide the relation field in the AJAX requests sent by the filters.

**Comment by alxy** [comment] 2020-05-10 15:49
I can confirm the issue.

**Comment by alxy** [comment] 2020-05-10 16:38
While trying to fix this, I have realized that it is actually a duplicate of https://github.com/octobercms/october/issues/4775 , which has already been fixed by @bennothommo . Nice work there! It works for me in view and manage mode.

**Comment by bennothommo** [comment] 2020-05-11 02:16
@alxy Thanks for letting us know about the duplication.

This issue is fixed by 9155e7d.

**Closed by bennothommo** 2020-05-11 02:16 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
