### ISSUE TITLE
Fatal Exception called when an image is missing

### ISSUE THREAD

**Issue by karnold** [octobercms/october#924] opened 2015-02-02 20:09 UTC
It would be ideal if the entire page didnt need to die with a fatal error because an image associated with an object is missing.

![screen shot 2015-02-02 at 2 08 56 pm](https://cloud.githubusercontent.com/assets/1236813/6008170/1cd874e8-aae5-11e4-9249-5084c5d393b3.png)

**Comment by flip4bytes** [comment] 2015-02-02 20:15
I've had this exact same thing happen and couldn't agree more with @karnold

The only way I could fix the error was by creating another jpg mirroring the random name inside of the 3 folders within the public directory and THEN going in and removing the instance of the image within the backend. The problem happened to me when using a "featured image" within the blog. Because that information is stored in a database, I couldn't just locally remove the linkage, I had to actually access the backend to remove the instance of the featured image, of which I couldn't because the error was thrown preventing me from accessing the backend.

**Comment by daftspunk** [comment] 2015-02-02 21:05
Duplicate of #181

**Closed by daftspunk** 2015-02-02 21:05 UTC
Labels: duplicate
