### ISSUE TITLE
Richeditor doesn't save in Code mode.

### ISSUE THREAD

**Issue by tombien** [octobercms/october#2243] opened 2016-07-26 10:00 UTC
##### Expected behavior
When I have Richeditor in Code mode, and click on Save, I expect that content is saved. Flash message say it.

##### Actual behavior
When I have Richeditor in Code mode, and click on Save, there is Flash message "Page was saved" but nothing is saved.
If I make changes in Code mode I must switch back to normal mode and then click on Save to save my content.

##### Reproduce steps
Open for example Static page plugin, edit some content in Richeditor - Code mode - click on Save. Close tab. Open content again - nothing is saved.

##### October build
348

**Comment by daftspunk** [comment] 2016-07-26 10:21
This appears to be a duplicate of #2109

**Closed by daftspunk** 2016-07-26 10:21 UTC
Labels: duplicate
