### ISSUE TITLE
Froala Editor removes the form even though it is allowed

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#4906] opened 2020-01-23 14:31 UTC
OctoberCMS Build: 464 and older versions

### Steps To Reproduce and description
I pasted a HTML form into the textarea. I used the Froala editor Code view mode.
![1](https://user-images.githubusercontent.com/2959112/72992591-49576400-3df4-11ea-858c-4f99729679cf.JPG)

After that I changed to normal view and I clicked on the  Code view again.
![2](https://user-images.githubusercontent.com/2959112/72992767-99cec180-3df4-11ea-87e5-37b166d3a948.JPG)

The editor removed the form HTML tag. I used default editor settings, so the form tag is allowed.
![3](https://user-images.githubusercontent.com/2959112/72993045-021da300-3df5-11ea-802f-55ccef375a28.JPG)

**Comment by LukeTowers** [comment] 2020-01-23 19:14
Duplicate of #3305

**Closed by LukeTowers** 2020-01-23 19:14 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
