### ISSUE TITLE
SASS compiler fails to compile `rgba(#xxx, yy)` value with php 7.4

### ISSUE THREAD

**Issue by XIOLog** [octobercms/october#5193] opened 2020-07-01 14:42 UTC
- OctoberCMS Build: master
- PHP Version: 7.4
- Database Engine: MariaDB

### Description:
SASS file with

``` scss
&__overlay {
    background-color: rgba($link, 0.95);
}
```

I had an error:
```
/* Trying to access array offset on value of type null */
```

I have switched to the Laravel 6 branch (wip/laravel-6), but the problem still remains.

**Comment by LukeTowers** [comment] 2020-07-01 20:58
Duplicate of #5058

**Closed by LukeTowers** 2020-07-01 20:58 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
