### ISSUE TITLE
Adding image in Froala adds full path to src

### ISSUE THREAD

**Issue by tombien** [octobercms/october#4968] opened 2020-03-04 13:36 UTC
- OctoberCMS Build: 464
- PHP Version: 7.1

### Description:
When I add Image in Froala editor, it add full path to src attribute (with protocol and domain).
It is important to add only relative paths (starting with /storage/...) not http(s)://domain.test/storage/...

### Steps To Reproduce:
Add Image in Froala editor and look at source.

I think, this bug is important to fix, because for now Froala is unuseful for example on testing domains etc. We put some content and we must change all images srs.

**Comment by mjauvin** [comment] 2020-03-04 13:50
This is discussed in here:

https://github.com/octobercms/october/issues/4082

**Comment by tombien** [comment] 2020-03-04 13:55
@mjauvin  thanks, sorry I miss this. But I feel this feature very unhandy, like others in discussion. Mainly because local development, testing domains development, changing protocols etc.

**Comment by mjauvin** [comment] 2020-03-04 14:30
Totally agree with you!

**Comment by LukeTowers** [comment] 2020-03-04 20:05
Closing as a duplicate of #4082. I do agree this is something that should be fixed though.

**Closed by LukeTowers** 2020-03-04 20:05 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
