### ISSUE TITLE
Problem with language folder names containing dashes and pluralization

### ISSUE THREAD

**Issue by manogi** [octobercms/october#2611] opened 2017-01-13 21:52 UTC
I hope "Issues" ist the right place for this:

OctoberCMS translations make use of [this Symfony Pluralization class](https://github.com/symfony/translation/blob/master/PluralizationRules.php). But have a look at line 38: it checks if the locale name is longer than 3 characters and then tries to split it at the "_" sign. After that, the locale is basically empty, and the translation falls back to taking the first part of the string in your translation file.  

So basically pluralization of strings in lang folder like "pt-br" does not work.

This probably never caused problems so far, because none of the core language files seem to use pluralization. But now a problem appeared [in this Twig Extensions plugin repository here](https://github.com/vojtasvoboda/oc-twigextensions-plugin/issues/20) by @vojtasvoboda where pluralization is used and a pt-br language was added. 

The dilemma is now: either change the folder name to pt_br and make it work for this plugin and break compatibility with the core language files, or...?

I don't know if Symfony will change the behavior of their pluralization class to make it work for dashes as well as underscores?

Well, I hope someone will have something smart to say about this ;-)

Cheers,  Sebastian

**Comment by daftspunk** [comment] 2017-01-26 00:52
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by ribsousa** [comment] 2017-02-04 17:12
The reported problem occurs when I add the language with the default code used in octobercms to **pt-br**, the plurization does not work for [vojtasvoboda-twigextensions **time_diff**](https://octobercms.com/plugin/vojtasvoboda-twigextensions) plugin. [Change the language aqui](http://gleebe.org/en/blog) to **pt_br** the plurization will not work for the date of the post, returning the singular version of the translation.

When I add the language with the code to **pt_br**, and rename the language directory of the plugin to **pt_br**, the plurization works correctly for plugin [vojtasvoboda-twigextensions time_diff filter](https://octobercms.com/plugin/vojtasvoboda-twigextensions). [Change the language here](http://iepm.online/pt_br/blog) to **en** or to **pt_br** the plurization will work correctly or the date of the post.

Now we have a problem, because if we change both the **language code** and **its directory** to **pt_br**, we break the compatibility with **Octobercms** it uses **pt-br**

This problem occurs (as reported **panogi**) because OctoberCMS translations make use of this [Symfony Pluralization class](https://github.com/symfony/translation/blob/master/PluralizationRules.php). But if you do not know what to do, you will not be able to do it. After that, the locale is basically empty, and the translation falls back to the first part of the string in your translation file.

```php
   /**
     * Returns the plural position to use for the given locale and number.
     *
     * @param int    $number The number
     * @param string $locale The locale
     *
     * @return int The plural position
     */
    public static function get($number, $locale)
    {
        if ('pt_BR' === $locale) { // SEE THAT IT VERIFIES (pt_BR) AND DOES NOT (pt-br)
            // temporary set a locale for brazilian
            $locale = 'xbr';
        }
        if (strlen($locale) > 3) {
            $locale = substr($locale, 0, -strlen(strrchr($locale, '_')));
        }
        if (isset(self::$rules[$locale])) {
            $return = call_user_func(self::$rules[$locale], $number);
            if (!is_int($return) || $return < 0) {
                return 0;
            }
            return $return;
        } 
```

**Comment by LukeTowers** [comment] 2017-03-04 04:27
@ribsousa If we were to modify the pluralization rules class so that it followed October's approach of using '-' instead of '_' as the locale separator, would that resolve the problem? 

Also, I'm not overly familiar with the pluralization aspect of the language library, what exactly calls the Symphony pluralization class?

**Comment by ribsousa** [comment] 2017-03-04 17:29
@LukeTowers, Well I changed my language in octobercms backend rainlab translate pugin from **pt-br** to **pt_br** and I renamed my language folder to "**pt_br**", and it worked perfectly. So I think the problem really is "**_**".

When I mentioned [Symphony pluralization class](https://github.com/symfony/translation/blob/master/PluralizationRules.php),  I referred to the [Sessions Lab product](https://symfony.com/) that octobercms uses to translate content.

**Comment by daftspunk** [comment] 2017-04-05 12:27
Concisely what action needs to come of this?

**Comment by LukeTowers** [comment] 2017-04-05 14:12
I believe the problem is that October doesn't properly support pluralized translations because we use `-` to separate our language from dialect in the folder naming convention; whereas the Symphony code that would have handled that expects `_`. I'd need to test it myself, none of my current translations use pluralization either.

**Comment by ribsousa** [comment] 2017-04-05 14:18
@LukeTowers, from what I've tested here, it's just that "-" the problem.

**Comment by daftspunk** [comment] 2017-04-28 08:43
Is it possible to implement our own version of `PluralizationRules`?

**Comment by LukeTowers** [comment] 2017-10-18 23:30
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-18 23:30 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
