### ISSUE TITLE
List of checkboxes do not work on the touch screen

### ISSUE THREAD

**Issue by VoroninWD** [octobercms/october#3755] opened 2018-09-04 22:18 UTC
##### Expected behavior
It should work

##### Actual behavior
It does not work. Pressing does not give any result

##### Reproduce steps
Go to any list and open its settings. Try turning off or on any checkboxes.
![screenshot_2018-09-05-01-04-15-205_com android chrome](https://user-images.githubusercontent.com/20097205/45060469-a12ee700-b0a8-11e8-86e1-4b72c1972b52.jpg)

It also does not work on the computer in the view mode through the device
![image](https://user-images.githubusercontent.com/20097205/45060546-f79c2580-b0a8-11e8-9a6c-7ab31dcd0e15.png)

##### October build
442

To solve this problem - just delete the list from the file: /modules/backend/widgets/lists/partials/_setup_form.htm

![image](https://user-images.githubusercontent.com/20097205/45060611-4fd32780-b0a9-11e8-8cb9-664fc986ba47.png)

And everything will work. But can there be another reason?

**Comment by w20k** [comment] 2018-09-05 11:35
Hi, @ebashu-on-holidays,
Needs additional effort to investigate the cause :)

Found out that only first checkbox works and not under the checkbox spot, but top left corner from it.

**Comment by ebashu-on-holidays** [comment] 2018-09-07 12:56
@w20k, yes, I tried to fix the problem through CSS, but it did not work out

**Comment by bennothommo** [comment] 2019-10-11 00:36
Confirmed that bug still exists in 459.

**Comment by w20k** [comment] 2019-10-11 08:31
Thanks, @bennothommo will look!

**Comment by mjauvin** [comment] 2019-11-02 19:23
confirming the bug as well. could it be related to z-index?

**Comment by w20k** [comment] 2019-11-02 19:25
It might be, but while testing localy I couldn't find the cause or any issues related to z-index. Still in `process`.

**Comment by mjauvin** [comment] 2019-11-02 21:31
Removing the "custom-checkbox" class from the surrounding <div> does not trigger the buggy behavior...

**Comment by mjauvin** [comment] 2019-11-19 13:31
So it's really some JS code or CSS breaking for mobile related to this class

**Comment by mjauvin** [comment] 2019-11-19 13:53
I've been poking everywhere this class is referenced and I just cannot find what's causing this.

Has anyone ever seen it work properly on mobile?

**Comment by mjauvin** [comment] 2019-11-19 14:57
Ok, getting closer... if I remove the "is-sortable" class from the following line:

https://github.com/octobercms/october/blob/develop/modules/backend/widgets/lists/partials/_setup_form.htm#L9

It works fine.

The problem is caused by this call here:

https://github.com/octobercms/october/blob/develop/modules/backend/assets/js/october.simplelist.js#L32

Looks like it's a known issue with jquery-sortable:

https://github.com/johnny/jquery-sortable/issues/209

**Comment by mjauvin** [comment] 2019-11-19 15:03
Can you guys test the referenced PR, it fixes the issue for me.

**Comment by w20k** [comment] 2019-11-25 19:26
@mjauvin sure, in a second ;)

**Comment by mjauvin** [comment] 2019-11-28 13:04
I confirm this fixes the issue on Android mobile browsers below:

- Firefox
- Opera
- Google Chrome
- Microsoft Edge

**Comment by mjauvin** [comment] 2019-11-28 13:05
Good work @daftspunk !

**Comment by LukeTowers** [comment] 2019-11-28 16:10
Fixed by https://github.com/octobercms/october/commit/566f138eabd8032aefc9aed84fe67ab4f8e6011f

**Closed** 2019-11-28 16:10 UTC
Labels: Status: Completed, Type: Bug
