### ISSUE TITLE
Component Validations fails

### ISSUE THREAD

**Issue by davidatMB** [octobercms/october#3686] opened 2018-08-11 14:03 UTC
##### Expected behavior
I use this validation settings for my component:
```
'validationPattern' => '.+@.+\.(de|com|org)',
'validationMessage' => 'Keine korrekte Adresse'
```
so I expect a eMail-Adress to be like: 'bla@blub.de'
##### Actual behavior
When giving '' (empty String) it gives me this error message:
'Please enter the external parameter name.' and not 'Keine korrekte ...'

When giving 'xxx' then it passes validation.

##### Reproduce steps
Create component
```
class ContactForm extends ComponentBase {

    public function componentDetails() {
        return [
            'name' => 'david.contact::lang.plugin.contact.components.contactform.name',
            'description' => 'david.contact::lang.plugin.contact.components.contactform.description'
        ];
    }

    public function defineProperties() {
        return [
            'to' => [
                'title' => 'Kontaktformular',
                'description' => 'Kontaktformular',
                'default' => 'bla@blub.de',
                'validationPattern' => '.+@.+\.(de|com|org)',
                'validationMessage' => 'keine korrekte Adresse'
            ],
        ];
    }
}
```

##### October build
437

**Comment by LukeTowers** [comment] 2018-08-11 16:56
Try `\S+@\S+\.\S+` as your pattern instead. Failing that, attempt to debug the issue in this file: https://github.com/octobercms/october/blob/5daf4365ae18df4deb961fab6d7e498a41c3ec3b/modules/system/assets/ui/js/inspector.validationset.js, which is probably included in storm-min.js

**Comment by davidatMB** [comment] 2018-08-13 13:58
> \S+@\S+\.\S+
This doesn't work either - same behavior as with my pattern.
But that main thing is that I get an error message which I haven't defined
```
Please enter the external parameter name.
```
not 'keine korrekte Adresse'.

I just noticed, that when I insert for example 'xxx' I get the correct validationMessage ('keine korrekte Adresse') - only when left completely empty the wrong validation Message is outputted.

Nor of the files modules\system\assets\ui\ storm-min.js, storm.js or modules\system\assets\ui\js\inspector.validationset.js is used.
I inserted the string 'debugger;' in all files but no debuggsession opens.

**Comment by w20k** [comment] 2018-08-21 11:51
Hi @davidatMB , @LukeTowers ,

Build version: v1.0.440
Screenshot: ![screen_shot_2018-08-21_at_14_45_42](https://user-images.githubusercontent.com/1053320/44399751-56ae5600-a551-11e8-82aa-bea3a3fa1ee9.png)
Code (just pasted to defineProperties in one of my ComponentBase implementation): 
` 'to' => [
                'title' => 'Kontaktformular',
                'description' => 'Kontaktformular',
                'default' => 'bla@blub.de',
                'validationPattern' => '.+@.+\.(de|com|org)',
                'validationMessage' => 'keine korrekte Adresse'
            ],`

Works fine as meant to be.

**Comment by LukeTowers** [comment] 2018-08-22 01:53
@w20k thanks. @davidatMB closing as we can't reproduce this.

**Closed by LukeTowers** 2018-08-22 01:53 UTC
Labels: Status: Response Needed, Type: Unconfirmed Bug
