### ISSUE TITLE
Media Manager Permission

### ISSUE THREAD

**Issue by damanic** [octobercms/october#1208] opened 2015-06-15 03:47 UTC
I have a user that I would like to give access to only the 'Pages' module and the 'Media Manager'

Can you please give the media manager its own permission please.

Currently it is set to `cms.*`  so if I want to give a user access to the media manager I am forced to give them access to a CMS area.

**Comment by daftspunk** [comment] 2015-06-27 01:52
Fixed by 57f32d0055f236cd152aeeab6303e2335d0621cf
Duplicate of #1134

**Closed by daftspunk** 2015-06-27 01:52 UTC
