### ISSUE TITLE
Upgrade included Froala richtext editor to 2.7.x

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#3203] opened 2017-10-26 09:57 UTC
It's already on a first patch after new release: https://www.froala.com/wysiwyg-editor/changelog

Quick Insert looks especially nice: https://www.froala.com/wysiwyg-editor/examples/quick-insert

**Comment by LukeTowers** [comment] 2018-02-08 19:58
@daftspunk please also fix https://github.com/octobercms/october/issues/3385

**Comment by Farrow** [comment] 2019-01-31 10:18
I realise you're obviously very busy @daftspunk and that this update probably involves lots of tests and checks, but is there a chance you can look into this sometime soon?

Our users (running Chrome on mac) are having issues with adding links to images in the richeditor. When they insert an image and then try to add a link to it, like so:
![richeditor-image-insert-link](https://user-images.githubusercontent.com/4127349/52046854-a9982a80-253f-11e9-8d39-3a43315b935f.jpg)

the popup that is opened:
![richeditor-image-insert-link-popup](https://user-images.githubusercontent.com/4127349/52046938-dc422300-253f-11e9-949e-c2acd6bb596a.jpg)

closes itself if/when it is clicked anywhere. Technically it is still usable if you only use the keyboard with paste, tab, space and enter keys but most of our users aren't that literate.

I believe that this issue is related to https://github.com/froala/wysiwyg-editor/issues/1733 - though as mentioned it also seems to be affecting Chrome on mac as well as Safari mentioned in that issue. This doesn't seem to be affecting Chrome, Firefox or Edge on Windows, however. 

The issue is apparently fixed in later versions of Froala (from that linked issue Feb 2017+) so I'm hoping this update will resolve our issues. It might also be the case that the update will resolve one or more of https://github.com/octobercms/october/issues/3064 and its related issues

**Comment by LukeTowers** [comment] 2019-01-31 16:30
@Farrow would you be willing to pitch in a monetary contribution to help prioritize the issue?

**Comment by Farrow** [comment] 2019-02-01 10:20
We asked our client but unfortunately they want to prioritise other things for now. I will update you if they decide to put any money up for this though.

If they do, what is the best way to go about it?

**Comment by LukeTowers** [comment] 2019-02-01 18:52
Just shoot me a message on Slack or email me at octobercms@luketowers.ca @Farrow

**Comment by daftspunk** [comment] 2019-03-28 16:51
Per OP, Froala has been bumped to v2.9.3 (463008450b627864cb3906b29cb1690e7e4517fc)

This should be available in Build 449+

**Closed by daftspunk** 2019-03-28 16:51 UTC
Labels: Priority: High, Status: Accepted, Type: Maintenance

**Comment by amdad** [comment] 2019-03-28 23:27
@daftspunk SAMMY IS A HERO.

**Comment by amdad** [comment] 2019-03-28 23:29
HURRAY, HURRAY

**Comment by amdad** [comment] 2019-03-28 23:29
HURRAY, HURRAY SAMMY IS A HERO!
