### ISSUE TITLE
CMS: Support for German Umlaute in URL #validation

### ISSUE THREAD

**Issue by dahLucky** [octobercms/october#2743] opened 2017-03-10 16:08 UTC
Please consider adding support for German Umlaute ä, ü, ö (adjusting validator behaviour for URL validation). Umlaute ä, ü, ö are supported chars for domains in Austria and Germany e.g. http://www.österreich.at, https://de.wikipedia.org/wiki/%C3%96sterreich)

**Comment by LukeTowers** [comment] 2017-03-10 17:22
Duplicate of https://github.com/octobercms/library/pull/178 which adds support for Unicode characters in slugs. The only thing preventing that PR from being merged is its lack of unit tests. If you add the tests and reimplement the change, then we'll merge it; otherwise it'll be looked at when we have time.

**Closed by LukeTowers** 2017-03-10 17:22 UTC
Labels: duplicate
