### ISSUE TITLE
Duplicates records where used 'relation'

### ISSUE THREAD

**Issue by ITCorporate** [octobercms/october#1988] opened 2016-05-05 19:56 UTC
It's problem in any plugin where used 'relation'.
For example in a plugin Acme.CRM I can create new 'opportunity'. I create two records of 'opportunity' where in tab 'Contacts' choose 'Add contact' and add all available contacts. When I want create third record, I can see this:
![screen shot 05-05-16 at 10 46 pm](https://cloud.githubusercontent.com/assets/15619945/15055057/3d296120-1313-11e6-9889-ad945a327d3e.PNG)
It's duplicates. After saving all is normal. But the more entries the more duplicates.

How do I fix this problem? Thank You!

**Comment by daftspunk** [comment] 2016-05-12 20:04
I wasn't able to replicate this. Using the CRM plugin on the latest edge build of October. When I select Wes Anderson, I see one Wes Anderson. Try reinstalling the plugin. If it occurs again, please provide clear instructions on how to arrive at the bug behavior. Please also include the Build number of October you are using.

**Comment by ITCorporate** [comment] 2016-05-12 23:30
Recorded a short video:
https://youtu.be/12eh9WzW0XU

I have two versions of the cms: 318 and 332. In both cases, the problem is the same.

Duplicates are not added to the database, but it is inconvenient

**Comment by daftspunk** [comment] 2016-05-13 07:00
Thanks. I watched it and it demonstrates the issue very well.

Duplicate of #1411

**Closed by daftspunk** 2016-05-13 07:00 UTC
Labels: duplicate, Type: Bug
