### ISSUE TITLE
After build 385 form field relation doesn't show items related

### ISSUE THREAD

**Issue by alvaro-canepa** [octobercms/october#2524] opened 2016-11-30 10:02 UTC
##### Expected behavior
Plugins, like RainLab User, must show all groups associated to each user. Or any plugin that use BelongToMany relation, must show all possible relation elements on a checkbox list. 

##### Actual behavior
Plugins, like RainLab User, only show first element in checkbox lists of a BelongsToMany related field.

##### Reproduce steps
```php
// \RainLab\User\Models\User
    public $belongsToMany = [
        'groups' => ['RainLab\User\Models\UserGroup', 'table' => 'users_groups']
    ];
```

```yaml
    # /plugins/rainlab/user/models/user/fields.yaml
    groups:
        label: rainlab.user::lang.user.groups
        tab: rainlab.user::lang.user.account
        type: relation
        emptyOption: rainlab.user::lang.user.empty_groups
```

Navigate to `/backend/rainlab/user/users` and click any user with groups to see the Groups field, empty.

This is the same to any model that has `BelongsToMany` relation

##### October build
385

**Comment by KGE** [comment] 2016-11-30 15:59
confirm :(

As I can see build 384 soffer the same issue too.

**Comment by manuelbua** [comment] 2016-12-02 09:01
I can also confirm this: this does look like a deal-breaking issue on production environments, but i don't see the priority being raised for this one?

**Comment by alvaro-canepa** [comment] 2016-12-02 09:50
For me, is very important, because I can't assign groups to users, In the User plugin. Or I can't assign keys to groups in the Passage plugins.

**Comment by tobias-kuendig** [comment] 2016-12-03 15:49
Having the same issue on build 385.

Using the demo plugin, you can see the problem when visiting /backend/october/test/users/update/2/relation. Only one role is listed in the relation checkbox list. The checkbox is rendered without a value.

**Comment by daftspunk** [comment] 2016-12-03 23:12
Confirmed this was caused by #2507
Impacting builds 384+

**Comment by daftspunk** [comment] 2016-12-03 23:52
Fixed in Build 387+

For priority issues like this, please ping me in Slack or IRC (username daftspunk or spunky).

**Closed by daftspunk** 2016-12-03 23:52 UTC
Labels: Priority: High, Status: Completed, Type: Bug
