### ISSUE TITLE
Fileupload sql fatal error

### ISSUE THREAD

**Issue by MaxNozhkin** [octobercms/october#3689] opened 2018-08-15 09:23 UTC
Since v1.0.438, when open page with fileupload field in backend - fatal error.
Postgres postgres (PostgreSQL) 10.4. PHP 7.2.8.

`SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "as" LINE 1: ...hment_id" is not null or "CAST(system_files"."id" as "TEXT)"... ^ (SQL: select * from "system_files" where ("system_files"."attachment_type" = RainLab\Blog\Models\Post and "system_files"."attachment_id" = 2 and "field" = featured_images and "system_files"."attachment_id" is not null or "CAST(system_files"."id" as "TEXT)" in (select "slave_id" from "deferred_bindings" where "master_field" = featured_images and "master_type" = RainLab\Blog\Models\Post and "session_key" = 3uAJxNfzJMY03ybe3KpvfeuEVMziCznkI9jgZWHA and "is_bind" = 1)) and not exists (select 1 from "deferred_bindings" where slave_id = CAST(system_files.id AS TEXT) and "master_field" = featured_images and "master_type" = RainLab\Blog\Models\Post and "session_key" = 3uAJxNfzJMY03ybe3KpvfeuEVMziCznkI9jgZWHA and "is_bind" = 0 and id > coalesce((select max(id) from deferred_bindings where slave_id = CAST(system_files.id AS TEXT) and master_field = featured_images and master_type = RainLab\Blog\Models\Post and session_key = 3uAJxNfzJMY03ybe3KpvfeuEVMziCznkI9jgZWHA and is_bind = 1 ), 0)) order by "sort_order" asc)`

**Comment by LukeTowers** [comment] 2018-08-15 23:02
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by onurguven** [comment] 2018-08-20 03:36
I'm having the same issue.

**Comment by chrisbethelepb** [comment] 2018-08-20 17:19
I ran in to the same bug in a different area, but can also reproduce it on a backend controller that contains a fileupload widget.

Steps to reproduce:
1) Install: `composer create-project october/october test-pgsql`
2) Clone test plugin: `git clone https://github.com/octoberrain/test-plugin.git test-pgsql/plugins/october/test`
3) Run a new pgsql instance via docker: `sudo docker run --name pgsql -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres`
4) Change `config/database.php` config to use pgsql:
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | PDO Fetch Style
    |--------------------------------------------------------------------------
    |
    | By default, database results will be returned as instances of the PHP
    | stdClass object; however, you may desire to retrieve records in an
    | array format for simplicity. Here you can tweak the fetch style.
    |
    */

    'fetch' => PDO::FETCH_CLASS,

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => 'pgsql',

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver'   => 'sqlite',
            'database' => 'storage/database.sqlite',
            'prefix'   => '',
        ],

        'mysql' => [
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'port'      => 3306,
            'database'  => 'database',
            'username'  => 'root',
            'password'  => '',
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
        ],

        'pgsql' => [
            'driver'   => 'pgsql',
            'host'     => 'localhost',
            'port'     => 5432,
            'database' => 'postgres',
            'username' => 'postgres',
            'password' => 'postgres',
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
        ],

        'sqlsrv' => [
            'driver'   => 'sqlsrv',
            'host'     => 'localhost',
            'port'     => 1433,
            'database' => 'database',
            'username' => 'root',
            'password' => '',
            'prefix'   => '',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk have not actually be run in the databases.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'cluster' => false,

        'default' => [
            'host'     => '127.0.0.1',
            'password' => null,
            'port'     => 6379,
            'database' => 0,
        ],

    ],

];
```
5) Run migrations
```
cd test-pgsql
php artisan october:up
```
6) Run local server `php artisan serve`
6) Log in to backend
7) Go to http://127.0.0.1:8000/backend/october/test/galleries/create
8) Crash

```
~/Projects/contrib/test-pgsql$ php -v
PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
```

[system.log](https://github.com/octobercms/october/files/2303330/system.log)

[composer.lock.txt](https://github.com/octobercms/october/files/2303334/composer.lock.txt)

[composer.json.txt](https://github.com/octobercms/october/files/2303335/composer.json.txt)

**Comment by chrisbethelepb** [comment] 2018-08-20 17:48
```
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "as" LINE 1: ...test_posts" where ("CAST(october_test_posts"."id" as "TEXT)"... ^ (SQL: select "october_test_posts".* from "october_test_posts" where ("CAST(october_test_posts"."id" as "TEXT)" in (select "slave_id" from "deferred_bindings" where "master_field" = posts and "master_type" = October\Test\Models\Gallery and "session_key" = 9RAkw2XFXDvBnqMoDvAJ4KBMNXYBM9xniZ38RuXu and "is_bind" = 1)) and not exists (select 1 from "deferred_bindings" where slave_id = CAST(october_test_posts.id AS TEXT) and "master_field" = posts and "master_type" = October\Test\Models\Gallery and "session_key" = 9RAkw2XFXDvBnqMoDvAJ4KBMNXYBM9xniZ38RuXu and "is_bind" = 0 and id > coalesce((select max(id) from deferred_bindings where slave_id = CAST(october_test_posts.id AS TEXT) and master_field = posts and master_type = October\Test\Models\Gallery and session_key = 9RAkw2XFXDvBnqMoDvAJ4KBMNXYBM9xniZ38RuXu and is_bind = 1 ), 0)) order by "id" desc)
```

`where ("CAST(october_test_posts"."id" as "TEXT)"` is clearly where the problem is in this query.

**Comment by LukeTowers** [comment] 2018-08-21 02:52
Possibly related to https://stackoverflow.com/questions/40016417/laravel-eloqeunt-cast-table-column-with-postgres-generating-error

**Comment by daftspunk** [comment] 2018-08-21 03:40
Interesting. It worked before.

Actual:

```
where ("CAST(october_test_posts"."id" as "TEXT)"
```

Expected:

```
where (CAST("october_test_posts"."id" as "TEXT")
```

First and foremost, can we confirm the expected should appear exactly as shown above?

**Comment by daftspunk** [comment] 2018-08-21 04:32
Nevermind. This was caused by 8c084045596aaf182a8eae412873437f3729222d

 - Enhance deferred_bindings table query performance (#328)

Subsequently fixed by fc8cd3e6d6aba36e60787c006774215d5b3582a8

We'll need someone to test this to make sure it is working before preparing a build.

**Comment by chrisbethelepb** [comment] 2018-08-21 13:07
@daftspunk that fixed the Test plugin, it now seems to work as expected. Thanks for the quick response!

**Comment by daftspunk** [comment] 2018-08-22 02:14
Cheers for following that up.

**Closed by daftspunk** 2018-08-22 02:14 UTC
Labels: Priority: High, Status: Completed, Type: Bug
