### ISSUE TITLE
create:controller name pluralisation

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#473] opened 2014-07-27 10:25 UTC
When I do a `php artisan create:controller My.Plugin TaxClass` the *config_form.yaml, config_list.yaml* files title fields all say **TaxClasses**. They should say **Tax Class** - CapCase words should be separated, and it should be the singular version - for example *Edit Tax Class, Preview Tax Class* etc.

**Comment by daftspunk** [comment] 2015-03-26 11:42
Duplicate of [or fixed by] #472

**Closed by daftspunk** 2015-03-26 11:42 UTC
Labels: unconfirmed bug
