### ISSUE TITLE
Trouble after plugin created

### ISSUE THREAD

**Issue by bekerov** [octobercms/october#2107] opened 2016-06-08 04:59 UTC
Hello. I created plugin `php artisan create:plugin AuthorName.PluginName`

And see image. Is this ok?
![image](https://cloud.githubusercontent.com/assets/2405629/15883231/e8c4574c-2d4e-11e6-8fa5-decd71d75857.png)

Also cant find it on backend.

**Comment by daftspunk** [comment] 2016-06-08 07:35
This is a duplicate of #1955

This bug somehow made it in to the current release, it will be fixed in the upcoming stable version.

**Closed by daftspunk** 2016-06-08 07:35 UTC
