### ISSUE TITLE
Tab Form Fields Trigger Options Ignored when Lazy Loading Tab

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#4880] opened 2020-01-14 10:00 UTC
- OctoberCMS Build: `464`
- PHP Version: `7.2`
- Database Engine: `mysql`
- Plugins Installed: `n/a`

### Description:
If you lazy load a tab which would only otherwise be displayed when all the fields within fulfil their required trigger options the tab is displayed anyway. The tab should only be displayed when the trigger options are complete, eg:

If you click on the **Employment Details** tab there are no fields until you flick the `is_employed` switch. Without lazy loading the tab wouldn't be displayed until the fields are triggered - which is the correct behaviour.

### Steps To Reproduce:

- Download an install test plugin with the following PR: https://github.com/octoberrain/test-plugin/pull/84
- Navigate to `admin/october/test/people/update/6`

**Comment by seanthepottingshed** [comment] 2020-02-15 07:41
Bumpity bump

**Comment by bennothommo** [comment] 2020-02-19 03:07
@seanthepottingshed I've taken a look at this for you (and confirmed the bug), however, this looks to be an incompatibility of ideas unfortunately.

The hiding and showing of tabs based on trigger rules work when the fields are present in the HTML (either hidden due to the rules, or visible), however, lazy loaded tabs don't have any HTML until they are loaded for the first time.

This means that if the "Employment Details" tab is hidden by the normal functionality, and I click the "Employed" switch, the tab will still not show because none of the fields are visible in the tab. If I get it to retrieve the fields, then that removes the point of lazy loading the tabs.

We've got a couple of options at this juncture:

- We simply tell people to avoid using trigger fields and lazy tabs in the same form in the docs, and leave it as is.
- We use some server-side functionality when trigger fields are interacted with, to determine which lazy tabs should be visible.

@LukeTowers any thoughts on the above?

**Comment by seanthepottingshed** [comment] 2020-02-19 09:12
@bennothommo Thanks for your time researching and confirming the bug, really appreciated. 

Obviously updating the documents to advise against using both tab lazy loading and field trigger options would be quickest win, however it would be simply dreamy if both could work.

**Comment by LukeTowers** [comment] 2020-02-20 05:03
@bennothommo I believe there was a proposal about the lazyloaded tabs still including trigger attributes and hidden input data containers, but the problem with that is the available options for how a given FormWidget could handle their data lockers in HTML is too varied for us to reliably do so. 

I haven't given this one too much thought, but could we include only the field container divs that contain their trigger attributes and not their actual content, and then use those attributes to check if a given field might be impacted by the updating of another field and then at that point load the tab behind the scenes to evaluate the trigger condition?

**Comment by LukeTowers** [comment] 2020-02-20 05:04
That still wouldn't work for the opposite direction (trigger condition based on a field in a hidden tab), but that one seems pretty unworkable tbh so I don't think it's worth the time to look into a solution right now.

**Comment by bennothommo** [comment] 2020-02-20 05:26
@LukeTowers my thoughts too. I might just update the docs just to indicate that triggers and lazy tabs are not recommended to be used together.

**Comment by seanthepottingshed** [comment] 2020-02-20 07:59
@bennothommo @LukeTowers thanks for your thoughts on time and thoughts on this.

**Comment by LukeTowers** [comment] 2020-03-31 07:37
@bennothommo could you update the docs as above so we can close this issue for 466?

**Comment by bennothommo** [comment] 2020-03-31 10:58
@LukeTowers already done :) - https://github.com/octobercms/docs/commit/252f2bfdba2321738b07f25b91e1159fa4daf8bf#diff-3253ac7e6278d278efcecb4cf1619b35

**Comment by LukeTowers** [comment] 2020-03-31 17:48
Excellent @bennothommo, thanks!

**Closed by LukeTowers** 2020-03-31 17:48 UTC
Labels: Website / Marketplace / Docs
