### ISSUE TITLE
Composer dependencies on plugin testcases

### ISSUE THREAD

**Issue by uxms** [octobercms/october#1833] opened 2016-03-07 09:11 UTC
As mentioned in the title, while starting unittests for a specific plugin, it raises "Class not found" error. This class is required by plugin's composer.json file and it is located in plugin's vendor folder. Dependency can be found and works when any website request happens, but not when unittest runs.

Actually, #1714  not solved in some cases..

Maybe "plugin dependency pool" or similar logic will be useful for managing additional libraries which plugins needs externally.

**Comment by daftspunk** [comment] 2016-03-07 09:13
First and foremost, we need clear instructions on how to replicate this.

**Comment by uxms** [comment] 2016-03-07 09:31
Our json file: https://gist.github.com/uxms/3209ee76e5b9456dce68

1- Create phpunit.xml file in root of the plugin: https://gist.github.com/uxms/3166c63f85958bf58cb1
2- Create PLUGIN/test/PluginTestCase.php: https://gist.github.com/uxms/b21f96e11fbd4afedc45
3- Create PLUGIN/test/unit/classes/IpTest.php: https://gist.github.com/uxms/d3d35b397668879ae5a0
4- Sample content of Ip class of plugin: https://gist.github.com/uxms/d8fc9f63f2d2dd04b417

"GeoIp2\Database\Reader" class is required by plugin's composer file and it can be found in plugin's vendor folder.
It can be instanced on normal requests but not unittests. While running unittest, is raises "Fatal error: Class 'GeoIp2\Database\Reader' not found" http://prnt.sc/ac86p0

Hope this instructions helps.

**Comment by uxms** [comment] 2016-03-07 09:42
Probably, it looks only for root vendor folder, not plugins vendors. So class can't be found on root vendor folder while tests not looking for plugin's composer.json file.

**Comment by daftspunk** [comment] 2016-03-07 10:51
Try modifying the `tests\PluginTestCase.php` class line 131:

```
$plugin = $manager->loadPlugin($namespace, $path);
$manager->registerPlugin($plugin);
$manager->bootPlugin($plugin);
```

**Comment by uxms** [comment] 2016-03-07 11:10
Yes, it works like a charm, thanks..

**Comment by SaifurRahmanMohsin** [comment] 2016-11-28 17:01
+1

Modifying `tests\PluginTestCase.php` doesn’t solve the trick either.
Steps to reproduce:
1. Install translate plugin from the backend.
2. From terminal CD into plugins/rainlab/translate
3. Run phpunit

Here’s the output I get:
```
Moz at Moz in ~/projects/Current/Acme/plugins/rainlab/translate
$ phpunit
PHP Fatal error:  Class 'PluginTestCase' not found in /Users/Moz/Projects/Current/Acme/plugins/rainlab/translate/tests/unit/behaviors/TranslatableCmsObjectTest.php on line 12

Fatal error: Class 'PluginTestCase' not found in /Users/Moz/Projects/Current/Acme/plugins/rainlab/translate/tests/unit/behaviors/TranslatableCmsObjectTest.php on line 12
```

**Comment by daftspunk** [comment] 2016-11-28 21:21
Seems to be working over here. Running Windows 10

```
# phpunit
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

........

Time: 9.73 seconds, Memory: 25.25MB

OK (8 tests, 43 assertions)
```

Might be a case sensitivity issue if it fails on a unix based system.

**Comment by LukeTowers** [comment] 2017-10-18 22:07
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-18 22:07 UTC
Labels: Priority: Low, Type: Maintenance
