### ISSUE TITLE
Please update Froala

### ISSUE THREAD

**Issue by jajacobs** [octobercms/october#3492] opened 2018-04-09 15:05 UTC
Trying to extend the richeditor to automatically scramble email addresses in links href attribute. But the generated code is being decoded after insert and saved as normal text. This has been fixed in version 2.7.4.

See https://github.com/froala/wysiwyg-editor/issues/2431

**Comment by LukeTowers** [comment] 2018-04-09 16:18
Duplicate of #3203

**Closed by LukeTowers** 2018-04-09 16:18 UTC
