### ISSUE TITLE
Bug in pivot sorting

### ISSUE THREAD

**Issue by vakopian** [octobercms/october#4335] opened 2019-05-12 17:45 UTC
- OctoberCMS Build: 454
- PHP Version: 7.2
- Database Engine: MySQL 5.7
- Plugins Installed: none

### Description:
Two models called `Product` and `Category` that are in a many-to-many relationship with a pivot table. The pivot table has a column `relation_sort_order`, which should be used to sort the products within a category. The `belongsToMany` in `Category` is set like this:
```php
    public $belongsToMany = [
        'products' => [
            'Acme\Plugin\Models\Product',
            'table' => 'acme_plugin_category_product',
            'pivot' => ['relation_sort_order'],
            'order' => ['relation_sort_order']
        ]
    ];
```
When trying to create a new category, the following error is received:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relation_sort_order' in 
'order clause' (SQL: ...)
```
where it's trying to run the following sql:
```sql
select `acme_plugin_products`.*
from `acme_plugin_products`
where (acme_plugin_products.id in (select `slave_id`
                                    from `deferred_bindings`
                                    where `master_field` = products
                                      and `master_type` = Acme\Plugin\Models\Category
                                      and `session_key` = 17Ik8vNIs7tBP5fhNTcTlY3IEv4JpyS3W6gzobGS
                                      and `is_bind` = 1))
  and acme_plugin_products.id not in (select `slave_id`
                                       from `deferred_bindings`
                                       where `master_field` = products
                                         and `master_type` = Acme\Plugin\Models\Category
                                         and `session_key` = 17Ik8vNIs7tBP5fhNTcTlY3IEv4JpyS3W6gzobGS
                                         and `is_bind` = 0
                                         and id
                                           > ifnull((select max(id) from deferred_bindings where slave_id = acme_plugin_products.id
                                         and master_field = products
                                         and master_type = Acme\Plugin\Models\Category
                                         and session_key = 17Ik8vNIs7tBP5fhNTcTlY3IEv4JpyS3W6gzobGS
                                         and is_bind = 1 )
                                           , 0))
order by `relation_sort_order` asc, `product_name` desc
```

So the `order` clause is clearly added to the wrong query.

### Steps To Reproduce:

* Create two simple models `Product` and `Category`. 
* Create a pivot table:
```php
class CreateCategoryProductTable extends Migration
{
    public function up()
    {
        Schema::create('acme_plugin_category_product', function(Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->integer('category_id')->unsigned();
            $table->integer('product_id')->unsigned();
            $table->integer('relation_sort_order')->unsigned()->default(0);

            $table->foreign('category_id')->references('id')->on('acme_plugin_categories');
            $table->foreign('product_id')->references('id')->on('acme_plugin_products');
        });
    }

    public function down()
    {
        Schema::dropIfExists('acme_plugin_category_product');
    }
}
```
* Configure the `RelationController` in `Category` model:
```php
    public $implement = [
        'Backend.Behaviors.FormController',
        'Backend.Behaviors.ListController',
        'Backend.Behaviors.RelationController'
    ];
```
* Configure `belongsToMany` in `Category` model:
```php
    public $belongsToMany = [
        'products' => [
            'Acme\Plugin\Models\Product',
            'table' => 'acme_plugin_category_product',
            'pivot' => ['relation_sort_order'],
            'order' => ['relation_sort_order']
        ]
    ];
```
* Create the `Categories` and `Products` controllers, and add the `RelationController` to `Categories`, with standard
```php
    public $relationConfig = 'config_relation.yaml';
```
where `config_relation.yaml` is also standard:
```yaml
# ===================================
#  Relation Behavior Config
# ===================================

products:
  label: Product
  view:
    toolbarButtons: add|remove
    list: $/acme/plugin/models/product/columns.yaml
  manage:
    list: $/acme/plugin/models/product/columns.yaml
    form: $/acme/plugin/models/product/fields.yaml

```

**Comment by vakopian** [comment] 2019-07-04 18:22
https://www.bountysource.com/issues/74048786-bug-in-pivot-sorting

**Comment by Cleanse** [comment] 2019-07-05 01:45
How are you making the call on the pivot? I use October and just built a plugin with pivot sorting.

```
public $belongsToMany = [
        'matches' => [
            'Cleanse\Event\Models\Match',
            'table' => 'cleanse_event_broadcast_match',
            'pivot' => ['lineup'],
            'order' => 'pivot_lineup asc'
        ]
    ];
```

Maybe try changing your line to: ` 'order' => ['pivot_relation_sort_order']`.

**Comment by w20k** [comment] 2019-07-05 04:45
Might be fix your looking for https://github.com/octobercms/october/issues/4432

**Comment by vakopian** [comment] 2019-07-06 22:19
@Cleanse , using `pivot_relation_sort_order` doesn't work, it just complains about `Unknown column 'pivot_relation_sort_order' in 'order clause'`. Would you mind sharing a working code example where pivot sorting works?

@w20k please note that the example above does not use the Relation widget, which your pull request is fixing. It uses the `Backend\Behaviors\RelationController` behavior.

**Comment by Cleanse** [comment] 2019-07-07 15:21
I'll try and get you an example out tomorrow. My project does not use the Backend, so that could be why. I'll test a backend example similar to your setup. 

The project I created that has working pivot sorting: https://github.com/Cleanse/events/blob/master/models/Match.php

**Comment by LarBearrr** [comment] 2019-10-08 01:22
@vakopian What exactly are you trying to do here? I think the issue is due to the fact that you are not defining a `pivotModel` on your relationship. If you could explain your desired end result, and possibly provide a detailed example, I may be able to point you in the right direction.

**Comment by adamo** [comment] 2019-11-12 09:24
I had the same problem for me it seems that this notation works 
```
'order' => [
                'pivot'=>'series_sort_order'
],
```

**Comment by adamo** [comment] 2019-11-12 10:00
I'm having the same problem, using the sorting work but I cannot attach (add button) any model in the relation widget 

`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relation_sort_order' in 'order clause' (SQL: select `depcore_inspiracjekludi_products`.* from `depcore_inspiracjekludi_products` where published = 1 and `depcore_inspiracjekludi_products`.`id` not in (137, 2, 150, 149) order by `relation_sort_order` asc, `product_number` desc)" on line 664 of /var/www/public/inspiracje/vendor/laravel/framework/src/Illuminate/Database/Connection.php`

The order is displayed as it should in the back and in frontend.

**Comment by woshj** [comment] 2019-11-25 17:18
> I'm having the same problem, using the sorting work but I cannot attach (add button) any model in the relation widget
> 
> `"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relation_sort_order' in 'order clause' (SQL: select `depcore_inspiracjekludi_products`.* from `depcore_inspiracjekludi_products`where published = 1 and`depcore_inspiracjekludi_products`.`id`not in (137, 2, 150, 149) order by`relation_sort_order`asc,`product_number` desc)" on line 664 of /var/www/public/inspiracje/vendor/laravel/framework/src/Illuminate/Database/Connection.php`
> 
> The order is displayed as it should in the back and in frontend.

You're having exactly the same issue as me, hope someone finds a workaround it gets sorted soon

**Comment by adamo** [comment] 2019-11-29 11:35
I've found some workaround fot displaying the relation window in my case the `add`
In the controller I override the method

```
public function onRelationButtonAdd()
    {
        SeriesModel::extend(function($model) {
            $model->belongsToMany['products']['order'] = array('product_number');
        });

        return $this->asExtension('RelationController')->onRelationButtonLink();
    }

```

I'm using a column from the relation not the pivot table.

**Comment by daftspunk** [comment] 2019-12-05 09:21
Confirmed this issue has been fixed by 5f8a5454eeb401d5ac13b5b644353b8dcaf0de14

@bennothommo this is yours to close and claim the bounty!

**Comment by daftspunk** [comment] 2019-12-05 09:26
Replication instructions:

1. Install the [test plugin](https://github.com/octoberrain/test-plugin)
1. Add the `order` sorting to the `roles_pivot` definition inside file **plugins\october\test\models\User.php**

        'roles_pivot' => [
            'October\Test\Models\Role',
            'table' => 'october_test_users_roles',
            'pivot' => ['clearance_level', 'is_executive'],
            'order' => 'clearance_level',
            'timestamps' => true
        ],

3. Navigate to Users > Click a User > Click **Pivot Data** Tab
4. Click the Add Role button

Without code in 5f8a5454eeb401d5ac13b5b644353b8dcaf0de14 an exception is thrown. With the code, the nefarious sort order appears to be removed and no error occurs

**Comment by bennothommo** [comment] 2019-12-05 09:31
Thanks heaps @daftspunk :D

**Closed** 2019-12-05 09:40 UTC
Labels: Status: Completed, Type: Bug, bounty, hacktoberfest, help wanted

**Comment by bennothommo** [comment] 2019-12-09 14:28
@vakopian Would you mind testing the fix provided above, and releasing the bounty if this has sorted out the issue for you?

**Comment by woshj** [comment] 2019-12-11 09:54
Sorry if this is the wrong place to ask but how do we apply these fixes I manually went into the backend files and changed them to match the ones in the above commit.

Once I had done that I now can't view the list within the backend at all way before because I get a chance to click the add button within the relation controller.

Error: "Call to undefined method Backend\Widgets\Lists::getSortColumn()"

Am I on the wrong build number (458) or is applying this fix not as simple as copy pasting the correct cod from the commit?

**Comment by bennothommo** [comment] 2019-12-11 10:07
@woshj The `getSortColumn` method in `Backend\Widgets\Lists` was only made public in build 460, which is an edge update. You will need to enable `edgeUpdates` in your `config/cms.php` file to retrieve that version.

**Comment by woshj** [comment] 2019-12-11 10:22
@bennothommo Thanks mate! Now I can sort the columns although you still can't use the Add Button as mentioned by OP

> When trying to create a new category, the following error is received:
> ```
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relation_sort_order' in 
> 'order clause' (SQL: ...)
> ```

Unless I still have something wrong with my setup but it all seems okay to me and the sorting fix has been applied so I think it's working correctly

**Comment by vakopian** [comment] 2020-06-14 01:47
Unfortunately this bug is still not fixed in the latest build 466. I just tried my test project and got the same error as @woshj. 

This bug was a major blocker for the project I was attempting with octobercms and I spent many hours trying to fix it myself in the core, without success. This endeavor has proved to me that the enormous complexity in this framework is just not worth the effort (a bug like this should have been relatively easy to fix, but turned out to be next to impossible to debug and isolate). And thus, sadly, I have since abandoned the framework.

**Comment by LukeTowers** [comment] 2020-06-14 20:31
@vakopian I would encourage you to give it another try, I've tested https://github.com/octobercms/october/commit/24f87ae10ebd97fe5f6ba4c2a87cf60d521f9861 and it solves the problem with the add button too. The framework is not that complicated, but like any framework you have to invest time into understanding how everything fits together in order to solve complex issues with edge cases.
