### ISSUE TITLE
Error in october installer

### ISSUE THREAD

**Issue by trsh** [octobercms/october#2389] opened 2016-09-24 11:41 UTC
##### Expected behavior

Install from installer without errors.
##### Actual behavior

Any ideas on this installer error -> "Parse error: syntax error, unexpected 'pR' (T_STRING), expecting ']'" on line 119 of /home/fotocimparimpa/public_html/install_files/php/InstallerRewrite.php(43) : eval()'d code 
##### Reproduce steps

Install with newest installer and PHP 7

**Comment by trsh** [comment] 2016-09-24 12:34
Turns out, I can't use high security password like this "]pR@}WTgR.n1".

**Comment by LukeTowers** [comment] 2017-01-30 07:00
@trsh What are you using this password for? The admin account login password or the Database connection password?

**Comment by trsh** [comment] 2017-01-30 18:41
Database password. One defined in config.

**Comment by daftspunk** [comment] 2017-02-01 20:06
Duplicate of #2361

**Closed by daftspunk** 2017-02-01 20:06 UTC
Labels: Status: Revision Needed, Type: Unconfirmed Bug
