### ISSUE TITLE
Mail adding inline CSS to mail template and layout

### ISSUE THREAD

**Issue by pavicmario** [octobercms/october#3511] opened 2018-04-17 22:10 UTC
##### Expected behavior
Sending mail with Mail Facade and method sendTo as usual. Choosing custom template and custom layout for mail to send.

Layout:
```
`<!DOCTYPE HTML>`
`<html>`
`<head>`
    `<meta name="viewport" content="width=device-width, initial-scale=1.0" />`
    `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />`
`</head>`
`<body>`


   `  {{ content|raw }}`
                                   
`</body>`
`</html>`
```

Template:
`<p style="color: red;">Igra</p>`

Expected:
```
`<!DOCTYPE HTML>`
`<html>`
`<head>`
    `<meta name="viewport" content="width=device-width, initial-scale=1.0" />`
    `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />`
`</head>`
`<body>`

`<p style="color: red;">Igra</p>`
                                   
`</body>`
`</html>`
```
##### Actual behavior
Expecting what's actual sent the raw format is:
```
`<!DOCTYPE HTML>`
`<html>`
`<head>`
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">`
`</head>`
`<body style="font-family: Avenir,Helvetica,sans-serif; box-sizing: border-box; background-color: #f5f8fa; color: #74787e; height: 100%; hyphens: auto; line-height: 1.4; margin: 0; -moz-hyphens: auto; -ms-word-break: break-all; width: 100% !important; -webkit-hyphens: auto; -webkit-text-size-adjust: none; word-break: break-word;">`
     `<p style="font-family: Avenir,Helvetica,sans-serif; box-sizing: border-box; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left; color: red;">Igra</p>`
                                  
`</body>`
`</html>`
```
So this inline CSS in body and in p element added out of nowhere.
##### Reproduce steps
Just simple sending mail as shown in tutorial.

##### October build
Newest october by todays date 17.4.2018.

**Comment by LukeTowers** [comment] 2018-04-17 22:14
Duplicate of #3192

**Closed by LukeTowers** 2018-04-17 22:14 UTC
