### ISSUE TITLE
Problem with Artisan when creating new plugin

### ISSUE THREAD

**Issue by jamiegrand** [octobercms/october#1922] opened 2016-04-10 19:48 UTC
On October build 318 check out the folder structure generated in the image below
![artisan](https://cloud.githubusercontent.com/assets/6545316/14412579/6ddc3e10-ff5d-11e5-8136-1fa7efff3b80.jpg)

**Comment by daftspunk** [comment] 2016-04-11 07:06
Duplicate of https://github.com/octobercms/library/issues/204

**Closed by daftspunk** 2016-04-11 07:06 UTC
