### ISSUE TITLE
Package files from server are corrupt

### ISSUE THREAD

**Issue by Xerxos** [octobercms/october#4186] opened 2019-03-07 12:42 UTC
- OctoberCMS Build: ### Newest from https://octobercms.com/

### Description:

Hi,

When I try install October, I get:

> Package files from server are corrupt
> Something went wrong during the installation. Please check the log file (install_files/install.log) or see the documentation for more information. 

LOG:
```
.============================ POST REQUEST ==========================.
[2019/03/07 01:34:29] Postback payload: Array
(
    [step] => downloadCore
    [meta] => Array
        (
            [core] => Array
                (
                    [hash] => 61c929870890c2206ff3d84c4a12c354
                    [build] => 447
                    [uhash] => 3bea68b737188c91d4613538c6dbcec4
                )

        )

    [handler] => onInstallStep
)

[2019/03/07 01:34:29] Install step: downloadCore
[2019/03/07 01:34:42] File hash mismatch: 61c929870890c2206ff3d84c4a12c354 (expected) vs d41d8cd98f00b204e9800998ecf8427e (actual)
[2019/03/07 01:34:42] Local file size: 0
[2019/03/07 01:34:42] Handler error (onInstallStep): Package files from server are corrupt



```

**Comment by Cleanse** [comment] 2019-03-09 16:33
Were you getting a 500 server error after you attempted to update? I tried to update today and now my server 500'd.

**Comment by LukeTowers** [comment] 2019-03-09 16:51
@Cleanse are you using edgeBuilds? @w20k can you link the code reversion to fix that? I'm guessing his issue is the Http Network class issue.

**Comment by Cleanse** [comment] 2019-03-09 16:52
@LukeTowers I was running an update from the backend. The update error'd and now my site has a 500 message.

**Comment by w20k** [comment] 2019-03-09 16:55
@Cleanse could you try this fix: https://github.com/octobercms/library/commit/21b00902c8bf1265b643374f0a54e88074242acf

**Comment by LukeTowers** [comment] 2019-03-09 16:59
@w20k I believe the breaking change is in the latest edge build, the fix is in the develop branch.

**Comment by Cleanse** [comment] 2019-03-09 17:01
@w20k @LukeTowers I reverted line 282 (added `$this->requestData` back in) `src/Network/Http.php` but I am unable to retry the update because of the 500 error.

**Comment by w20k** [comment] 2019-03-09 17:08
@LukeTowers we had three majors, which I do remember, and none of those `should` cause this thing to happen: Login|LogoutCache/Middleware, Repeater, and HasMany.

**Comment by w20k** [comment] 2019-03-09 17:22
@LukeTowers Did a fresh install with an upgrade to the latest edge build (with scratch options) - nothing...

<img width="1209" alt="Screenshot 2019-03-09 at 19 20 29" src="https://user-images.githubusercontent.com/1053320/54074867-a3b10a00-42a0-11e9-9ec6-d484cd044413.png">
<img width="1440" alt="Screenshot 2019-03-09 at 19 22 14" src="https://user-images.githubusercontent.com/1053320/54074873-ad3a7200-42a0-11e9-9425-31aa5141b31b.png">

**Comment by w20k** [comment] 2019-03-09 17:24
@Cleanse - could you disabled all the plugins?

**Comment by Cleanse** [comment] 2019-03-09 17:26
@w20k I'll back up my data and see about a reinstall. I get a 500 error on all routes after the update errored midway through.

**Comment by daftspunk** [comment] 2019-03-28 03:14
Referring to the OP issue only. Note the important detail here:

```
[2019/03/07 01:34:42] Local file size: 0
```

This means the package delivered to the installer was empty. This is usually caused by some misconfiguration of the web server. Since the "Test the connection to the installation server" passed then its not caused by a firewall or anything, rather it is due to the size of the file / timeout configuration in the web server.

Refer to the documentation for more details:
https://octobercms.com/docs/setup/installation#troubleshoot-installation

> **An error 500 is displayed when downloading the application files**: You may need to increase or disable the timeout limit on your webserver. For example, Apache's FastCGI sometimes has the -idle-timeout option set to 30 seconds.

Hope this helps!

**Closed by daftspunk** 2019-03-28 03:14 UTC
Labels: Status: Review Needed, Type: Bug
