### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by ghostix** [octobercms/october#1511] opened 2015-10-12 10:29 UTC
The last button to select custom colors doesn't work for relation model. 
![capture](https://cloud.githubusercontent.com/assets/13018389/10426025/d40ce802-70dc-11e5-85f3-dbc7759c20b6.PNG)

**Comment by Samuell1** [comment] 2016-05-02 09:24
I have same issue, anybody know how to fix it ?

**Comment by daftspunk** [comment] 2016-05-28 06:11
Duplicate of #1145

**Closed by daftspunk** 2016-05-28 06:11 UTC
