### ISSUE TITLE
Can not create new assets in backend

### ISSUE THREAD

**Issue by Cellular-** [octobercms/october#2192] opened 2016-07-08 14:58 UTC
When I log in to the backend, I should be able to click on CMS->Assets->Add new and have it open up a blank assets page.

When I log in to the backend  click on CMS->Assets->Add new, no new asset page is created. Nothing happens. The Add new button is clicked with no response from the CMS.

I should be able to click on CMS->Assets->Add new and have it open up a blank assets page.

October build 347

OS: Windows 7 
Browser: Google Chrome

Plugins installed: 
RainLab.User	1.2.7
RainLab.Blog	1.2.8
RainLab.Forum	1.0.17
RainLab.Builder	1.0.10
October.Demo	1.0.1
RainLab.Location	1.0.3
RainLab.Twitter	1.0.4
Renatio.Logout	1.0.2

**Comment by Teranode** [comment] 2016-07-11 02:16
Does the sidebar disappear as soon as you click on add? If so ten u need to pin the sidebar.

**Comment by daftspunk** [comment] 2016-07-18 20:48
Duplicate of #2190 ?

**Comment by Cellular-** [comment] 2016-07-19 13:59
Yes. Thanks. Having another issue with moving around assets too.

**Closed** 2016-07-26 10:18 UTC
Labels: duplicate
