### ISSUE TITLE
not working on windows 10 / apache 2.4.46 / php 8.0.1 / postgresql 13

### ISSUE THREAD

**Issue by CnApTaK** [octobercms/october#5464] opened 2021-01-19 11:22 UTC
- OctoberCMS Build: v1.1.1
- PHP Version: PHP 8.0 (8.0.1)
- Database Engine: PostgreSQL 13.1 (Ubuntu 13.1-1.pgdg20.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
- Plugins Installed: 

### Description:

not working :(

### Steps To Reproduce:

1. clean install in empy folder: composer create-project october/october .
2. php artisan october:version                                                                                                                                                                                      *** Detecting October CMS build...                                                                                                                                                                                 *** No database detected - skipping setting the build number.                                                                                                                                                      *** Detected a modified version of October CMS build 470. 
3. configuration: php artisan october:install
`========= INSTALLATION COMPLETE =========' 
4. launch chrome with http://localhost and get code 500 in response
Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

(1/1) FatalErrorExceptionDeclaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)
--
in PDOConnection.php line 81

P.S.  but it;s working whithout issues when i change php to version 7.4.14

**Comment by LukeTowers** [comment] 2021-01-19 16:02
Duplicate of #5452

**Closed as completed by LukeTowers** 2021-01-19 16:02 UTC
Labels: duplicate
