### ISSUE TITLE
[Bug] PostgreSQL > Undefined EXCEPTION Illuminate\Database\QueryException

### ISSUE THREAD

**Issue by christophheich** [octobercms/october#1726] opened 2016-01-26 10:03 UTC
Build: 313

Hey,

tested it several times, and always gettin the exception below while entering the settings page Administrators: link: "/backend/backend/users"

The Bug occurs only in PostgreSQL (tested it in MySQL and SQLite which both work fine)

Unhandeled Error:

SQLSTATE[42883]: Undefined function: 7 ERREUR: la fonction string_agg(character varying, unknown) n'existe pas LINE 1: select "backend_users".*, (select string_agg(name::VARCHAR, ... ^ HINT: Aucune fonction ne correspond au nom donné et aux types d'arguments. Vous devez ajouter des conversions explicites de type. (SQL: select "backend_users".*, (select string_agg(name::VARCHAR, ', ') from "backend_user_groups" inner join "backend_users_groups" on "backend_user_groups"."id" = "backend_users_groups"."user_group_id" where "backend_users_groups"."user_id" = "backend_users"."id") as "groups" from "backend_users" order by "login" desc limit 20 offset 0)

______________________________________________________________

Undefined EXCEPTION
Illuminate\Database\QueryException

        // If an exception occurs when attempting to run a query, we'll format the error
        // message to include the bindings with SQL, which will make this exception a
        // lot more helpful to the developer instead of just the database's errors.
        catch (Exception $e)
        {
            throw new QueryException(
                $query, $this->prepareBindings($bindings), $e
            );
        }
  
        return $result;
    }

**Comment by daftspunk** [comment] 2016-01-27 00:02
Duplicate of #1418
Fixed in Build 314

**Closed by daftspunk** 2016-01-27 00:02 UTC
Labels: PostgreSQL
