### ISSUE TITLE
composer instal failed

### ISSUE THREAD

**Issue by tempcke** [octobercms/october#3486] opened 2018-04-05 00:55 UTC
##### Expected behavior
I expect to execute the command `composer create-project october/october myoctober` without errors as detailed here https://octobercms.com/docs/console/commands#console-install-composer

##### Actual behavior
`composer create-project october/october myoctober`
Results in the output:
```
Installing october/october (v1.0.434)
... good output showing all of the composer dependencies being installed properly without errors
> php artisan october:util set build
-
No database detected - skipping setting the build number.
> php artisan october:util set build
-
No database detected - skipping setting the build number.
> php artisan key:generate

In KeyGenerateCommand.php line 96:
                                                                               
  file_get_contents(/home/logikos/dev/lt/karenblog/.env): failed to open stre  
  am: No such file or directory                                                
                                                                               

Script php artisan key:generate handling the post-create-project-cmd event returned with error code 1
```

##### Reproduce steps
Env:
`php --version` PHP 7.0.28-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 10:44:15) ( NTS )
`composer --version` Composer version 1.5.2 2017-09-11 16:59:25
execute `composer create-project october/october myoctober`

##### October build
october/october (v1.0.434)

**Comment by LukeTowers** [comment] 2018-04-05 03:06
Duplicate of #3321 and #3419, see https://github.com/octobercms/october/issues/3419#issuecomment-369447901

**Closed by LukeTowers** 2018-04-05 03:06 UTC
