### ISSUE TITLE
Build 468 causes error

### ISSUE THREAD

**Issue by Hlusta** [octobercms/october#5235] opened 2020-08-10 11:09 UTC
- OctoberCMS Build: 468
- PHP Version: 7.1.33
- Database Engine: mysql

### Description:
After upgrade to 468 the error appears (see screenshots below for details). The cookie needs to be deleted in order to make website available again.

![Snímek obrazovky 2020-08-10 v 12 37 33](https://user-images.githubusercontent.com/2931374/89774719-aef80d00-db06-11ea-94c0-8482d78be364.png)
![Snímek obrazovky 2020-08-10 v 12 37 55](https://user-images.githubusercontent.com/2931374/89774713-ab648600-db06-11ea-9421-7b7ac5b30b25.png)

**Comment by bennothommo** [comment] 2020-08-10 12:46
@Hlusta a fix has been deployed for this, but needs to be brought into the 468 build tag. See https://github.com/octobercms/library/commit/09896978bd8b09aac20a8da70ac93c2617afa03c. In the meantime, you can either delete the cookies, or apply the fix manually into the `vendor/october/rain` folder until the tag is updated.

Duplicate of https://github.com/octobercms/october/issues/5226.

**Closed as completed by bennothommo** 2020-08-10 12:46 UTC
Labels: duplicate

**Comment by Hlusta** [comment] 2020-08-10 12:53
Thank you and I'm sorry for duplicate, did not notice... :(
