### ISSUE TITLE
Persistent List settings

### ISSUE THREAD

**Issue by karnold** [octobercms/october#617] opened 2014-09-12 19:42 UTC
From what I can tell it appears that a users configuration for a listing page (which fields to show and what order) are only preserved for the session.

Is there a way to make each users configuration remain permanent for that user?

Similarly but possibly not related.  I would like to be able to do the same thing with the dashboard so that users can have individually customized admin dashboards.

**Comment by daftspunk** [comment] 2016-08-13 01:57
Further to this, we would need some way to reset it.

**Comment by geoffbeaumont** [comment] 2017-04-26 09:51
+1

This is something we're getting complaints about from users - they get the lists set up nicely for the tasks they're doing, and when they come back in the morning they've all reset to default. Account level persistence would be a big improvement.

I'm not convinced a reset facility is necessary? The user can just going into the list settings / reorder columns as they need. At least for our use case this would be fine. A reset would only need to delete any custom configuration though, so I guess not a big deal to implement.

**Comment by LukeTowers** [comment] 2017-04-26 16:41
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by daftspunk** [comment] 2017-05-14 05:11
This will be one of the first cabs off the rank due to its age.

**Comment by lthurston** [comment] 2017-09-21 22:14
Per my communication with @LukeTowers in Slack, I'm mentioning a related "bug" that might be fit under the umbrella of this issue.

The problem is this: backend list views return to the first results page after editing any record.

Steps to reproduce:

1) navigate to a list of records with more than one page;
2) go to page 2;
3) edit a record;
4) click "cancel";
5) you're on page 1 again

**Comment by LukeTowers** [comment] 2019-10-21 00:35
Fixed in #4360. References #4357

**Closed by LukeTowers** 2019-10-21 00:35 UTC
Labels: Priority: Medium, Status: Accepted, Status: Archived, Type: Enhancement
