### ISSUE TITLE
file_put_contents(): Exclusive locks are not supported for this stream 

### ISSUE THREAD

**Issue by daveharrisonnet** [octobercms/october#969] opened 2015-02-26 20:28 UTC
Following clean install on vidacloud I got this error. Their support guys said that exclusive locking would ot work on their cloud. So we removed Locks from the function, but need to know if they are required for everything to work. as the CMS now outputs nothing in the content area. I only get menus. It may be a different issue but it may be related? 

Might it make sense to include this as part of config so we can turn on locking if hosting environment allows it and off if not. I don;t think locking was included in beta version, so its new feature that has broken RC on cloud hosting

/var/sites/m/mrmcontracts.com/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php
        line 74

Type
> ------- Undefined Exception -------- ErrorException * @param string $contents * @param bool $lock * @return int */ public function put($path, $contents, $lock = false) { return file_put_contents($path, $contents, $lock ? LOCK_EX : 0); } /** * Prepend to a file. * * @param string $path Stack trace -------- # Called Code Document Line 8 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(…) 7 file_put_contents(…) /vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php 74 6 Illuminate\Filesystem\Filesystem->put(…) /vendor/october/rain/src/Filesystem/Filesystem.php 189 5 October\Rain\Filesystem\Filesystem->put(…) /vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php 70 4 Illuminate\Session\FileSessionHandler->write(…) /vendor/laravel/framework/src/Illuminate/Session/Store.php 255 3 Illuminate\Session\Store->save() /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php 89 2 Illuminate\Session\Middleware\StartSession->terminate(…) /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php 129 1 Illuminate\Foundation\Http\Kernel->terminate(…) /index.php 48

**Comment by daftspunk** [comment] 2015-02-26 21:25
This is probably the result of Laravel 5, sometimes their reasons are not clear. Perhaps we should disable it.

**Comment by daveharrisonnet** [comment] 2015-02-26 22:22
So removing the lock in the code (which I did) wouldn't be responsible for me not seeing anything in content area of CMS?? For some reason any page using the code console, e.g editing pages, partials, content and many settings, doesn't show in the CMS I just see menus top and left? Any idea. Should I post this elsewhere?

**Comment by daveharrisonnet** [comment] 2015-02-26 22:23
I'm goina try a clean install of RC on MAMP OSX to see if the same issue arises or if it is peculiar to cloud hosting ( I assume it is, but I'll check and also see if i get the problem with my content area on CMS)

**Comment by daveharrisonnet** [comment] 2015-02-26 22:54
OK Have done a clean install of RC on MAMP and m not expereincing the same issue as i do on the RC install on vidahost cloud. I'll look into this a bit more and report back. Some kind of issue/conflict on cloud host must be messing up the interface

**Comment by daftspunk** [comment] 2015-02-27 23:43
I have looked in to this further, the L5 Filesystem class does not use exclusive locking by default. However the introduce Storage system (for CDN) called Flysystem appears to use it.

Can you please add more detail?

- **Bug summary**: Make sure your summary reflects what the problem is and where it is.

- **Request location**: Enter the URL where this bug occurs, if applicable.

- **Reproduce steps**: Clearly mention the steps to reproduce the bug.

- **Expected result**: How OctoberCMS should behave on above mentioned steps.

- **Actual result**: What is the actual result on running above steps i.e. the bug behavior - **include any error messages**.

**Comment by daveharrisonnet** [comment] 2015-02-28 03:26
Sorry I thought I had provided all the info...apologies. here is the full detail

    Bug summary: Following clean install of RC on vidahost cloud servers, I immediately get errors on page (all pages but initially the dashboard of CMS and also ALL frontend pages, which then prevents rest of page rendering completely causing varouos layout CSS issues etc)

    Request location: All Pages following, clean install. (Both CMS backend and frontend pages display the error, except login page)

    Reproduce steps: Run install, navigate to backend, login, error appears immediately.

    Expected result: Should be presented with interface of CMS.

    Actual result: Get partially rendered CMS interface and error message as follows

file_put_contents(): Exclusive locks are not supported for this stream

/var/sites/m/mrmcontracts.com/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php
line 74

IN order to prevent the error the hosting support guys suggested removing the reference to , $lock ? LOCK_EX : 0); } from the function on line 74 in above named file. I did this and the error is no longer thrown, however I wondered if the locks are required to make other things work properly?

**Comment by Kpjackson27** [comment] 2015-03-16 03:42
Getting this same error, but it is not being fixed by removing the reference to $lock ? LOCK_EX : 0

This is the error message: 
ErrorException in Filesystem.php line 75:
file_put_contents(/var/www/html/storage/cms/disabled.json): failed to open stream: Permission denied

Steps:

Reproduce Steps: Follow update instructions at octobercms.com/beta and navigate to backend

Expected Results: Should be presented with the Backend of the CMS

Actual Result: 
ErrorException in Filesystem.php line 75:
file_put_contents(/var/www/html/storage/cms/disabled.json): failed to open stream: Permission denied
in Filesystem.php line 75
at HandleExceptions->handleError('2', 'file_put_contents(/var/www/html/storage/cms/disabled.json): failed to open stream: Permission denied', '/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php', '75', array('path' => '/var/www/html/storage/cms/disabled.json', 'contents' => '[]', 'lock' => false))
at file_put_contents('/var/www/html/storage/cms/disabled.json', '[]', '0') in Filesystem.php line 75
at Filesystem->put('/var/www/html/storage/cms/disabled.json', '[]', false) in Filesystem.php line 189
at Filesystem->put('/var/www/html/storage/cms/disabled.json', '[]') in Facade.php line 213
at Facade::__callStatic('put', array('/var/www/html/storage/cms/disabled.json', '[]')) in PluginManager.php line 459
at File::put('/var/www/html/storage/cms/disabled.json', '[]') in PluginManager.php line 459
at PluginManager->writeDisabled() in PluginManager.php line 436
at PluginManager->loadDisabled() in PluginManager.php line 71
at PluginManager->init() in Singleton.php line 33
at PluginManager->__construct() in Singleton.php line 25
at PluginManager::instance() in ServiceProvider.php line 60
at ServiceProvider->register() in Application.php line 463
at Application->register(object(ServiceProvider)) in ProviderRepository.php line 75
at ProviderRepository->load(array('Illuminate\Bus\BusServiceProvider', 'Illuminate\Cache\CacheServiceProvider', 'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider', 'Illuminate\Routing\ControllerServiceProvider', 'Illuminate\Cookie\CookieServiceProvider', 'Illuminate\Encryption\EncryptionServiceProvider', 'Illuminate\Foundation\Providers\FoundationServiceProvider', 'Illuminate\Hashing\HashServiceProvider', 'Illuminate\Pagination\PaginationServiceProvider', 'Illuminate\Pipeline\PipelineServiceProvider', 'Illuminate\Queue\QueueServiceProvider', 'Illuminate\Redis\RedisServiceProvider', 'Illuminate\Session\SessionServiceProvider', 'Illuminate\Validation\ValidationServiceProvider', 'Illuminate\View\ViewServiceProvider', 'October\Rain\Foundation\Providers\ArtisanServiceProvider', 'October\Rain\Database\DatabaseServiceProvider', 'October\Rain\Filesystem\FilesystemServiceProvider', 'October\Rain\Html\HtmlServiceProvider', 'October\Rain\Html\UrlServiceProvider', 'October\Rain\Network\NetworkServiceProvider', 'October\Rain\Scaffold\ScaffoldServiceProvider', 'October\Rain\Flash\FlashServiceProvider', 'October\Rain\Mail\MailServiceProvider', 'October\Rain\Parse\ParseServiceProvider', 'System\ServiceProvider')) in Application.php line 439
at Application->registerConfiguredProviders() in RegisterProviders.php line 15
at RegisterProviders->bootstrap(object(Application)) in Application.php line 167
at Application->bootstrapWith(array('October\Rain\Foundation\Bootstrap\RegisterClassLoader', 'Illuminate\Foundation\Bootstrap\DetectEnvironment', 'October\Rain\Foundation\Bootstrap\LoadConfiguration', 'October\Rain\Foundation\Bootstrap\LoadTranslation', 'October\Rain\Foundation\Bootstrap\ConfigureLogging', 'Illuminate\Foundation\Bootstrap\HandleExceptions', 'October\Rain\Foundation\Bootstrap\RegisterOctober', 'Illuminate\Foundation\Bootstrap\RegisterFacades', 'Illuminate\Foundation\Bootstrap\RegisterProviders', 'Illuminate\Foundation\Bootstrap\BootProviders')) in Kernel.php line 195
at Kernel->bootstrap() in Kernel.php line 106
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 84
at Kernel->handle(object(Request)) in index.php line 37

**Comment by pederwessel** [comment] 2015-03-20 14:37
Experiencing same issue. Removing $lock does not feel to be the correct way to handle the situation. Other suggestions?

**Comment by daveharrisonnet** [comment] 2015-03-20 14:52
Seems to be an issue/restriction with cloud/shared hosting. You have option
of hosting site on dedicated server??

**Comment by pederwessel** [comment] 2015-03-20 15:34
Thanks Dave. For now – not. Using tsohost.co.uk. But will reach out to them and see if they have a solution.

 

Thanks again for your quick response – wishing you a great weekend!

**Comment by daveharrisonnet** [comment] 2015-03-20 17:50
Hey Peder
    
    I'm using vidahost who I think are the same hosting company?
    They told me that it was an issue with their cloud which wasn't
    compatible with locking
    
    :)
    Have a good one
    D
    
    On 20/03/2015 15:34, Peder Wessel
      wrote:
    
    Thanks Dave. For now – not. Using tsohost.co.uk. But
      will reach out to them and see if they have a solution.
      
      
      
      Thanks again for your quick response – wishing you a great
      weekend!

**Comment by anvarstudios** [comment] 2015-03-22 20:02
I resolved wiht comand php artisan cache:clear

**Comment by ganey** [comment] 2015-04-14 09:00
I get this on 4.2.17 locally, rolling back to 4.2.16 fixes the issue

**Comment by LaravelNick** [comment] 2015-04-24 13:41
Did anyone manage to find a solution to this.

I'm experiencing the same problem with a fresh install of October on TSOHost.

Changing line 74 of Filesystem.php fixed the problem in one area of the CMS, not other areas. For instance, changing the logged in user's Avatar throws the following exception, as does using the new Media manager facility.

Error uploading file: file_put_contents(): Exclusive locks are not supported for this stream

Obviously a bit of a showstopper at the moment, so I would be grateful for any help.

Is the problem specific to TSOHost ?

**Comment by pederwessel** [comment] 2015-04-24 15:10
To my understanding the problem is related to that TSOHost has decided to
not allow exclusive locks (some web hosts do). Perhaps TSOHost are able to
tell you which file you would need to update to allow the
file_put_contents() to work?

I feel your frustration - so far I have only encountered the filesystem.php
and after updating it my L5 runs smoohtly on TSOHost.

Best regards,
Peder

2015-04-24 9:41 GMT-04:00 LaravelNick <notifications@github.com>:

**Comment by LaravelNick** [comment] 2015-04-24 15:31
Hi Peder,

Yes, Adam at TSOHost changed line 74 of Filesystem.php which fixed the problem within one part of the CMS, but it's still throwing an exception whilst trying to upload a file via the Media Library or changing the logged in Admin's avatar.

Very frustrating and a bit of a showstopper. Other than thatm L5 runs fine on TSOHost.

**Comment by daftspunk** [comment] 2015-05-09 03:43
None of this makes any sense, in both instances

* October\Rain\Filesystem\Filesystem::put()
* Illuminate\Filesystem\Filesystem::put()

The third argument `$lock` is set to `FALSE` meaning "Do not use exclusive locks". The only reason that October would use them is if the third argument was TRUE, which in October's code base is not the case.

This leads me to believe it is a problem with the latest versions of Laravel, not October.

According to [this post](https://laracasts.com/discuss/channels/general-discussion/l5-new-install-error) you need to disable file based sessions. This is a potential area where the third argument would be set to TRUE, thereby enabling exclusive locks.

At any rate, this needs to be reported with Laravel as this is the root cause.

**Closed by daftspunk** 2015-05-09 03:43 UTC
Labels: missing detail, unconfirmed bug

**Comment by daveharrisonnet** [comment] 2015-05-17 23:15
So this has raised its ugly head again!. Just noticed my website started throwing error and complaining about exclusive locks. i edited the code in filesystem.php to following
return file_put_contents($path, $contents, $lock ? LOCK_SH : 0);

**Comment by hasangilak** [comment] 2016-01-11 20:54
this package may help https://github.com/hasangilak/NoLock

**Comment by shoguniphicus** [comment] 2016-09-09 06:23
I had this issue on Digital Ocean's droplet and not on my local virtual server from time to time. cache:clear does clean up the issue for a while before it comes back again when I tried to access /backend. Changing to Database for Cache seems to make the issue go away.

At the very least this issue doesn't affect frontend at all. Only happens when trying to access /backend

**Comment by gitressa** [comment] 2017-05-28 11:09
I am also getting this error on a fresh install, using ScotchBox https://github.com/scotch-io/scotch-box. Clearing cache with `php artisan cache:clear` did not solve it, it hangs and then I get this message:

```
Error

We're sorry, but an unhandled error occurred. Please see the details below.
file_put_contents(): Exclusive locks are not supported for this stream

/var/www/public/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php line 81

    Type

    Undefined
    Exception

    ErrorException
    
     * @param  string  $contents
     * @param  bool  $lock
     * @return int
     */
    public function put($path, $contents, $lock = false)
    {
        return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    }
  
    /**
     * Prepend to a file.
     *
     * @param  string  $path
Stack trace
#   Called Code     Document    Line
6   file_put_contents(…)    ~/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php     81
5   Illuminate\Filesystem\Filesystem->put(…)    ~/vendor/october/rain/src/Filesystem/Filesystem.php     200
4   October\Rain\Filesystem\Filesystem->put(…)  ~/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php    83
3   Illuminate\Session\FileSessionHandler->write(…)     ~/vendor/laravel/framework/src/Illuminate/Session/Store.php     262
2   Illuminate\Session\Store->save()    ~/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php   88
1   Illuminate\Session\Middleware\StartSession->terminate(…)    ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php    145
0   Illuminate\Foundation\Http\Kernel->terminate(…)     ~/index.php     48
```

**Comment by gitressa** [comment] 2017-05-28 11:58
I had a read at https://laracasts.com/discuss/channels/general-discussion/l5-new-install-error and indeed after disabling NFS in my Vagrantfile, the error is gone: 
```
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    # config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
```

**Comment by mikestratton** [comment] 2017-07-06 04:55
I found the problem to be the result of not having correct database tables installed. I resolved it with: php artisan migrate
