### ISSUE TITLE
IE (11) bug in AJAX data attribute framework

### ISSUE THREAD

**Issue by getrightnl** [octobercms/october#2890] opened 2017-05-24 13:36 UTC
##### Expected behavior
Using the ajax extra_framework for updating some values with the data attributes syntax. In every browser it is working except for IE 11.

##### Actual behavior
IE 11 doesn't update and gives an error in the framework.js file on line 414, column 13. 

```
Error parsing the data-request-update attribute value. SyntaxError: Multiple definitions of a property not allowed in strict mode
```
Code at fault:
```js
function paramToObj(name, value) {
        if (value === undefined) value = ''
        if (typeof value == 'object') return value

        try {
            return JSON.parse(JSON.stringify(eval("({" + value + "})")))
        }
        catch (e) {
            throw new Error('Error parsing the '+name+' attribute value. '+e)
        }
    }
```

##### Reproduce steps
Add the data-request api method and use IE 11.0.9600.18638. This will work in every browser except IE

##### October build
v1.0.419

It is possible to use the javascript api for Ajax, but would be nice if the data api works for IE

**Comment by jimcottrell** [comment] 2017-06-01 23:50
Thought I'd see if I can replicate.

Not to sound overly critical, but if the error message specifically mentions the `data-request-update` attribute, you should really include that attribute's value (or a suitably sanitized version that still triggers the bug) in a bug report to help others reproduce.

That said, I can confirm that this error can be triggered in IE11 by specifying a partial more than once in `data-request-update`, which would of course be duplicate property definitions on the parsed object like the error message says.  So are you trying to load the same partial to multiple elements, @getrightnl?  Or is there another possibility I'm not seeing?

I imagine loading the same partial into multiple elements is uncommon, but perhaps the AJAX framework functionality could support this use case via an optional array of selectors.

**Comment by LukeTowers** [comment] 2017-10-19 08:24
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-19 08:24 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
