### ISSUE TITLE
Imposible to use sorting in the relations

### ISSUE THREAD

**Issue by host138** [octobercms/october#4439] opened 2019-07-08 12:18 UTC
- OctoberCMS Build: 455
- PHP Version: 7.3.4
- Database Engine: Mysql 5.7.23
- Plugins Installed: October.Test-v1.0.1

### Description:
Sorting doesn't work at all

### Steps To Reproduce:
You can see in the October Test plugin. 
Users -> NEO -> In the "Standard" tab "Roles" section.  For example, try to sort by ID column.

**Comment by w20k** [comment] 2019-07-10 08:17
Confirmed - a bug, will be looking at it on weekends.

**Comment by bennothommo** [comment] 2019-12-02 01:00
@host138 I've done a test on this, and found sorting doesn't work when the relation has a specified order clause in its definition.

With your example above in the Test plugin, the User model has a `belongsTo` definition with the Role model which has `order` set to the `name` field. Because of this, when the Lists widget tries to re-order the records based on the column name picked, the name ordering is applied first. When you remove this `order` definition from the relation, ordering in the lists works as expected.

**Comment by bennothommo** [comment] 2019-12-02 01:28
Fixed by 9f8d8ec9fabad06e0eb4b222611910e608729074.

**Closed** 2019-12-02 01:29 UTC
Labels: Status: Completed, Type: Bug
