### ISSUE TITLE
Problem when trying to detach a a belongs-to-many relationship(not working on create model)?

### ISSUE THREAD

**Issue by mirenibg** [octobercms/october#1150] opened 2015-05-19 11:14 UTC
I followed the Back-end relations tutorial(https://vimeo.com/123489421) because I have very similar relationships structure but when I installed the https://github.com/daftspunk/oc-crm-plugin plugin it appears the same issue  - the contacts cannot be removed when creating an opportunity.
I checked the onRelationManageRemove() function in the \Backend\Behaviours\RelationController, but it appears that it's removing only the db relation and does not unbind the deferred relations from the main model.

I also noticed that when I create one after another opportunity with a particular contact attached - on the 3rd attempt to create a opportunity with the same contact the contacts table view appends 2 or more duplicates of the same contact.
![screen shot 2015-05-19 at 10 07 32 am](https://cloud.githubusercontent.com/assets/1543162/7701580/3cd1ffb8-fe31-11e4-9e81-c51aafe33e55.png)

**Comment by mplodowski** [comment] 2015-05-28 11:18
I experienced the same bug. The remove button will not remove binding in **create** context. Also the added position is not removed in manage list section, so you can still add the same position twice. 

Everything works fine in **update** context.

CRM plugin is an example of this bug.

**Comment by IcedLime** [comment] 2015-09-18 15:45
I have the same issues
Like : https://github.com/octobercms/october/issues/1411

**Comment by ekrokowski** [comment] 2016-02-12 20:39
I also got this bug, however I implemented an temporary fix for this. 

The Problem is that the RelationController calls the detach() method from Laravels BelongsToMany class. That Method has no deferred bindings, therefore this actually can't work as needed. The remove() Method of October\Rain\Database\Relations\BelongsToMany needs to be called which has the needed wrapper for deferred bindings.

file: /modules/backend/behaviors/RelationController.php
Original content:
https://github.com/octobercms/october/blob/master/modules/backend/behaviors/RelationController.php#L1103

The workaround would be (**The workaround will be overwritten by every october update!**):

    public function onRelationManageRemove()
    {
        $this->beforeAjax();

        $recordId = post('record_id');

		$sessionKey = $this->deferredBinding ? $this->relationGetSessionKey() : null;

        /*
         * Remove
         */
        if ($this->viewMode == 'multi') {

            $checkedIds = $recordId ? [$recordId] : post('checked');

            if (is_array($checkedIds)) {

                if ($this->relationType == 'belongsToMany') {
					$foreignKeyName = $this->relationModel->getKeyName();

					$models = $this->relationModel->whereIn($foreignKeyName, $checkedIds)->get();
					foreach ($models as $model) {
						$this->relationObject->remove($model, $sessionKey);
					}
                }

**Comment by daftspunk** [comment] 2016-08-13 02:41
Thanks @ekrokowski, this would have been picked up sooner with a Pull Request =)

**Closed by daftspunk** 2016-08-13 02:41 UTC
Labels: Priority: Medium, Status: Accepted, Type: Bug
