### ISSUE TITLE
when system Ui lib (storm) is minified, it has textarea related error, and textarea treat next html as its value

### ISSUE THREAD

**Issue by hardik-satasiya** [octobercms/october#5337] opened 2020-10-29 07:52 UTC
- OctoberCMS Build: 469 
- PHP Version: 7.2

### Description:
- When System Ui lib is minified its converting This
````
<textarea class="form-control size-small field-textarea" name="name"></textarea>  
````
> To this
````
<textarea class="form-control size-small field-textarea" name="name" /> 
````
Because of that next HTML content is treated as its text area's value

### Solution
Minification algorithm should spare empty text area to converting from <textarea></textarea> to this <textarea />
I am sorry I am not sure how can I do this, so its in issue list otherwise it will be in PR list 😄 

Actual code
![actual_code](https://user-images.githubusercontent.com/2410795/97540346-8686fd00-19e9-11eb-9016-f9295be32455.png)

Why this error
![why_error](https://user-images.githubusercontent.com/2410795/97540341-8424a300-19e9-11eb-82e7-4df281c8edfc.png)

### Steps To Reproduce:

> In component add `defineProperties` and add `stringList` type item
````
public function defineProperties()
{
        return [
            'mail_recipients' => [
                'title'             => 'Title',
                'description'       => 'Description',
                'type'              => 'stringList',
                'showExternalParam' => false
            ],
        ];
}
````
![component_props](https://user-images.githubusercontent.com/2410795/97540250-622b2080-19e9-11eb-8b54-3b76d4296797.png)

> Add this component to page and try to edit this property

![inspector](https://user-images.githubusercontent.com/2410795/97540360-8be44780-19e9-11eb-8a0e-3e1d136c42b8.png)

![Bug](https://user-images.githubusercontent.com/2410795/97540365-8dae0b00-19e9-11eb-889f-40a206641c76.png)

**Comment by bennothommo** [comment] 2020-10-29 07:57
Duplicate of #5222.

You can either upgrade October CMS to 1.1.0, or you can run the CLI command `php artisan october:util compile assets` within your site directory and then refresh your browser cache and it should then be fixed.

**Closed as completed by bennothommo** 2020-10-29 07:57 UTC
Labels: duplicate

**Comment by hardik-satasiya** [comment] 2020-10-29 08:02
@bennothommo thanks for information recompiling assets  fixed my issue 👍 
`php artisan october:util compile assets`
