### ISSUE TITLE
Fix the issue with a huge number of the filtering items

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#5581] opened 2021-04-26 17:53 UTC
If a filter has 200+ items, not all of them are rendered in the dropdown list.

![image](https://user-images.githubusercontent.com/196445/116127329-5c7c7200-a6d0-11eb-9818-243ad9ab706a.png)

Moreover, search over this field doesn't work for the not rendered items, the filtering doesn't work correctly, and the apply button doesn't appear.

![image](https://user-images.githubusercontent.com/196445/116128174-563ac580-a6d1-11eb-9883-105532be1094.png)

October build is 431.

**Comment by danielbidala** [comment] 2021-04-27 07:34
@lautsevich this is a long-standing issue. I've added a pull request to solve this but it isn't merged yet. See #5470 
By the way build 431 is outdated.

**Comment by daftspunk** [comment] 2021-04-27 08:33
This list filter mode was never designed to handle a heavy number of items. A new filter scope was to be developed that would allow a greater number of records and filtering, but it never came to pass. Now that we are in a better position to improve the platform, we can get a revamp of it added to the roadmap

@danielbidala It looks like 200+ isn't even close to hitting the artificial 500 query limit, is there some other limitation causing it to fail?

**Comment by lautsevich** [comment] 2021-04-27 09:58
@daftspunk, do you plan to fix this in v2 or we can expect this in v1 too?

**Comment by daftspunk** [comment] 2021-04-27 22:51
@lautsevich The revamp would arrive in v2 and it might be some time, I suggest commenting out this line for the time being..

Found here: https://github.com/octobercms/october/commit/b53015e020e522f512c85b7bf441207308900b46

**Comment by lautsevich** [comment] 2021-04-28 10:32
> @lautsevich The fix would arrive in v2 and it might be some time, I suggest commenting out this line for the time being

This doesn't work for us.

And what is the chance to merge this PR #5470?

**Comment by daftspunk** [comment] 2021-04-28 23:19
Tested this and it works. Backported to 1.0 in 2f32fef551f94cf6d3246c7e08b4eb3618232e67

@lautsevich That should sort it out, we've tested this with 600 items. Please close issue once confirmed

@danielbidala Beautiful work, thank you

Also included in v2.0 + v1.1

**Closed as completed** 2021-04-29 21:45 UTC
