### ISSUE TITLE
Error after update to 446 & clean install

### ISSUE THREAD

**Issue by re-sign** [octobercms/october#4036] opened 2019-01-04 17:08 UTC
![october_install_bug](https://user-images.githubusercontent.com/10549482/50700328-48be2500-105b-11e9-911f-c51caee33b79.PNG)

Please check install screen, Some error after update from 443 to 446 on another website.
PHP 7.2.13+MariaDB-10.2.16+ubuntu16.04

![october_update_error](https://user-images.githubusercontent.com/10549482/50700734-5e801a00-105c-11e9-9fc3-1ace409d288f.PNG)

**Comment by re-sign** [comment] 2019-01-04 19:23
Downgrade to build 443. Is working correctly on these servers.

**Comment by w20k** [comment] 2019-01-06 17:04
@re-sign, could you past the log as a text, and remove personal information? Couldn't reproduce, yet, the clean install.

**Comment by LukeTowers** [comment] 2019-01-07 00:02
@re-sign did you add any plugins or themes with the installer?

**Comment by re-sign** [comment] 2019-01-07 12:04
@w20k Unfortunately, there is no installation log, as I had to immediately return to the previous working version of the site.
@LukeTowers No, the installation was clean from scratch.

**Comment by chrisvidal** [comment] 2019-01-08 08:38
Hi,
I am having the same issue while updating from 443 to 446.

```php
08-Jan-2019 08:30:51 UTC] PHP Fatal error:  Class Illuminate\Database\Eloquent\Collection contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Queue\QueueableCollection::getQueueableRelations) in /Users/toto/Sites/oc-vodka/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php on line 11
[08-Jan-2019 08:30:51 UTC] PHP Fatal error:  Uncaught Error: Class 'October\Rain\Database\Collection' not found in /Users/toto/Sites/oc-vodka/vendor/october/rain/src/Database/Model.php:608
Stack trace:
#0 /Users/toto/Sites/oc-vodka/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(261): October\Rain\Database\Model->newCollection(Array)
#1 /Users/toto/Sites/oc-vodka/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1477): Illuminate\Database\Eloquent\Builder->hydrate(Array)
#2 /Users/toto/Sites/oc-vodka/vendor/october/rain/src/Extension/ExtendableTrait.php(411): Illuminate\Database\Eloquent\Model->__call('hydrate', Array)
#3 /Users/toto/Sites/oc-vodka/vendor/october/rain/src/Database/Model.php(635): October\Rain\Database\Model->extendableCall('hydrate', Array)
#4 /Users/toto/Sites/oc-vodka/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(481): October\Rain\Database\Model->__call('hydrate', Array)
#5 /Users/toto/Sites/oc- in /Users/toto/Sites/oc-vodka/vendor/october/rain/src/Database/Model.php on line 608
```

**Comment by w20k** [comment] 2019-01-08 08:44
@chrisvidal, have you tried copy-past your plugins in the subdir and re-paste them one-by-one? Or is this the issue with the clean install?

**Comment by chrisvidal** [comment] 2019-01-08 08:53
Issue is showing up after performing an upgrade on an existing project hence with existing plugins.
Let me try to remove plugin by plugin to check that.

**Comment by chrisvidal** [comment] 2019-01-08 09:00
Well, it seems that the issue is coming from one on my own developed plugins. Not sure what and why.
After removing it from the plugins folder, OC is still in version 443 and the 'check for updates' buttons does not work anymore.

**Comment by w20k** [comment] 2019-01-08 09:39
@chrisvidal, don't forget that Laravel framework do tend to remove/add methods as a fix within the `PATCH` version -> 5.6.**x**

**Comment by chrisvidal** [comment] 2019-01-08 09:47
thanks @w20k 
I am still confused, as in:
- which Laravel version is running OC 446? is it still Laravel 5.5 LTS ?
- which patch notes are you referring to? I checked the latest OC Release notes and no mention of anything around a new Laravel version

**Comment by w20k** [comment] 2019-01-08 10:04
@chrisvidal, 
- Yes, OC will still run with 5.5.x LTS.
- I was referring to Laravel patch notes, or changes that were made.

Here you go latest 5.6.x added new method, which is not present in 5.5.x QueueableCollection.class:
![screenshot 2019-01-08 at 12 03 20](https://user-images.githubusercontent.com/1053320/50823798-7a760b00-133d-11e9-8c2e-a432989c284d.png)

**Comment by chrisvidal** [comment] 2019-01-08 10:21
ok thanks @w20k 

so I don't understand why it does not work anymore and this exception is raised since nobody upgraded to Laravel 5.6.x

**Comment by w20k** [comment] 2019-01-08 10:30
@chrisvidal, the difference in release dates? Or others dev tend to not use 5.6.x Laravel with OC 😄

**Comment by chrisvidal** [comment] 2019-01-08 11:53
I don't have any composer.json for Octobercms, it is installed with the wizard.
in the vendor folder from OC, there is a Laravel folder, but I can't seem to find the Laravel version

**Comment by w20k** [comment] 2019-01-08 12:06
@chrisvidal, how did you install/add - LaravelShoppingCart?
Your issue is not with OctoberCMS, but plugins that use Laravel higher than 5.5.x.

See composer for LaravelShop which use 5.1.x - 5.6.x https://github.com/Crinsane/LaravelShoppingcart/blob/master/composer.json -> should be only 5.5.x.
If you have a root composer use it there (like: `plugins/author/name/composer.json`).

**Comment by chrisvidal** [comment] 2019-01-09 08:30
thanks @w20k for your help
so basically I am screwed :) I can't modify their composer.json.
So I had to go with a previous version 2.4 and it seems to be working.
Still in test though

**Comment by LukeTowers** [comment] 2019-01-09 16:39
@chrisvidal you should be able to use the `replace` property in your composer to specify illuminate/support 5.5: https://getcomposer.org/doc/04-schema.md#replace. This should lock their dependencies to 5.5 and prevent the unnecessary inclusion of the illuminate/support package within your plugin. This is the method used by the marketplace build server.

**Comment by chrisvidal** [comment] 2019-01-10 03:36
Thanks @LukeTowers 
that is much cleaner way to proceed indeed. thanks, let me try this

**Comment by LukeTowers** [comment] 2019-01-27 18:00
@pierzo change your composer to use these:
```json
"october/rain": "v1.0.443 as 1.0",
"october/system": "v1.0.443",
"october/backend": "v1.0.443",
"october/cms": "v1.0.443",
```

**Comment by LukeTowers** [comment] 2019-07-26 08:10
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Closed by LukeTowers** 2019-07-26 08:10 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug

**Comment by jackkjohn** [comment] 2023-03-01 18:09
I recently started doing IT and since it used to be just a hobby, now I want it to be profitable. I am already improving my skills in development sites, testing, even writing https://www.businessmole.com/main-role-of-manual-testing-in-software-development/ articles myself sometimes. But I still have a lot of questions. However, after reading this article, I will be able to work even more productively and my goals will be achieved faster.
