### ISSUE TITLE
Adding MainMenuItem(s) without sideMenu fails 

### ISSUE THREAD

**Issue by CSNWEB** [octobercms/october#2777] opened 2017-03-24 14:47 UTC
##### Expected behavior
If an existing item is edited the exiting sideMenu should be taken if a new item is added it should just have no sideMenu.

##### Actual behavior
This exception is thrown:
Type error: Argument 4 passed to Backend\Classes\NavigationManager::addSideMenuItem() must be of the type array, object given, called in /var/www/html/services/internal-october/modules/backend/Classes/NavigationManager.php on line 250

##### Reproduce steps
This is the code snippet which produces the error:
`        
Event::listen('backend.menu.extendItems', function ($manager) {
            $manager->addMainMenuItems('Renatio.DynamicPDF', [
               'dynamicpdf' => [
                   'label' => 'CoE',
                   'order' => 570
               ]
 ]);
}
`

##### October build
Build 407

I also added a comment to the commit where this error was introduced (at least I think so)
https://github.com/octobercms/october/commit/462c9cd4e822cb9193a0b4f89f66a82a126fb53d

**Comment by LukeTowers** [comment] 2017-03-24 15:02
Duplicate of #2757

**Closed by LukeTowers** 2017-03-24 15:02 UTC

**Comment by LukeTowers** [comment] 2017-03-24 15:06
@CSNWEB Please let me know if https://github.com/octobercms/october/commit/d1c9b1a6f1511824cbc74c7cd31926cace58fb9c solved your problem.

**Comment by CSNWEB** [comment] 2017-03-24 15:58
@LukeTowers yes it does thanks a lot :)! Do you already know when the next release happens?

**Comment by LukeTowers** [comment] 2017-03-24 16:09
Next dev release will be whenever @daftspunk pushes a tag, the next stable release should be coming shortly, it's been a couple months or so since the last one. Lots of testing required before stable gets bumped generally though

**Comment by daftspunk** [comment] 2017-03-31 01:32
Fixed in Build 408+

**Comment by CSNWEB** [comment] 2017-03-31 17:23
Thanks 👍

**Comment by LukeTowers** [comment] 2017-04-03 13:43
A [release note](http://octobercms.com/support/article/rn-6) has been created to document this.
