### ISSUE TITLE
User model fails on validation(password confirmation missmatch) when it's not

### ISSUE THREAD

**Issue by RomainMazB** [octobercms/october#5347] opened 2020-11-07 23:05 UTC
- OctoberCMS Build: 469
- PHP Version: 7.4.12
- Database Engine: MySQL
- Plugins Installed: none

### Description:
Hi,
I'm trying to create a backend User using the BackendAuth class as [described in the documentation](https://octobercms.com/docs/backend/users#backend-auth-facadelaravel ), or directly from the User model, but the validation fails on password confirmation missmatch.

Creating User from the backend Administration interface works correctly. Can't tell what's going on here...

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/53976837/98453095-ae96fe80-2155-11eb-86c1-4a24c995d298.png)

**Comment by LukeTowers** [comment] 2020-11-07 23:06
Duplicate of #5313. Potentially fixed by https://github.com/octobercms/library/pull/533

**Closed as completed by LukeTowers** 2020-11-07 23:06 UTC
Labels: Type: Bug, duplicate
