### ISSUE TITLE
Sortables Trait does not work when sort_order = 0

### ISSUE THREAD

**Issue by firemankurt** [octobercms/october#2957] opened 2017-07-07 03:40 UTC
##### Expected behavior
Dragging records in backend reorder page should save the order of records as displayed with new 'sort_order' values starting with 1 and throught the count of records.
##### Actual behavior
Dragging records in backend reorder page does not change 'sort_order' values when 'sort_order' = 0 in all rows.
Posted field values are :
record_ids[]:1
record_ids[]:2
record_ids[]:3
record_ids[]:4
record_ids[]:5
record_ids[]:8
record_ids[]:7
record_ids[]:6
sort_orders[]:0
sort_orders[]:0
sort_orders[]:0
sort_orders[]:0
sort_orders[]:0
sort_orders[]:0
sort_orders[]:0
sort_orders[]:0
##### Reproduce steps
- Insert several records in a sorable model. ( 8 records for my case )
- The sort_order default is 0 per schema documented here : https://octobercms.com/docs/database/traits#sortable
- open backend reorder controller page for the above model and attempt to drag and sort.

##### October build
System build 419

**Comment by LukeTowers** [comment] 2017-07-07 13:45
@firemankurt I literally just added [this to the docs](https://github.com/octobercms/docs/commit/e07d603bb0fe68d057b091990a2ae6881781d53f) yesterday 😂 

This is a duplicate of https://github.com/octobercms/october/issues/1923

**Closed by LukeTowers** 2017-07-07 13:45 UTC
