### ISSUE TITLE
Repeater Issue with translated WYSIWYG Editor

### ISSUE THREAD

**Issue by jo-bitcraft** [octobercms/october#5394] opened 2020-12-09 15:20 UTC
- OctoberCMS Build: 469
- PHP Version: 7.4
- Database Engine: MySQL
- Plugins Installed: Rainlab Translate Plugin

### Description:

If you use a translated WYSIWYG Editor in a repeater and copy&paste content i.e. from Google Spreadsheet it will add html attributes like data-sheets-userformat or data-sheets-value, i.e.

`<span data-sheets-userformat="{&quot;2&quot;:513,&quot;3&quot;:{&quot;1&quot;:2,&quot;2&quot;:&quot;#,##0.0&quot;,&quot;3&quot;:1},&quot;12&quot;:0}" data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}">4,0</span>
`
Those attributes causes the repeater to stop working correctly - it won't show anything in that language anymore. With the default language it seems that it escapes those attributes.

### Steps To Reproduce:

1. make a translated repeater with a Richtext-Editor
2. copy into one translation Richtext-Editor that html content
`<span data-sheets-userformat="{&quot;2&quot;:513,&quot;3&quot;:{&quot;1&quot;:2,&quot;2&quot;:&quot;#,##0.0&quot;,&quot;3&quot;:1},&quot;12&quot;:0}" data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}">4,0</span>`

![image](https://user-images.githubusercontent.com/52261448/101648745-6e6bba00-3a3a-11eb-93bc-350b731dbe07.png)

3. save
4. ALL repeater fields for that language (if not the default) won't show up anymore (although the content is there)

When switching to a different language the input field will be completely cleared.

![image](https://user-images.githubusercontent.com/52261448/101648266-ef768180-3a39-11eb-981b-ce487519b301.png)

**Comment by mjauvin** [comment] 2020-12-09 15:26
@jo-bitcraft are you saying this only happens with RainLab.Translate in the mix?

**Comment by jo-bitcraft** [comment] 2020-12-09 15:30
@mjauvin 
yes, for all translations which are not the default language. For the default language it is kind of escaped when saving which will also be the case if there is no translation.

![image](https://user-images.githubusercontent.com/52261448/101649961-bc34f200-3a3b-11eb-9bc2-9e505123ded8.png)

**Comment by mjauvin** [comment] 2020-12-09 15:41
Ok, so maybe you opened the issue in the wrong repo?

**Comment by jo-bitcraft** [comment] 2020-12-09 15:58
@mjauvin also opened it here: https://github.com/rainlab/translate-plugin/issues/627

But I think the repeater has a problem when interpreting the "unescaped" wysiwyg value of 

`<span data-sheets-userformat="{&quot;2&quot;:513,&quot;3&quot;:{&quot;1&quot;:2,&quot;2&quot;:&quot;#,##0.0&quot;,&quot;3&quot;:1},&quot;12&quot;:0}" data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}">4,0</span>`

**Comment by mjauvin** [comment] 2020-12-09 16:04
You said above that it's escaped when saving with default language... why do you think it's not caused only by the MLRepeater formwidget code?

**Comment by jo-bitcraft** [comment] 2020-12-09 16:13
@mjauvin just had a look into the db, actually it is not escaped when saving but before outputting, cause in the db field I have the full input but not in the richtext editor (which would stop the repeater from working correctly)

![image](https://user-images.githubusercontent.com/52261448/101655130-872b9e00-3a41-11eb-8ca3-d65a087c5df6.png)

![image](https://user-images.githubusercontent.com/52261448/101655266-b2ae8880-3a41-11eb-9cdc-a37727b4d75a.png)

**Comment by mjauvin** [comment] 2020-12-10 18:19
Unless I'm mistaken, this is a duplicate of https://github.com/rainlab/translate-plugin/issues/448

**Closed as completed** 2021-02-12 00:22 UTC
Labels: Type: Unconfirmed Bug, Status: Review Needed, Status: Archived
