### ISSUE TITLE
Field option "stretch: true" causes overflow / doesn't work for rich editor

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#2303] opened 2016-08-11 09:13 UTC
##### Expected behaviour

The field option `stretch` should stretch the given form element (in this case `type: richeditor`) to match the parent's height (/stretch to the bottom of the screen). 

In normal fields:

```
fields:
    field_name:
        type: richeditor
        stretch: true
```

![octobercms-stretch-form-fireld](https://cloud.githubusercontent.com/assets/1681727/17583166/d1636ff0-5faf-11e6-8b1f-e7f850c2a384.png)

The field option `stretch` should stretch the given form element (in this case `type: richeditor`) to match the parent's height (/stretch to the bottom of the screen). 

In tabs:

```
tabs:
    fields:
        field_name:
            type: richeditor
            stretch: true
```

![octobercms-stretch-form-fireld-4](https://cloud.githubusercontent.com/assets/1681727/17583414/358a04b6-5fb1-11e6-825c-cc33eb477f30.png)
##### Actual behaviour

The field option `stretch` removes the ability to use the WYSIWYG, as the height seems to match normal inputs.

```
fields:
    field_name:
        type: richeditor
        stretch: true
```

![octobercms-stretch-form-fireld-2](https://cloud.githubusercontent.com/assets/1681727/17583234/2e074d12-5fb0-11e6-8658-d3f0ffd43c11.png)

The field option `stretch` stretches the WYSiWYG over the save/cancel buttons.

In tabs:

```
tabs:
    fields:
        field_name:
            type: richeditor
            stretch: true
```

![octobercms-stretch-form-fireld-3](https://cloud.githubusercontent.com/assets/1681727/17583426/463a9a3c-5fb1-11e6-8a06-4e1884f93a41.png)
##### Reproduce steps

in `fields.yaml`

```
fields:
    field_name:
        type: richeditor
        stretch: true

tabs:
    fields:
        field_name:
            type: richeditor
            stretch: true
```
##### October build

Build 351

**Comment by daftspunk** [comment] 2016-08-13 01:38
Confirmed this using the test plugin **models/review/fields.yaml**

```
fields:
    content:
        label: Content
        type: richeditor
        stretch: true
```

**Comment by LukeTowers** [comment] 2017-10-18 21:06
@CptMeatball is this still an issue in the latest build?

**Comment by CptMeatball** [comment] 2017-10-19 09:28
Will check today.

**Comment by CptMeatball** [comment] 2017-10-19 09:33
**Current Behavior**

![image](https://user-images.githubusercontent.com/1681727/31764262-f353454c-b4c0-11e7-9bf8-c080b7bf71b3.png)

It does stretch, but UI/UX wise it stretches a bit _too far_. A bit of `margin-bottom` should be included I guess.

**Comment by LukeTowers** [comment] 2017-10-19 14:20
@CptMeatball feel free to make a PR with the fixes. Include before and after screenshots but not the compiled assets please.

**Comment by LukeTowers** [comment] 2018-12-27 19:13
@w20k @ayumihamsaki @Teranode anyone want to try their hand at this? Note that it's tricky to fully support because form outside fields container has a height based on the content (only tabbed fields have 100% height) and stretch = height: 100% doesn't really work because it doesn't take into account any labels or previous fields that are in the same container. Stretch should stretch to fill the remaining space in my mind.

**Comment by w20k** [comment] 2018-12-27 19:49
@LukeTowers, could you example a bit more. How should `stretch` work? For example, if you have a small screen? Where half of your fields don't even fit? Should it have a min-height and max - should be dynamic, based on your screen size?

**Comment by LukeTowers** [comment] 2018-12-27 20:00
stretch should only really work on the last field in the container, and it should stretch to fit the available height. I'm fine if outside form fields still require an explicit height to be set on the outside form fields container before stretch fills the remaining height.

**Comment by ayumihamsaki** [comment] 2018-12-27 23:37
I have not looked into this properly but I would think that using `height: 100%` is not a good idea. It would be better to use `height: 100vh` and `width: 100vw` then the css can work it out from the screen size instead.

**Comment by Teranode** [comment] 2018-12-28 14:02
i have a general idea on how to fix this, but my first question would be is "layout-relative" needed on the form group?

**Comment by Teranode** [comment] 2018-12-28 14:13
If I can remove the layout-relative from the form group then we can have this:
![](https://i.imgur.com/mNbFC80.gif)

**Comment by ayumihamsaki** [comment] 2018-12-28 15:46
Not really a fan of that feature, but I am sure other people want it. Looking at the gif's it reminds me of a `textarea` and I want to ask/suggest, would it be a good idea to add a feature like `cols`, for example:

```html
<textarea cols="10">
  ..richeditor
</textarea>
```

To allow the developer to choose the `min-height`, e.g.

```
fields:
    content:
        label: Content
        type: richeditor
        stretch: true
        cols: 10
```

But change the `cols` to something like `minStrechHeight`.

```
fields:
    content:
        label: Content
        type: richeditor
        stretch: true
        minStrechHeight: 10
```

or

```
fields:
    content:
        label: Content
        type: richeditor
        stretch: true, 10
```

**Comment by LukeTowers** [comment] 2018-12-28 16:08
@Teranode the example you provided looks good, what does removing the layout-relative do? Also, if we had it stretch based on the content then it should be able to specify a maxHeight.

Here's an example of where the stretch property comes in handy:
![0notes-interface](https://user-images.githubusercontent.com/7253840/50520802-0196c980-0a88-11e9-8b84-09c35986f9b2.png)

See how the richeditor expands to fill the form space on the right? That's where it's useful

**Comment by LukeTowers** [comment] 2019-04-19 22:11
@CptMeatball could you test https://github.com/octobercms/october/pull/4016?

**Comment by ayumihamsaki** [comment] 2019-04-20 15:26
@LukeTowers I might try and test this right now. I have been waiting for this issue, as I have some plugins I built needing this feature. So I will try and test the pr today.

**Comment by ayumihamsaki** [comment] 2019-04-20 15:52
Hi that pr is not working I get the following results:

![eg](https://user-images.githubusercontent.com/17784082/56459518-a406ef80-638c-11e9-9cf3-e32a9f54ce28.png)

**Comment by LukeTowers** [comment] 2019-04-22 00:45
@ayumihamsaki feel free to help out @Teranode with making a fix

**Comment by ayumihamsaki** [comment] 2019-05-05 10:11
Hi, I have updated Modernizr, see my PR to allow support `vw` and `vh`, this may help this issue and pr, please see my commit here: https://github.com/octobercms/october/pull/4316/commits/5e5f19381457d5c9990863353db118753aafdde5

**Comment by ayumihamsaki** [comment] 2019-06-19 21:08
Was thinking, the solution is some basic maths e.g.

![d1636ff0-5faf-11e6-8b1f-e7f850c2a384](https://user-images.githubusercontent.com/17784082/59800274-14bf7f00-92de-11e9-9b91-aa6581897684.png)

1. We work out the total height of the field area on the User's device using 100vh.

2. We then use javascript to keep increasing the `height` of the `stretch box` until it hits the height limit of the `field area box`. When we start increasing the `field area box` we know that it has passed the limit for the `stretch box`.

**Comment by ayumihamsaki** [comment] 2019-07-18 07:09
Think this can be done with flexbox, here's a working example:

```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Flexbox example for stretch</title>

<style>
html,
body {
  height: 100%;
  margin: 0
}

.box {
  display: flex;
  flex-flow: column;
  height: 100%;
}

.box .row {
  border: 1px dotted grey;
}

.box .row.header {
  flex: 0 1 auto;
  /* The above is shorthand for:
  flex-grow: 0,
  flex-shrink: 1,
  flex-basis: auto
  */
}

.box .row.content {
  flex: 1 1 auto;
}

.box .row.footer {
  flex: 0 1 40px;
}	
</style>

</head>

<body>

<div class="box">
  <div class="row header">
    <p><b>header</b>
      <br />
      <br />(sized to content)</p>
  </div>
  <div class="row content">
    <p>
      <b>content</b>
      (fills remaining space)
    </p>
  </div>
  <div class="row footer">
    <p><b>footer</b> (fixed height)</p>
  </div>
</div>

</body>
</html>
```

Going to try and work on this issue at the same time, while I create the pr for this issue: https://github.com/octobercms/october/issues/4437

I will probably create a single PR for both issues - going to be writing that pr today.

**Comment by ayumihamsaki** [comment] 2019-07-19 16:07
@LukeTowers Review please!

Possible fix for this issue, however there is a big catch! The fix will only work if you do not add any fields under the stretch field.

Stretch field (with no fields below it):

![see](https://user-images.githubusercontent.com/17784082/61549276-873f8e00-aa47-11e9-9155-1c82f8c1d072.png)

Stretch field (with fields below it):

![see](https://user-images.githubusercontent.com/17784082/61549220-6840fc00-aa47-11e9-8936-1fe0f40e5a9b.png)

If you ok with this, I can add it to the pr I'm working on. Plus adds some extra notes in the doc's about this feature.

**Comment by ayumihamsaki** [comment] 2019-07-19 16:16
@LukeTowers Review please!

Possible fix for this issue, however there is a big catch! The fix will only work if you do not add any fields under the stretch field.

Stretch field (with no fields below it):

![see](https://user-images.githubusercontent.com/17784082/61549276-873f8e00-aa47-11e9-9155-1c82f8c1d072.png)

Stretch field (with fields below it):

![see](https://user-images.githubusercontent.com/17784082/61549220-6840fc00-aa47-11e9-8936-1fe0f40e5a9b.png)

If you ok with this, I can add it to the pr I'm working on. Plus adds some extra notes in the doc's about this feature.

Otherwise people can just add in custom heights to their fields.

Or you can completely change it and do what Teranode said and do this:

![68747470733a2f2f692e696d6775722e636f6d2f6d4e62464338302e676966](https://user-images.githubusercontent.com/17784082/61549816-e5b93c00-aa48-11e9-869f-18168d078e5c.gif)

**Comment by Eoler** [comment] 2019-07-19 16:47
Hmm, can we have both stretch (if last) and dynamic height (on more content) implementations?

**Comment by ayumihamsaki** [comment] 2019-07-19 17:10
@LukeTowers 

I'm thinking what @Eoler is saying and create two options called: `stretch` and `grow`.

- stretch = stretch (if last)

- grow = dynamic height (on more content)

If you and @daftspunk are happy with that. I will code that today.

**Comment by ayumihamsaki** [comment] 2019-07-19 17:14
@LukeTowers 

I'm thinking what @Eoler is saying and create two options called: `stretch` and `grow`.

- stretch = stretch (if last)

- grow = dynamic height (on more content)

If you and @daftspunk are happy with that. I will code that today.

---

Code for grow would be this:

```css
.grow .fr-wrapper {
    min-height: 100px;
    height: auto !important;
}
```

Have already tested it and works fine.

**Comment by LukeTowers** [comment] 2019-07-20 02:38
@ayumihamsaki I like the idea but `grow` isn't going to be applicable to every field type. For example, any single line text input (text, date, colour, password, number, etc) isn't going to need grow, only multiline inputs like richeditor, markdown, textarea need to support those options. Stretch can apply to slightly more (partial & hint perhaps)

**Comment by ayumihamsaki** [comment] 2019-07-20 03:42
@LukeTowers I totally get what you are saying. My only problem in the builder plugin is trying to make sure someone doesn't select Stretch and Grow at the same time. That's the reason why I put it in a dropdown menu. 

It has three options: `nothing`, `stretch` and `grow` for people to select under a dropdown name of `dynamic`.

When I was looking at the builder code, the `textarea` field was turned off for `Stretch` and I turned it on. Will double check for `markdown`.

You can see what I have done with the code so far here: https://github.com/rainlab/builder-plugin/pull/290

Please have a look and let me know.

p.s. I am stuck on the bit from getting the dropdown data and injecting either `stretch` or `grow` it into the class attirbute, I need some help from someone on that part.

**Comment by ayumihamsaki** [comment] 2019-07-20 13:04
@LukeTowers Sorry I forgot to ask you the most important thing, would you be happy with this setup:

Builder plugin to display that `grow` and `stretch` options for multiline inputs like `richeditor`, `markdown` and `textarea` etc.

If a user wanted to add `stretch` (not `grow`) to `partial` and `hint` or another field type, they can manually add it in themselves. To be honest those two fild types are more custom anyway.

Let me know if this is ok, this way I don't need to mess around with the builder files so much and do major changes.

**Comment by ayumihamsaki** [comment] 2019-07-20 15:52
@LukeTowers Sorry I forgot to ask you the most important thing, would you be happy with this setup:

Builder plugin to display that `grow` and `stretch` options for multiline inputs like `richeditor`, `markdown` and `textarea` etc.

If a user wanted to add `stretch` (not `grow`) to `partial` and `hint` or another field type, they can manually add it in themselves. To be honest those two fild types are more custom anyway.

Let me know if this is ok, this way I don't need to mess around with the builder files so much and do major changes.

---

Then this is the doc's pr: https://github.com/octobercms/docs/pull/387
(to keep you in the loop)

**Comment by ayumihamsaki** [comment] 2019-07-21 01:33
Just in the process of trying to code this out.

### New feature idea for textarea

My plan is trying to make the textarea be able to do three things:

1. grow
2. stretch
3. fullscreen

Below is a code example doing the fullscreen:

![ezgif-2-e00c879af276](https://user-images.githubusercontent.com/17784082/61585881-49ce2400-ab5f-11e9-88b4-0ab5ccea3be5.gif)

**Comment by LukeTowers** [comment] 2019-07-21 07:48
@ayumihamsaki Don't bother with the fullscreen unless you have a specific project that actually uses it, text areas shouldn't really be used for super long form content anyways. Builder stuff is fine with me as long as it's just the fields that actually use it that get the option.

**Comment by ayumihamsaki** [comment] 2019-07-21 12:16
@LukeTowers I will leave out the fullscreen option. My reason behind it was because both the **Rich Editor** and **Textarea** use the same mysql function of `text` which allow a 65,535 character limit. So I thought many people may add large amounts of text to the textarea. I know I do in many cases.

**Comment by ayumihamsaki** [comment] 2019-07-21 18:51
PR results:

## Textarea Stretch

### Outside Tabs

![outside-tabs](https://user-images.githubusercontent.com/17784082/61595576-bc3b1480-abf0-11e9-899e-e4723b63b17d.png)

### Primary Tabs

![primary-tabs](https://user-images.githubusercontent.com/17784082/61595580-c65d1300-abf0-11e9-91a9-3207357f5114.png)

### Secondary Tabs

![secondary-tabs](https://user-images.githubusercontent.com/17784082/61595587-d07f1180-abf0-11e9-9f0f-2b0371db9b2f.png)

**Comment by LukeTowers** [comment] 2019-07-21 18:52
@ayumihamsaki I'm curious to hear more about use cases where you would put long form text into a text area. I almost always find that it's better to use markdown or richeditor when dealing with long form text.

**Comment by ayumihamsaki** [comment] 2019-07-21 18:56
@LukeTowers I have major issues when I try to put HTML in the rich editor or markdown. The simple reason is because there are new attributes all the time and these editors remove the new attributes. Secondary they add a bunch of crazy HTML code in the source view, for example a line break comes up like this:

```html
<p>something</p>
   <p>   </p>
<p>more text</p>
```

I don't use them for HTML code at all and paste my HTML code directly into textarea boxes so what I see is what I get. Then I use html purifier to display the textarea onto the frontend.

That's my personal use cases.

**Comment by LukeTowers** [comment] 2019-07-21 19:11
Ah, gotcha. Yeah, I don't think that's a super common one so I think we're fine without a full screen button supported in the textarea.

**Comment by ayumihamsaki** [comment] 2019-07-21 19:19
I'm fine not adding it, I was worried add the icon in the textarea causing issues.

**Comment by ayumihamsaki** [comment] 2019-07-23 16:11
As per Luke's comment, I decided to code his request.

Stretch feature to `hint` fields:

![hint](https://user-images.githubusercontent.com/17784082/61728059-57a4c480-ad6c-11e9-8afb-aa2b76ae2feb.png)

Stretch feature to `partial` fields:

![partial](https://user-images.githubusercontent.com/17784082/61728078-62f7f000-ad6c-11e9-8d3b-403eb5999b19.png)

Grow is not added to them.

Right now it's not possible to add Stretch to YAML for these two fields, due to the code setup. Instead all you need to do is the following:

```html
<div class="stretch">
    ..
</div>
```

Add the `class stretch` to your container in your hint or partial file and October will do all the rest for you.

I will add a note of this in the doc's.

Peace.

**Comment by ayumihamsaki** [comment] 2019-08-23 15:19
I have tagged everyone who has shown interest in this issue:

@CptMeatball
@daftspunk
@LukeTowers
@Eoler
@Teranode
@w20k

If you want to see this added to October please add yourself as a tester to the pr found here: #4509

(The pr was finished weeks ago and just sitting there waiting for some testers)

**Comment by Eoler** [comment] 2019-08-27 14:00
Cool, going to test it by the end of the weekend.

**Comment by ayumihamsaki** [comment] 2019-08-27 14:27
Thanks

**Comment by ayumihamsaki** [comment] 2019-08-31 18:07
### My notes

Maths to work out stretch amount for tabs:

![image](https://user-images.githubusercontent.com/17784082/64067572-99a20f80-cc22-11e9-9f1c-3a7cfae2c2bd.png)

**Comment by ayumihamsaki** [comment] 2019-08-31 18:12
### My notes

Maths to work out stretch amount for tabs:

![image](https://user-images.githubusercontent.com/17784082/64067607-55633f00-cc23-11e9-9be5-428ed2afe6bc.png)

**Comment by ayumihamsaki** [comment] 2019-08-31 19:49
## Updated test plugin

PR found here: https://github.com/octoberrain/test-plugin/pull/77

### Screenshots:

Grow feature:

![image](https://user-images.githubusercontent.com/17784082/64068485-b9403480-cc30-11e9-8298-6b543b95aee8.png)

Stretch feature:

![image](https://user-images.githubusercontent.com/17784082/64068492-c3fac980-cc30-11e9-9c40-66967308b801.png)

**Comment by ayumihamsaki** [comment] 2019-08-31 19:49
Disclaimer I not yet finished the stretch feature - still working on it. Just need wait for three other PR's I have done to get merged first.

**Comment by ayumihamsaki** [comment] 2019-09-01 14:58
### Rich editor has been upgraded to using flexbox

The Rioch editor failed my testing, to fix it I have converted the Rich editor from using `display:table-row` to using `flexbox`.

The CSS fix is as follows:

```css
.field-richeditor.stretch .fr-box:not(.fr-fullscreen) {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
        -ms-flex-direction: column;
            flex-direction: column;
}
```

Test results:

![image](https://user-images.githubusercontent.com/17784082/64078140-eb07d880-ccce-11e9-91db-23419b67db67.png)

PLEASE NOTE: THIS SHOULD NOT CHANGE ANYTHING ON THE USER SIDE!

I have left this comment just as a future ref note.

**Comment by ayumihamsaki** [comment] 2019-09-01 15:48
# PR now finished

> This PR is now completely finished - there is nothing more I need to do now!

- This PR: https://github.com/octobercms/october/pull/4509 (finished)

- Doc's PR: https://github.com/octobercms/docs/pull/387 (finished)

- Test plugin PR: https://github.com/octoberrain/test-plugin/pull/77 (finished)

Please install this PR and use the Test plugin PR I created and you should see the following results:

### Grid

![image](https://user-images.githubusercontent.com/17784082/64078745-70db5200-ccd6-11e9-820a-fd90010904fc.png)

### New line

![image](https://user-images.githubusercontent.com/17784082/64078751-851f4f00-ccd6-11e9-8cc9-a811f778e21b.png)

### Grow

![image](https://user-images.githubusercontent.com/17784082/64078762-a3854a80-ccd6-11e9-9720-a2bc24544fcd.png)

### Stretch (textarea)

![image](https://user-images.githubusercontent.com/17784082/64078766-b861de00-ccd6-11e9-907f-e999f7b790b8.png)

### Stretch (rich editor)

![image](https://user-images.githubusercontent.com/17784082/64078773-cd3e7180-ccd6-11e9-933b-36adf62f4e14.png)

### Stretch (markdown editor)

![image](https://user-images.githubusercontent.com/17784082/64078779-e34c3200-ccd6-11e9-84d6-e6c17233f7f2.png)

### Stretch (Code editor)

![image](https://user-images.githubusercontent.com/17784082/64078785-f65f0200-ccd6-11e9-9d8f-eea78ec3c76d.png)

### Stretch (Hint)

![image](https://user-images.githubusercontent.com/17784082/64078792-0840a500-ccd7-11e9-93ec-16befdd2e527.png)

### Stretch (Partial)

![image](https://user-images.githubusercontent.com/17784082/64078797-1b537500-ccd7-11e9-9d08-120ae042ca56.png)

## Test results in test plugin

- [x] - New grid fields - passed testing (Stable)

- [x] - New line fields - passed testing (Stable)

Grow tests:

- [ ] - Grow - not passing - see below
  - [x] Textarea (Stable)
  - [x] Rich editor (Stable)
  - [x] Markdown editor (Unstable due to Ace version)
  - [x] Code editor (Unstable due to Ace version)

There is a bug with the grow on the Markdown editor and Code editor widgets, it sometimes doesn't work and some times does, without changing any code. This strange bug seems to be from using an old version of Ace Editor. This PR might fix all these issues found here: [Update Ace Editor from 1.2.6 to 1.4.5 and emmet.js](https://github.com/octobercms/october/pull/4585)

Stretch tests:

- [x] - Stretch - passed testing (Stable)
  - [x] Textarea (Stable)
  - [x] Rich editor (Stable)
  - [x] Markdown editor (Stable)
  - [x] Code editor (Stable)
  - [x] Hint (Stable)
  - [x] Partial (Stable)

**Comment by LukeTowers** [comment] 2020-06-17 21:30
@CptMeatball why'd you close this?

**Comment by daftspunk** [comment] 2021-03-06 02:54
Stretch needs to work in tandem with specific CSS classes layouts. Study the code to see where and how this is used. If the parent container does not afford the space, it won't stretch; does not push on parent containers, but fills them instead

**Closed by daftspunk** 2021-03-06 02:54 UTC
Labels: Priority: Medium, Status: Accepted, Status: In Progress, Type: Bug
