### ISSUE TITLE
[Suggestion] Show plugin codes on Updates page

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#200] opened 2014-05-22 19:25 UTC
If we're able to manually disable plugins via the ```config cms.disablePlugins``` option, would be good to have the plugin codes displayed on the SYSTEM > UPDATES page for each plugin, then it'd just be a simple copy & paste to disable each plugin - for now :)

**Comment by daftspunk** [comment] 2015-05-09 02:15
Duplicate of #36

**Closed by daftspunk** 2015-05-09 02:15 UTC
Labels: feature request
