### ISSUE TITLE
SCSS Compiler doesn't support `@supports` (ironically)

### ISSUE THREAD

**Issue by Harti** [octobercms/october#3647] opened 2018-07-21 08:46 UTC
#### Expected behavior

```sass
.sticky-top {
  @supports (position: sticky) {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
```
should compile to:
```
.sticky-top { @supports (position:sticky){position:sticky;top:0;z-index:1020} }
```

#### Actual behavior

```sass
.sticky-top {
  @supports (position: sticky) {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
```
instead compiles to:
```
@supports (position:sticky){position:sticky;top:0;z-index:1020}
```

#### Reproduce steps

theme/demo/assets/scss/app.scss:
```sass
.sticky-top {
  @supports (position: sticky) {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
```

In your layout file:
```htm
<link href="{{ ['assets/scss/app.scss']|theme }}" rel="stylesheet">
...

<body style="min-height: 3000px;">
    <div class="sticky-top">This should stick to the top</div>
    I'm the wrapper content
</body>
```

Regardless of the example working, you can see in the combined asset that the `.sticky-top` part of the SCSS rule is missing.

#### October build

437

**Comment by LukeTowers** [comment] 2018-07-22 03:54
Duplicate of https://github.com/leafo/scssphp/issues/493, not much we can do about in October itself but feel free to contribute towards a fix on leafo's side of things and it'll propagate to October!

**Closed by LukeTowers** 2018-07-22 03:54 UTC

**Comment by LukeTowers** [comment] 2020-04-01 23:04
This may be solved in the latest version of the dependency.
