### ISSUE TITLE
Administrator in octobercms

### ISSUE THREAD

**Issue by ronogrimen** [octobercms/october#3365] opened 2018-01-17 09:25 UTC
![error](https://user-images.githubusercontent.com/32258387/35035122-4cb459d8-fbab-11e7-86d9-2c21c7f03e08.png)
This error pop ups when creating admin user

##### October build
(October build number 432)

**Comment by LukeTowers** [comment] 2018-01-18 01:57
Duplicate of #3341. Discussion will continue there.

**Closed by LukeTowers** 2018-01-18 01:57 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
