### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by GaneshKandu** [octobercms/october#3402] opened 2018-02-16 05:28 UTC
##### Actual behavior
While installing OctoberCMS 1.0.433  we are getting following issue :

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `sessions` add unique `sessions_id_unique`(`id`))

##### Reproduce steps
While installing OctoberCMS 1.0.433
Server environment
PHP - 7.0.2
MySQL - 5.5.53

##### October build
OctoberCMS 1.0.433

**Comment by feridi94** [comment] 2018-02-16 11:05
I also experience it, as a solution I try to do this and succeed. by adding a line of code in the ArtisanServiceProvider.php

open location file: ./vendor/laravel/framework/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php
and add the following line of code:
`use Illuminate\Support\Facades\Schema;
class ArtisanServiceProvider extends ServiceProvider{
     public function boot(){
               Schema::defaultStringLength(191);
    }
  ...
}`

then do install october through php artisan:
php artisan october: install
done.

**Comment by GaneshKandu** [comment] 2018-02-16 12:30
Hi,

i can't update any file during installation
i am using online installer can't update file at run time

[Download installer](https://codeload.github.com/octobercms/install/zip/master)

@octobercms you can set Schema::defaultStringLength(191); in the boot method of your AppServiceProvider.

[https://github.com/laravel/framework/pull/23189](https://github.com/laravel/framework/pull/23189)

**Comment by feridi94** [comment] 2018-02-16 17:09
I agree the thing that just did not completely solve it, but in this way might be able to solve this problem.
in config/database.php in mysql section
add or replace charset & collation
**default**
 'charset' => 'utf8mb4',
 'collation' => 'utf8mb4_unicode_ci',

**replace with**
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',

       'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

**Comment by LukeTowers** [comment] 2018-02-16 22:02
Duplicate of #1927

**Closed by LukeTowers** 2018-02-16 22:02 UTC
