### ISSUE TITLE
Composer 2.0 compatibility

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#5033] opened 2020-04-08 08:40 UTC
It seems like composer 2.0 is right around the corner. Downloading `https://getcomposer.org/composer.phar` already gives you a 2.0 build. 

Our deployments just started to fail because of this. It seems like there is an issue with the composer-merge-plugin, as it explicitly requires composer 1.1:
https://github.com/wikimedia/composer-merge-plugin/blob/master/composer.json#L15

I have opened an issue on the plugins' GitHub page:
https://github.com/wikimedia/composer-merge-plugin/issues/184

I guess this needs a bump of the `wikimedia/composer-merge-plugin` dependency in October once a new version has been released.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires wikimedia/composer-merge-plugin 1.4.1 -> satisfiable by wikimedia/composer-merge-plugin[v1.4.1].
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
```

**Comment by idpsycho** [comment] 2020-04-08 15:24
It has been happening everywhere for a few days now, happens to everyone in our team.

TEMPORARY solution:
```
composer create october/october .
composer i --ignore-platform-reqs
```

**Comment by SaifurRahmanMohsin** [comment] 2020-04-15 04:28
I'm getting a similar issue which I believe is related to this. Surprising that the error message makes no sense because I'm using php 7.2 when the minimal requirement is 7.0 as per the platform.
![Screen Shot 2020-04-15 at 9 56 31 AM](https://user-images.githubusercontent.com/1699753/79298740-9f253f00-7eff-11ea-9567-5432c8327264.png)

**Comment by bennothommo** [comment] 2020-04-15 04:33
@SaifurRahmanMohsin The issue is we use the `config` key in `composer.json` to lock the version of PHP to `7.0`. @daftspunk's reasoning for the change can be [found here](https://github.com/octobercms/october/commit/f12f3af37f491f26fe101c3a01458fa467455df0). If this issue occurs for you, you can either remove the `config` key in `composer.json`, use @idpsycho's suggestion above, or use the `wip/laravel-6` branch.

**Comment by LukeTowers** [comment] 2020-04-15 04:36
@bennothommo using the L6 branch in @SaifurRahmanMohsin's case isn't the problem, he needs to update his composer.json to pull in 1.4.1 of the merge plugin instead of using dev-master. It's unfortunate that we were using dev-master in the first place, every project that's ever been pulled down before the recent fix will still have the broken version in their composer.json.

**Comment by tinh1115** [comment] 2020-04-17 11:07
Downgrade to 1.9.2 works for me, but in different project.

**Comment by bennothommo** [comment] 2020-06-17 06:05
Marking this as In Progress as [Wikimedia are working on it](https://github.com/wikimedia/composer-merge-plugin/issues/184), and just so this doesn't get archived again.

**Comment by prhost** [comment] 2020-10-30 21:11
Hello, I tested it on the branch `dev-composer20` (https://github.com/wikimedia/composer-merge-plugin/tree/composer20) and presented the error below. We will probably have to wait for a stable release from them before we update.

![Screen Shot 2020-10-30 at 18 09 24](https://user-images.githubusercontent.com/3984760/97757284-31c3af00-1adb-11eb-9616-632525c0f5c0.png)

**Comment by prhost** [comment] 2020-10-30 22:07
> Hello, I tested it on the branch `dev-composer20` (https://github.com/wikimedia/composer-merge-plugin/tree/composer20) and presented the error below. We will probably have to wait for a stable release from them before we update.
> 
> ![Screen Shot 2020-10-30 at 18 09 24](https://user-images.githubusercontent.com/3984760/97757284-31c3af00-1adb-11eb-9616-632525c0f5c0.png)

I made an adjustment for them that corrects this problem, let's see if they approve, I tested here with my fork and october, and ran the tests well on a large project with more than 40 plugins and with october developer branch and everything went well.

**Comment by LukeTowers** [comment] 2020-10-31 23:09
@prhost please test https://github.com/wikimedia/composer-merge-plugin/pull/189#issuecomment-719514950 against October, that's the PR that adds full 2.0 support to the merge plugin.

**Comment by prhost** [comment] 2020-11-02 18:53
I tested it here, my project ran fine with laravel 6. but I ran phpunit and presented the error below:

```
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

...............................................................  63 / 505 ( 12%)
............................................................... 126 / 505 ( 24%)
............................................................... 189 / 505 ( 37%)
............................................................... 252 / 505 ( 49%)
............................................................... 315 / 505 ( 62%)
...........................................................S... 378 / 505 ( 74%)
............................................................... 441 / 505 ( 87%)
............................................EEEEEE............. 504 / 505 ( 99%)
.                                                               505 / 505 (100%)

Time: 1.92 minutes, Memory: 92.50 MB

There were 6 errors:

1) HelpersTest::testConfigPath
Error: Class 'Mockery' not found

/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:116
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:100
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:88
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/october/rain/tests/Support/HelpersTest.php:18

2) HelpersTest::testPluginsPath
Error: Class 'Mockery' not found

/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:116
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:100
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:88
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/october/rain/tests/Support/HelpersTest.php:18

3) HelpersTest::testThemesPath
Error: Class 'Mockery' not found

/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:116
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:100
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:88
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/october/rain/tests/Support/HelpersTest.php:18

4) HelpersTest::testTempPath
Error: Class 'Mockery' not found

/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:116
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:100
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:88
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/october/rain/tests/Support/HelpersTest.php:18

5) HelpersTest::testUploadsPath
Error: Class 'Mockery' not found

/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:116
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:100
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:88
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/october/rain/tests/Support/HelpersTest.php:18

6) HelpersTest::testMediaPath
Error: Class 'Mockery' not found

/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:116
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:100
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:88
/Users/kallef/PhpstormProjects/orbital/october-develop/vendor/october/rain/tests/Support/HelpersTest.php:18

ERRORS!
Tests: 505, Assertions: 2890, Errors: 6, Skipped: 1.
➜  october-develop git:(develop) ✗ 
```

**Comment by LukeTowers** [comment] 2020-11-02 18:55
@bennothommo ^

**Comment by bennothommo** [comment] 2020-11-03 01:52
@LukeTowers fixed: fffa6db8d8b9dddd6b8fca79ffed26753029d59f

**Comment by prhost** [comment] 2020-11-04 14:16
Thanks @bennothommo, it worked. However @LukeTowers I believe that this version of the composer-merge-plugin did not work for us, what we really should do is to merge the vendor autoload of a plugin with the main autoload did not work.

I tested it by installing October.Drivers and creating an instance of Aws, one of the packages installed by him.

![Screen Shot 2020-11-04 at 11 12 41](https://user-images.githubusercontent.com/3984760/98122017-cc7f0d80-1e8e-11eb-8e6e-51684c7c371e.png)

**Comment by LukeTowers** [comment] 2020-11-04 16:05
@prhost how did you install the package?

**Comment by prhost** [comment] 2020-11-05 18:47
> @prhost how did you install the package?

`php artisan plugin:install Orctober.Drivers`

Within this plugin is the vendor folder `plugins/october/drivers/vendor`, in theory `composer-plugin-merge` should recognize that vendor and merge with the main vendor.

I remember that there was a native october class that did this job, I don't know why @daftspunk left the previous class to use `composer-plugin-merge`. Maybe save maintenance. I know 🤷🏻‍♂️

**Comment by LukeTowers** [comment] 2020-11-05 22:53
@prhost that native class still exists, it handles marketplace plugins, which if you run `plugin:install` is what you have. The composer-merge-plugin has nothing to do with marketplace plugins or plugins with vendor directories in the plugin folder. It simply merges the project composer.json with any composer.json files present in the plugins so that all project dependencies are loaded in the main project vendor folder.

**Comment by anilloutombam** [comment] 2020-11-07 12:08
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires wikimedia/composer-merge-plugin dev-master -> satisfiable by wikimedia/composer-merge-plugin[dev-master].
    - wikimedia/composer-merge-plugin dev-master requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
**Help unable to update or install composer**

**Comment by bennothommo** [comment] 2020-11-07 12:53
@anilloutombam We are aware of the error message - you do not need to re-paste the same error message, nor create another issue with the exact same message.

**Comment by anilloutombam** [comment] 2020-11-08 06:05
What is the solution for now @bennothommo

**Comment by bennothommo** [comment] 2020-11-08 06:18
@anilloutombam Download [Composer 1.10.17](https://github.com/composer/composer/releases/tag/1.10.17) locally into your October CMS folder and run that directly.

**Comment by koesper** [comment] 2020-11-11 08:34
If you happen to run into this problem when your build pipeline throws errors with composer v2, while it worked on v1. This might work:

`composer self-update --1`

This workaround makes sure that your pipeline runs Composer v1.x instead of v2

Suggestion found in the release notes:
https://github.com/composer/composer/releases/tag/2.0.0-RC2

**Comment by LukeTowers** [comment] 2020-11-11 21:16
Worth noting that if you manually add the repository from here: https://github.com/wikimedia/composer-merge-plugin/pull/189#issuecomment-719514950 and switch to the 2.0 patch branch in your project's composer.json it seems to work fine with 2.0. Using it on all my projects right now.

**Comment by everyx** [comment] 2020-12-14 15:51
> Thanks @bennothommo, it worked. However @LukeTowers I believe that this version of the composer-merge-plugin did not work for us, what we really should do is to merge the vendor autoload of a plugin with the main autoload did not work.
> 
> I tested it by installing October.Drivers and creating an instance of Aws, one of the packages installed by him.
> 
> ![Screen Shot 2020-11-04 at 11 12 41](https://user-images.githubusercontent.com/3984760/98122017-cc7f0d80-1e8e-11eb-8e6e-51684c7c371e.png)

@prhost I meet this problem too, do you have any workaround for this?

**Comment by everyx** [comment] 2020-12-14 23:31
> @prhost that native class still exists, it handles marketplace plugins, which if you run `plugin:install` is what you have. The composer-merge-plugin has nothing to do with marketplace plugins or plugins with vendor directories in the plugin folder. It simply merges the project composer.json with any composer.json files present in the plugins so that all project dependencies are loaded in the main project vendor folder.

@LukeTowers looks like the plugins' composer.json not loaded in the main project vendor folder in v1.1.1, how can I get this wokr?

**Comment by LukeTowers** [comment] 2020-12-15 07:04
@everyx what makes you think that's the case? Did you remove any vendor directory from the plugin folder itself and run composer update from the project root?

**Comment by everyx** [comment] 2020-12-15 08:09
> @everyx what makes you think that's the case? Did you remove any vendor directory from the plugin folder itself and run composer update from the project root?

@LukeTowers thanks your reply, and I have solved this problem by 

```shell
# disable scripts
composer create-project --no-scripts october/october . 1.1.1;
# and run discover manually
php artisan package:discover;
```

**Comment by VolCh** [comment] 2021-02-13 18:36
https://github.com/wikimedia/composer-merge-plugin/pull/189 has been merged

**Closed** 2021-03-05 07:21 UTC
Labels: Priority: High, Status: Blocked, Status: In Progress, Type: Bug, third party
