### ISSUE TITLE
Custom Form Widgets With AJAX Handlers Won't Work As Expected Inside Repeaters

### ISSUE THREAD

**Issue by theodark** [octobercms/october#3415] opened 2018-02-26 08:57 UTC
Adding a custom form widget, with AJAX handlers, inside a repeater should call that handler upon request. However the response throws an SystemException, even if the said custom widget uses the `$this->getEventHandler('onXXX')` method to access the handler.

In my case I was using the select2 to implement a custom "relation" style widget. Below is the partial that does the fetching request:

````html
<select class="form-control jq-select2" id="<?= $id ?>" name="<?= $name ?>">
</select>
<script lang="javascript" type="text/javascript">
	$(document).ready(function () {
		$('select.jq-select2').select2({
			'placeholder': '(Select Item)',
			'minimumInputLength': 3,
			'templateResult' : function (data) {
				if(!data.id) return data.text;
				console.log(data);
				var option = $(data.text);
				return option;
			},
			'ajax': {
				'delay': 500,
				'url': '',
				'dataType': 'json',
				'transport': function (params, success, failure) {
					$.request('<?= $this->getEventHandler('onFetchResultList') ?>',{
						'data' : { 'query' : params.data.term },
						'success' : success,
						'error' : failure
					});
				}
			}
		});
	});
</script>
````

And this ends up in a php function at the back end, in the style of:
````php
public function onFetchResultList() {
	return [
		"results" => $this->forgeQueryResults(strip_tags(input("query")))
	];
}
````
At rendering, I insert the widget inside a data repeater with name `contents_json` and I give it a name `magazine` - for example. In which case `$this->getEventHandler('onFetchResultList')` renders to `formContentsJsonForm1Magazine` when the partial is rendered in the form.

Upon ajax requests, October returns the following exception in the response
> "A widget with class name 'formContentsJsonForm1Magazine' has not been bound to the controller" on line 513 of /domains/example.domain/httpdocs/modules/backend/classes/Controller.php

I imagine that this should not happen under normal circumstances.
___

**For whom it may concern:** A quick workaround to this issue is to add another widget of the same kind at the top level form fields, then give it a name - f.e. `magazine_ajax` and set it to hidden, just to force the controller to load the widget class in the form. Then instead of using the `getEventHandler()` method in the partial, hardcode the name that the controller uses to identify that widget, in the javascript.  For example, the above `$.request` code of the partial would turn to

````javascript
	$.request('formMagazineAjax::onFetchResultList') ?>
````

##### October build
434

**Comment by iotch** [comment] 2018-09-29 16:18
Is there any progress on this? Got same issue recently.

**Comment by LukeTowers** [comment] 2018-09-30 02:56
@iotch feel free to dig into it further to see if you can find out any more information on the issue.

**Comment by pavsid** [comment] 2019-07-05 17:09
Getting a similar error too - `A widget with class name ... has not been bound to the controller on line 598 ...`

I'm using a record finder widget inside a repeater field. The record finder works, until I try to search within it, or sort columns etc.

If I select an option, and save the record, it works fine. Strange thing is, if I go back to that record and use the search/sort then works fine. Only errors on new fields.

**Comment by LukeTowers** [comment] 2019-07-05 18:27
@bennothommo could you look into @pavsid's report above?

**Comment by bennothommo** [comment] 2019-07-06 14:53
@pavsid PR #4434 may resolve this issue for you. Would you mind trying that fix out and let me know how you go?

**Comment by pavsid** [comment] 2019-07-08 14:46
@bennothommo Thanks, but unfortunately i'm getting the same error :(

**Comment by LukeTowers** [comment] 2019-07-08 17:49
@bennothommo this issue probably still exists inside and outside of a child repeater with your fix because it's an issue with a detached formwidget (detached because it's calling from the context of a popup instead of the overall form) trying to call it's AJAX handlers when either the widget nested in a repeater isn't initialized or the alias for referencing that widget is incorrect.

**Comment by bennothommo** [comment] 2019-07-08 23:59
@pavsid Thanks for letting me know.

@LukeTowers thanks for that. Will dig into it further :)

**Comment by bennothommo** [comment] 2019-07-13 04:15
@pavsid Would you mind providing an example of your setup as a PR to our [test plugin](https://github.com/octoberrain/test-plugin)? I think I have an idea as to where the issue may lie, but I would like to test it with a replica of your custom field setup so I can confirm.

**Comment by pavsid** [comment] 2019-07-30 15:15
> @pavsid Would you mind providing an example of your form as a PR to our [test plugin](https://github.com/octoberrain/test-plugin)? I think I have an idea as to where the issue may lie, but I would like to test it with a replica of your custom field setup so I can confirm.

Sorry @bennothommo I've been away - do you still need this?

**Comment by bennothommo** [comment] 2019-07-30 16:03
@pavsid not a problem. And yes please :)

**Comment by w20k** [comment] 2019-09-13 09:11
Forgot about test-plugin link: https://github.com/octoberrain/test-plugin/pull/78 😉

**Comment by LukeTowers** [comment] 2019-10-09 14:09
Fixed by https://github.com/octobercms/october/commit/96e335aebc144a67f0cc7661ac5853a1d21a5741

**Closed by LukeTowers** 2019-10-09 14:09 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
