### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by Marron0421** [octobercms/october#3457] opened 2018-03-18 16:34 UTC
※I am doing machine translation.
As it is in the title, I fail to update

#####ErrorLog
```
[18-Mar-2018 16:32:50 UTC] PHP Fatal error:  Call to undefined function Illuminate\Database\Schema\tap() in /home/hoge/public_html/hoge/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php on line 161
[18-Mar-2018 16:32:50 UTC] PHP Parse error:  syntax error, unexpected '?' in /home/hoge/public_html/hoge/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 250
```
##### Reproduce steps
build 430 → 434
##### October build
430

**Comment by LukeTowers** [comment] 2018-03-18 17:15
What's the full stack trace?

**Comment by devcflynn** [comment] 2018-03-27 19:13
Running into this same issue. Update from build 430 -> 434: Stack trace below:

[2018-03-27 15:12:55] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/chris/Projects/crosby/usba/vendor/symfony/translation/Translator.php:79
Stack trace:
#0 /home/chris/Projects/crosby/usba/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/chris/Pro...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#2 /home/chris/Projects/crosby/usba/vendor/jenssegers/date/src/Date.php(342): spl_autoload_call('Symfony\\Compone...')
#3 /home/chris/Projects/crosby/usba/vendor/jenssegers/date/src/Date.php(310): Jenssegers\Date\Date::getTranslator()
#4 /home/chris/Projects/crosby/usba/vendor/jenssegers/date/src/DateServiceProvider.php(36): Jenssegers\Date\Date::setLocale('en')
#5 /home/chris/Projects/crosby/usba/vendor/jenssegers/date/src/DateServiceProvider.php(25): Jenssegers\Date\DateServiceProvider->setLocale()
#6 [internal function]: Jenssegers\Date\DateServiceProvider->boot()
#7 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#8 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
#10 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
#11 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\Container\Container->call(Array)
#12 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Foundation\Application->bootProvider(Object(Jenssegers\Date\DateServiceProvider))
#13 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Jenssegers\Date\DateServiceProvider), 11)
#14 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#15 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#16 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(October\Rain\Foundation\Application))
#17 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#18 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
#19 /home/chris/Projects/crosby/usba/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#20 /home/chris/Projects/crosby/usba/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#21 {main}

**Comment by LukeTowers** [comment] 2018-03-27 19:37
@devcflynn were you updating via composer or the web installer?

**Comment by LukeTowers** [comment] 2018-03-27 19:44
Error is occurring because of https://github.com/symfony/translation/blob/master/Translator.php#L79 (the nullable typehint), which is a [PHP 7.1 feature](http://php.net/manual/en/migration71.new-features.php). This is probably happening for web installer updates because the marketplace build server probably builds the update files in a PHP 7.1 environment; which would pull down the latest version of symfony/translator which doesn't support PHP 7.0. 

@devcflynn @Marron0421 to fix this for your specific use cases; upgrade your servers to run PHP 7.1 instead.

**Comment by devcflynn** [comment] 2018-03-27 19:48
@LukeTowers So, I managed to make some progress in the time I posted to now. The issue is with Symfony's Translator component. And to that point, it is not really an issue with Symfony.  

Currently, I was running PHP 7.0 and not 7.1. But looking at the composer.json for October, it only states a requirement for PHP >= 7.0 but it looks like the Symfony/Translation/Translator.php that is being included in the project is using syntax that only works on PHP 7.1 or greater. Here is the line that was killing me:

 `public function __construct(**?**string $locale, MessageFormatterInterface $formatter = null, string $cacheDir = null, bool $debug = false)`

Notice the "?" before the string type declaration. This is what was messing things up. I have updated to 7.1 on the host machine as well as the requirement in composer and it fixes this issue. 

I don't know if this helps anyone, but took us a bit to narrow down the issue.

**Comment by devcflynn** [comment] 2018-03-27 19:51
@LukeTowers I think it would be beneficial to mention this in the requirements somewhere. I had a new guy trying to setup October with a fresh install and this issue was not obvious to them... Just a thought. 

Thanks for the quick responses!

**Comment by LukeTowers** [comment] 2018-03-27 20:18
@devcflynn that's all exactly as you said, and October does support 7.0, but the build server that produces the consumer version (updating through the backend or using the web installer) is generating the build in a PHP 7.1 environment which causes composer to pull in the 7.1 version of symfony. I've contacted @daftspunk to fix that in the future, but for now bump up your server to PHP 7.1 or use composer to update your installs to grab the PHP 7.0 versions of everything.

**Comment by LukeTowers** [comment] 2018-03-28 00:20
@devcflynn @Marron0421 please post your composer.json files and the list of plugins that you're using; we've confirmed that the version provided by the gateway is the PHP 7.0 compatible version so there must be something else going wrong.

**Comment by devcflynn** [comment] 2018-03-28 13:36
This is my current composer.josn, which is working now. It basically the one from the repo:

```
{
    "name": "october/october",
    "description": "October CMS",
    "homepage": "http://octobercms.com",
    "keywords": [
        "october",
        "cms",
        "octobercms",
        "laravel"
    ],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Co-founder"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Co-founder"
        }
    ],
    "support": {
        "issues": "https://github.com/octobercms/october/issues",
        "forum": "http://octobercms.com/forum/",
        "docs": "http://octobercms.com/docs/",
        "irc": "irc://irc.freenode.net/october",
        "source": "https://github.com/octobercms/october"
    },
    "require": {
        "php": ">=7.1",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.5.*",
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.7",
        "phpunit/phpunit": "~5.7",
        "phpunit/phpunit-selenium": "~1.2"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-update-cmd": [
            "php artisan october:util set build"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}

```
and this is the composer.json that is used in one of our plugins:

```
{
	"require": {
		"tobscure/json-api": "^0.4.1",
		"lcobucci/jwt": "3.2.*",
		"moneyphp/money": "^3.0",
		"league/csv": "^8.0",
		"authorizenet/authorizenet": "~1.9",
		"doctrine/annotations": "1.4.*",
		"nesbot/carbon": "~1.21",
		"sentry/sentry": "^1.8",
		"monolog/monolog": "^1.23",
        "sentry/sentry-laravel": "^0.8.0",
        "stanley/geocodio-php": "~1.0"
	}
}
```
Let me know if that was what you were looking for @LukeTowers

**Comment by LukeTowers** [comment] 2018-03-28 15:41
@devcflynn I don't think the PHP requirement being changed from PHP 7.0 to 7.1 would fix this on it's own, composer still runs using the CLI PHP version unless you tell it not to. My best guess at this point is the dependencies were downloaded on a 7.1 environment and then copied over to a 7.0 environment.

**Comment by LukeTowers** [comment] 2018-07-12 12:23
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Closed by LukeTowers** 2018-07-12 12:23 UTC
Labels: Status: Response Needed, Type: Unconfirmed Bug
