### ISSUE TITLE
i can't enable the disabled plugins

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#2774] opened 2017-03-23 07:08 UTC
##### Expected behavior
I hope the plugins can be enable in normal

##### Reproduce steps
1. i disable plugins in backend
2. i can't found a 'enable' opiton when i want to enable plugins

![image](https://cloud.githubusercontent.com/assets/26053904/24235793/cc636ebc-0fd9-11e7-8e87-c1578a19a8bc.png)

![image](https://cloud.githubusercontent.com/assets/26053904/24235817/e4a163c6-0fd9-11e7-825f-fc52298393ed.png)
3. i try the 'Freeze updates' option,  it show me  below, it means 'Freeze updates' is 'enable'?
![image](https://cloud.githubusercontent.com/assets/26053904/24235850/129d3fa2-0fda-11e7-8425-11ee9f398a05.png)

##### October build
v1.0.401

**Comment by LukeTowers** [comment] 2017-03-23 07:22
Duplicate of #2714. See https://github.com/octobercms/october/issues/2714#issuecomment-287591391 for the solution, basically just leave those boxes unticked and click apply / save / confirm (whatever that popup says for a positive action button).

I do agree that this UX could be much improved by populating the checkbox with the current status of the plugin so that it was more obvious what exactly you were doing to a plugin when using that popup.

**Closed** 2017-03-23 07:36 UTC
Labels: duplicate

**Comment by daftspunk** [comment] 2017-03-23 22:53
Great suggestion, someone PR this?
