### ISSUE TITLE
Searching in CMS pages/partials/layouts should return matching folder names too

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1466] opened 2015-09-26 12:18 UTC
If I search using the filter field in CMS pages/partials/layouts sidebar, it currently includes anything with a matching filename or description. I would also like matching folder names included in this list.

## Use case
If I have for example all my blog related partials inside a *blog* subfolder, that folder is the most relevant search result I could possibly have when searching for *blog*.

**Comment by daftspunk** [comment] 2015-10-16 22:03
There isn't enough detail here for me to make a decision, can you describe your folder structure and exactly what you are searching for to end up at the failing position that prompted you to log this.

**Comment by daftspunk** [comment] 2015-10-16 22:03
## Reporting a bug with OctoberCMS

**Please don't use the main Github for reporting bugs with plugins.** If you have found a bug in a plugin, the best place to report it is with the [plugin author](http://octobercms.com/plugins).

We work hard to process bugs that are reported, to assist with this please ensure the following details are always included:

- **Bug summary**: Make sure your summary reflects what the problem is and where it is.

- **Request location**: Enter the URL where this bug occurs, if applicable.

- **Reproduce steps**: Clearly mention the steps to reproduce the bug.

- **Expected result**: How OctoberCMS should behave on above mentioned steps.

- **Actual result**: What is the actual result on running above steps i.e. the bug behavior - **include any error messages**.

**Comment by Flynsarmy** [comment] 2015-10-19 01:05
**Reproduce steps:**
* Create a folder 'bloggy' in your Pages list in CMS.
* Add all your /blog/ URLs to it.
* Enter 'bloggy' into the filter field - you'll get 0 results.
![page-list](https://cloud.githubusercontent.com/assets/334808/10567803/2340104c-7651-11e5-923c-9af731d9a9d5.png)

**Expected result:**
If I'm searching for 'bloggy', i should get:
* Any pages with 'bloggy' in their URL
* Any pages with 'bloggy' in their title or description
* Any pages inside a folder containing the string 'bloggy'
![after-change-filtered](https://cloud.githubusercontent.com/assets/334808/10567804/2342e736-7651-11e5-9ae3-aa499471c384.png)

**Actual result:**
'bloggy' folders aren't included in the result list.
![before-change-filtered](https://cloud.githubusercontent.com/assets/334808/10567805/23435b80-7651-11e5-95c9-08480e4ae33e.png)

**Comment by daftspunk** [comment] 2015-12-04 21:24
Fixed by #1489

**Closed by daftspunk** 2015-12-04 21:24 UTC
Labels: missing detail
