### ISSUE TITLE
When browsing for a htm file and clicking on it multiple copies open up.

### ISSUE THREAD

**Issue by chowraid** [octobercms/october#1391] opened 2015-08-24 20:08 UTC
While you click on a htm file multiple of the same tabs open up at the same time.

**Comment by CameronHall** [comment] 2015-08-30 13:46
Can you please explain this clearer and in more detail?

**Comment by daftspunk** [comment] 2015-10-10 08:01
Duplicate of #1428 and missing detail

**Closed by daftspunk** 2015-10-10 08:01 UTC
