### ISSUE TITLE
Theme export bug

### ISSUE THREAD

**Issue by cheb60** [octobercms/october#4603] opened 2019-09-06 13:03 UTC
- OctoberCMS Build: 458
- PHP Version: 7.3
- Database Engine: mySQL 5.7
- Plugins Installed: None

### Description:
When trying to export the theme the system throws an error.

### Steps To Reproduce:
Step 1: Just clone octoberCMS Repo.
Step 2: Go to Settings -> Themes
Step 3: Theme -> Manage -> Export
Step 4: Receive error:
"Declaration of Cms\Models\ThemeExport::save() should be compatible with October\Rain\Database\Model::save(?array $options = NULL, $sessionKey = NULL)" on line 17 of C:\wamp64\www\october\modules\cms\models\ThemeExport.php

**Comment by vevers** [comment] 2019-09-06 13:32
Seems to be a duplicate of #4597 and fixed in the development branch

**Comment by bennothommo** [comment] 2019-09-06 13:47
@vevers is correct. This is a duplicate of #4597.

**Closed by bennothommo** 2019-09-06 13:47 UTC
Labels: duplicate
