### ISSUE TITLE
Issues with repeater drag and drop sorting

### ISSUE THREAD

**Issue by darkwoods-** [octobercms/october#1679] opened 2016-01-03 07:36 UTC
Seems like there is a issue with dragging and dropping in the repeater.
If I drag and drop child-item it can get stuck in the parent-item and I can not take it back as child item and is forced to refresh the whole page to fix it back as child item..

thanks

**Comment by jwilson8767** [comment] 2016-01-04 00:50
duplicate of [rainlab/pages-plugin#109](https://github.com/rainlab/pages-plugin/issues/109)

**Comment by daftspunk** [comment] 2016-01-19 10:10
Is this when using nested repeaters?

**Comment by darkwoods-** [comment] 2016-01-19 11:02
@daftspunk yes when using nested repeaters the nested items gets stuck in the parent item when reordering them and makes the whole drag and drop reordering chaotic and unusable.

**Comment by manogi** [comment] 2016-04-17 12:34
I have the same issue. Reordering nested repeater items. The nesed items lands in the parent level when I try to reorder them.

**Comment by manogi** [comment] 2016-04-17 12:34
...in Build 318

**Comment by daftspunk** [comment] 2016-05-17 22:43
Nested repeaters aren't really supported at this stage (initial tests were not performed for a repeater in a repeater). The possible solution would be to give each repeater a unique group code in the sortable plugin, if not already. It seems like children can be moved to parents, but parents not to children. This is odd and it looks to be bugging out.

For replication: See Countries > States tab in [Test plugin](http://github.com/daftspunk/oc-test-plugin)

**Comment by daftspunk** [comment] 2016-07-23 03:08
Fixed by: #2233
Our hero: @acasar

![Up top](https://dl.dropboxusercontent.com/u/5381773/lel/up-top.jpg)

**Closed by daftspunk** 2016-07-23 03:08 UTC
Labels: Priority: Low, Type: Bug
