### ISSUE TITLE
Current selection lost on Froala Editor while inserting a link from the list

### ISSUE THREAD

**Issue by jochemschulten** [octobercms/october#2979] opened 2017-07-17 12:05 UTC
##### Expected behavior
When highlighting text and inserting a link (picked from the link list) inside the Froala Editor, it should replace the current selection with the link.

##### Actual behavior
It inserts the link at the start of the text in the editor.

##### Reproduce steps
1. Go to a richeditor field, for example Pages -> Home.
2. Highlight text in the editor.
3. Click the 'Insert link' button in the editor.
4. Click the 'search' icon.
5. Select a link from the list.
6. Click 'Insert'.

##### October build
419

**Comment by jan-vince** [comment] 2017-07-22 05:07
I can confirm this bug - when a link is inserted from Link list popup, selection is lost.

The reason is probably same as [descriebed here](https://github.com/froala/wysiwyg-editor/issues/635) - the ````restore.selection```` is maybe missing.

*I will try to fix this when I have a little more time...*

**Comment by LukeTowers** [comment] 2017-10-19 15:56
Duplicate of #3064, moving discussion there.

**Closed by LukeTowers** 2017-10-19 15:56 UTC
Labels: Priority: Medium, Status: Review Needed, Type: Unconfirmed Bug
