### ISSUE TITLE
error when line in version.yaml to long

### ISSUE THREAD

**Issue by Codenator81** [octobercms/october#1816] opened 2016-02-27 23:52 UTC
When in plugin version.yaml file one line too long got error when install plugin.
May be we can trim it if too long?

  [Illuminate\Database\QueryException]
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'detail' at row 1 (SQL: insert into `system_plugin_history` (`code`, `type`,
  `version`, `detail`, `created_at`) values (KurtJensen.MyCalendar, comment, 1.1.5, !!! This is an important update that contains breaking changes. MyCalend
  ar will now be using Passage Permission Keys for permissions and you will need to install the plugin using code "kurtjensen.passage" if you use permission
  s for your events. If you do not install Passage Permission Keys plugin then your protected events may not show or may be visible to anyone who visits you
  r site until you do add PassagePermission Keys plugin. This update also added raw data element to event array and applied config date/time to all componen
  ts., 2016-02-27 22:58:02))

  [PDOException]
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'detail' at row 1

**Comment by firemankurt** [comment] 2016-02-27 23:55
FYI This worked fine on Feb 5 when I updated the same plugin.  My system_plugin_history table has that entry in it.

**Comment by Codenator81** [comment] 2016-02-27 23:56
Sorry I not mention. I use last stable branch

**Comment by daftspunk** [comment] 2016-02-28 01:32
This is probably caused by MySQL strict mode more than anything. We will
have to change the column to TEXT to support lengthy updates like this.

**Comment by daftspunk** [comment] 2016-03-25 20:29
##### This bug has been fixed via live stream:
:movie_camera: https://youtu.be/pWsljcZruKI

**Closed** 2016-07-02 21:44 UTC
Labels: Priority: High, Status: Completed, Type: Bug
