### ISSUE TITLE
Quick notice of a broken mediafinder version from 443 to 446 when upgrading

### ISSUE THREAD

**Issue by kukrik** [octobercms/october#4039] opened 2019-01-06 20:08 UTC
First of all, I would like to announce that my English is not good.
I don't know if upgrading the version caused a broken mediafinder. Today (06.01.2019), I received an automatic notification of a version update recommendation. Fortunately, my second project is in the development phase. Then other plugins that use the mediafinder will not display the image in the backend. Image link is broken. For example, the media url should be "http: //localhost/KAAR/storage/app/media/assets/more_image.jpg", but all links point to double root:
"http://localhost/KAAR/KAAR/.../.../etc /..."

I also looked at the mediamanager, then the download url is also broken. Screenshots speak better for themselves:
<img width="1280" alt="screenshot 2019-01-06 at 21 05 10" src="https://user-images.githubusercontent.com/2853034/50740955-5ad8c880-11ff-11e9-9cfc-d9e5377b0807.png">

<img width="1280" alt="screenshot 2019-01-06 at 21 06 56" src="https://user-images.githubusercontent.com/2853034/50740956-63c99a00-11ff-11e9-932d-b2b979eca41f.png">

I do not know if the failure of the mediafinder is related to the upgrade? I want to listen to you!

**Comment by w20k** [comment] 2019-01-07 20:44
@kukrik, couldn't yet reproduce your issue, might try with a subfolder.

**Comment by kukrik** [comment] 2019-01-07 23:13
My development on the server has several projects, so this project is in the "KAAR" folder. All other things work well, no problem. Only the image url is incorrect. There have been no problems until version 443.

Today I was thinking for a moment and raised the root of this project, then the url of the picture is correct and shows.

Today I made a clean installation for another project "OCTOBER" and wanted to see how the image link looks like. Same problem: "http://localhost/OCTOBER/OCTOBER/storage/app/media/assets/more_image.jpg".

This means that after the upgrade, only the correct url of the image can be seen on the root. But this is not normal, there may be multiple subfolders on the production server. What's going to happen then?

I searched and found the places that show the wrong way. These are "$imageUrl" and "$publicUrl". Certainly, they give a good hint to find other classe ...

I'll hear you. I am already concerned that this project cannot be continued.

**Comment by kukrik** [comment] 2019-01-08 09:38
I did another test and another level below: root->TEST->another_test.

The result is "http://localhost/TEST/another_test/TEST/another_test/storage/app/media/more_image.jpg".

I hope this test will give you a hint of where the problem is.

I look forward to your thoughts and suggestions.

**Comment by w20k** [comment] 2019-01-08 09:42
@kukrik, could you also try, just to be 100% sure where to look. Try the same thing `root->TEST->another_test` with .443 build?
Thanks a lot for your help!

**Comment by kukrik** [comment] 2019-01-08 12:13
How do I make a clean installation with build 443? Every new installation follows the latest versions in real time.

I use every project with a new installation, I use the installation wizard: https://octobercms.com/docs/setup/installation.

My previous project is in build 443. I copied it to another folder for testing. The image url is correct on the front end, but I cant log in to backend.

@w20k, does it give an idea of where a bug can be? Second, don't you want to try a new installation and try the same thing like root->some-test or root->some-test->another-test?

**Comment by w20k** [comment] 2019-01-08 12:20
@kukrik, I will, but most probably later today. Thanks for helping!

**Comment by kukrik** [comment] 2019-01-08 13:21
Hi, I was thinking and doing one sample, I exchanged the build 446 in the `modules->system` folder against build 443 in the folder` modules>system`.

And it works now.

I'm a new boy here since the summer of 2018. I can't find a specific cause that causes this error.

@LukeTowers, I hope this tip will give you a specific hint about what changes have earlier been made to this folder before.

I'll listen to you!

**Comment by w20k** [comment] 2019-01-08 14:14
@kukrik, @LukeTowers - found the cause here.

MediaLibrary.php (https://github.com/octobercms/october/blob/26173486d39cdf4312535ecf247e3d7a161713b4/modules/system/classes/MediaLibrary.php#L542)
Will create PR.
```
$fullPath = $this->storagePath.implode("/", array_map("rawurlencode", explode("/", $path))); 

$this->storagePath.$path;
```

**Comment by LukeTowers** [comment] 2019-01-08 15:41
@kukrik what is your link policy and your app_url set to?

**Comment by adsa95** [comment] 2019-01-08 16:01
The problem actually occurs in the next line: `Url::to($fullPath)`. Because `$fullPath` is relative to the domain root (due to `$this->storagePath` being so if not using S3 etc), and when not given a full URL `Url::to()` adds the schema and full root path again (incl subdomain) and it gets duplicated.

I suggest we make `$this->storagePath` only be relative to the application root, and then the application root relative to domain root will be added in `Url::to()`, this applies no matter the link policy. Since `$this->storagePath` originates in the config where it should be set relative to the application root in the config, the fix is as simple as removing these three rows that add the application root to the variable:

https://github.com/octobercms/october/blob/064daa2d2ecbb92d7d4ef058315c989e54c1aa87/modules/system/classes/MediaLibrary.php#L76-L78

I've done a quick test with this this using the Media Viewer and all different link policys, with and without subfolder and it seems to work as intended.

In this class `$this->storagePath` is only used in `getPathUrl()` so this should not affect any other featurs of the MediaLibrary class, and when using S3 etc `$this->storagePath` will be a qualified URL it would not be affected by the lines above and also passes through `Url::to()` without modification, hence it should not be affected either.

**Comment by LukeTowers** [comment] 2019-01-08 16:50
@adsa95 that sounds good to me, are you able to add a unit tests with various combinations of link policies and app urls to make sure that this stays fixed?

**Comment by kukrik** [comment] 2019-01-08 16:51
> @kukrik what is your link policy and your app_url set to?

@LukeTowers, hmmmm, I can't say anything about the first question. @adsa95 explained his comment, I understand it... 
The second question is clear, I have config->app.php:` 'url' => 'http://localhost/KAAR/'`.

Where did I make a mistake?

**Comment by w20k** [comment] 2019-01-12 21:15
@adsa95, could you make PR to fix it? I'll look at the testing part if you don't have time. Ping me on your PR.
Thanks!

**Comment by RempadDesign** [comment] 2019-01-22 19:01
I Can confirm that the #4055 solution of removing the 

<code>
if (!starts_with($this->storagePath, ['//', 'http://', 'https://'])) {
$this->storagePath = Request::getBasePath() . $this->storagePath;
}
</code>

from modules/system/classes/MediaLibrary.php on line 76 - 78 fixed the issue. 
This issue is also anoing if is present in the Rainlab Pages Plugin because you can't change the image in the design view mode. This fix also applied to this Page Plugin Bug.

I can confirm also that this Bug is only present in the last October CMS 446 Build, case confirmed by updating from 443 (old website on subfolder installation with tested no Media Library problems) to 446 and the problems showed up.

Thank you all for the fix and we are waiting for a update release with another Build that has this BUG fixed by default.

Cheers.

**Closed** 2019-03-02 01:02 UTC
Labels: Status: Completed, Type: Bug
