### ISSUE TITLE
Second added page in CMS with error

### ISSUE THREAD

**Issue by Trysystems** [octobercms/october#4627] opened 2019-09-18 21:40 UTC
- OctoberCMS Build: 458
- PHP Version: 7.2

### Description:
In CMS section on click Add page twice - first added page in tabs is ok, second - without editor.

![screen](https://user-images.githubusercontent.com/12799052/65187997-8a94cd00-da2a-11e9-93e7-33b0bfbe1b8b.png)

**Comment by w20k** [comment] 2019-09-19 07:08
CMS is having some weird issues in the clean build 458. JS errors for destroying tab as well.

**Comment by w20k** [comment] 2019-09-25 11:32
Know what the issue is, but now need to find where it is ;) 
It's not creating a new page, but trying to re-use old id.

**Comment by w20k** [comment] 2019-10-01 07:29
Fixed by @daftspunk ref: https://github.com/octobercms/october/commit/c23d671f9104f2239fc77c9601d48eb5c6db5c3a

**Closed by w20k** 2019-10-01 07:29 UTC
Labels: Priority: Medium, Status: Review Needed, Type: Bug

**Comment by LukeTowers** [comment] 2019-10-02 15:38
@w20k did we get the issue fixed in the RainLab.Pages plugin too?

**Comment by w20k** [comment] 2019-10-02 15:41
@LukeTowers I've already mentioned with the tests that I did couldn't reproduce the same behavior in RainLab.Pages. If you could point me out "how", then I'll triple-check :)
