### ISSUE TITLE
Please add deferred bindings support for pivot data

### ISSUE THREAD

**Issue by jajacobs** [octobercms/october#1803] opened 2016-02-24 20:17 UTC
There are many scenarios were this is useful. For example when adding order items while creating an order.

**Comment by daftspunk** [comment] 2016-02-25 19:40
We will get around to it eventually.

**Comment by priitperna** [comment] 2017-02-03 08:29
Any progress on this issue?

**Comment by LukeTowers** [comment] 2017-02-03 23:08
@priitperna Did #1641 fix it for you? Please let us know so we can close this issue and document the new support if it did.

**Comment by daftspunk** [comment] 2017-02-05 19:53
Still thinking of the best way to handle this. We may need to add a jsonable field to the deferred bindings table to allow the pivot data to be stored temporarily.

**Comment by LukeTowers** [comment] 2017-03-30 17:28
Duplicate of #1409

**Closed by LukeTowers** 2017-03-30 17:28 UTC
Labels: Priority: Medium, Status: Review Needed, Type: Conceptual Enhancement
