### ISSUE TITLE
Crash when trying to access manage usergroups

### ISSUE THREAD

**Issue by rendler-denis** [octobercms/october#1418] opened 2015-09-03 20:58 UTC
Hi!

I found an issue that crashes the app when trying to manage the user groups.
The error is generated by this SQL query:
```sql
select 
backend_users_groups.user_group_id, count(*) as count, 
"backend_users_groups"."user_group_id" as "pivot_user_group_id", 
"backend_users_groups"."user_id" as "pivot_user_id" 
from "backend_users" 
inner join "backend_users_groups" on "backend_users"."id" = "backend_users_groups"."user_id" 
where "backend_users_groups"."user_group_id" in (?) 
group by "backend_users_groups"."user_group_id"
```

Below is the complete error:

```
SQLSTATE[42803]: Grouping error: 7 ERROR: column "backend_users_groups.user_id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...groups"."user_group_id" as "pivot_user_group_id", "backend_u... ^ (SQL: select backend_users_groups.user_group_id, count(*) as count, "backend_users_groups"."user_group_id" as "pivot_user_group_id", "backend_users_groups"."user_id" as "pivot_user_id" from "backend_users" inner join "backend_users_groups" on "backend_users"."id" = "backend_users_groups"."user_id" where "backend_users_groups"."user_group_id" in (1) group by "backend_users_groups"."user_group_id")
```

The database is PostgreSQL 9.3 on Debian 7.

**Comment by rosuji-mms** [comment] 2015-09-21 16:12
Experiencing the same issue.

**Comment by kolbma** [comment] 2015-09-24 16:37
I've uploaded a PDF print of the complete exception to
https://www.dropbox.com/s/3y5235abdb0r0vx/octobercms_exception.pdf?dl=0

The system.log with what I can see the same exception is here:
https://www.dropbox.com/s/mvilx2y8efc0qx5/octobercms_system.log.gz?dl=0

My DB is also pgsql 9.3 but openSUSE 42.

**Comment by mosid** [comment] 2015-09-28 14:22
I got the same issue. It appears to be related to postgresql.
I switched my site to mysql  and the error was gone.

**Comment by kolbma** [comment] 2015-10-06 12:31
Yes, but they say postgres is supported and it does not work there. Currently you can not use octobercms with postgresql because the fundamental feature to manage users is not working.

**Comment by daftspunk** [comment] 2015-10-07 08:13
I thought we had solved this, but apparently it has returned. Someone feel free to submit a PR to solve it.

Laravel does not seem to protect us from invalid queries in PostgreSQL

**Comment by daftspunk** [comment] 2015-10-07 08:16
We had fixed this previously [by stripping off the ORDER BY clause whenever `count()` call is used](https://github.com/octobercms/library/blob/master/src/Database/QueryBuilder.php#L171-L182), can someone determine what we need to strip off this SQL query to make it valid?

**Comment by rendler-denis** [comment] 2015-10-07 08:20
I'll take a look at it later this week if no one else beats me to it. It starts to really bug me :)

**Comment by kolbma** [comment] 2015-10-07 11:05
Can you give me the line of code where build of this query starts?

**Comment by methodicool** [comment] 2015-10-29 03:06
Anyone make progress on this? I am experiencing the same issue. Postgres 9.3 and ubuntu 14.04

**Comment by rendler-denis** [comment] 2015-12-04 09:32
Hello! Guys, I've investigated this issue and it might be a little deeper than I initially thought. It also reproduces on MySQL 5.7.5+ I need a bit more time to confirm this and will update with results.

**Comment by phuib** [comment] 2016-01-12 23:33
This drove me crazy, so I just disabled the users_count column like this.

```php
\Backend\Controllers\UserGroups::extendListColumns(function($list, $model) {
    $list->removeColumn('users_count');
});
```

**Comment by daftspunk** [comment] 2016-01-13 07:05
Looks like this is a duplicate of https://github.com/rainlab/blog-plugin/issues/171
And fixed by https://github.com/octobercms/october/commit/d8922c263f99a51d3b58947ac633622fd1aa1043

**Comment by daftspunk** [comment] 2016-01-13 08:04
My mistake, this is fixed by:
https://github.com/octobercms/library/commit/b2e4d2a7af0e359de83a8eac95441bfb07b6e7b7

**Comment by daftspunk** [comment] 2016-01-27 00:02
Fixed in Build 314

**Closed by daftspunk** 2016-01-27 00:02 UTC
Labels: bug, PostgreSQL
