### ISSUE TITLE
Safe mode prevents editing of meta data

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#3551] opened 2018-05-16 12:32 UTC
##### Expected behavior
When safe mode is enabled only the php section will become uneditable.

##### Actual behavior
When safe mode is enabled all cms related data is protected.

##### Reproduce steps
Enable safe mode in config/cms.php

##### October build
435

##### Other issues regarding this issue
https://github.com/rainlab/pages-plugin/issues/174

**Comment by LukeTowers** [comment] 2018-05-17 07:07
@CptMeatball I don't have time to dig into this right now, could you investigate and see if you can come up with a fix that would solve both issues?

**Comment by Teranode** [comment] 2018-05-23 16:22
I can't replicate this issue. Safe mode seems to be functioning as intended.

**Comment by CptMeatball** [comment] 2018-05-28 08:00
WIll do Luke. 

@Teranode that's weird. Maybe a `null` implementation is the culprit. Or settings debug mode to false. Will see if I can come up with some more tests in different environments.

**Comment by bennothommo** [comment] 2019-08-07 01:24
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by CptMeatball** [comment] 2019-08-27 13:38
Looks like this is still an issue! 

The problem occurs if the page has a php section declared. If that's the case, the safe-mode kicks in to prevent the save event.

Also, `cms.databaseTemplates` circumvents this, as the safe mode only looks at the actual file I think and not the saving of the data itself. This is another issue however.

**Comment by bennothommo** [comment] 2020-02-10 04:02
I've confirmed the bug.

It appears to be a case of the newlines in the code editor being changed slightly (I presume by Ace Editor), which makes the field dirty and causes the safe mode check to prevent saving the model.

**Comment by bennothommo** [comment] 2020-02-10 04:39
@CptMeatball would you mind giving the fix in #4934 a go and let me know if that resolves the issue for you?

**Comment by CptMeatball** [comment] 2020-02-24 17:25
Will do! Sorry for the slow response.

**Comment by mjauvin** [comment] 2020-02-25 00:52
@CptMeatball if that can help, I created a container with PR #4936 merged in here (safe mode is enabled):

https://2c04c4984f2e.octodock.com/backend

user/pass = admin

**Comment by bennothommo** [comment] 2020-02-25 01:35
@CptMeatball maybe hold off for now. We've had some discussions about my fix and we're looking to attempt it a different way that may solve a few other issues that have cropped up as well. We'll update here when we have made progress on this.

**Closed** 2020-09-01 00:23 UTC
Labels: Status: Archived, Status: Review Needed, Type: Bug

**Comment by bennothommo** [comment] 2021-01-17 15:11
Fixed by https://github.com/octobercms/october/commit/47b2aa0f15fb44d8902c17d5150bc19e2eecdbe.
