### ISSUE TITLE
Limiting a repeater for a plugin

### ISSUE THREAD

**Issue by Benpxpx** [octobercms/october#1710] opened 2016-01-19 12:20 UTC
I'm looking to limit how many repeaters are used in a plugin setting.
My use case is I want people to put in the days of the week but I obviously don't want more then 7 to be inputted by the user.

Any recommendations on how best to tackle this?

/cc @jonpxpx

**Comment by daftspunk** [comment] 2016-01-21 09:35
An option called `maxItems` could be introduced to handle this, hiding the "Add" button when the limit is reached.

**Comment by Benpxpx** [comment] 2016-01-21 11:48
That would be perfect, it's not mission critical so to speak, but would be nice to see down the road.

**Comment by arzola** [comment] 2017-02-20 16:44
I already did this thing i can send a PR but i can't find how to test it, do you have an example of a Testing a FormWidget  to add my assertions ? related #2649

**Comment by LukeTowers** [comment] 2017-03-01 02:48
Duplicate of #2649, Fixed by #2723

**Closed by LukeTowers** 2017-03-01 02:48 UTC
Labels: Type: Conceptual Enhancement
