### ISSUE TITLE
A report widget is not bound to the index controller

### ISSUE THREAD

**Issue by ariponce** [octobercms/october#963] opened 2015-02-25 13:54 UTC
When using a list widget inside a report widget, the pagination fails with an error message that says "A widget with class name 'widgetName' has not been bound to the controller", even when calling the bindToController method.

It also happens when trying to use the AJAX framework on the report widget.

**Comment by daftspunk** [comment] 2015-02-27 23:59
[Caused by this](https://github.com/octobercms/october/issues/953#issuecomment-76495455)

Duplicate of #953

**Closed by daftspunk** 2015-02-27 23:59 UTC
Labels: duplicate

**Comment by SebastiaanKloos** [comment] 2017-09-13 09:52
@daftspunk this is not fixed by the commit made to issue #953... :(

**Comment by sushmak2216** [comment] 2018-06-07 10:40
Does we can create a form into reportWidget for filtering the dashboard widget data by ajax request?

**Comment by LukeTowers** [comment] 2018-06-07 13:19
@SebastiaanKloos is this still an issue? 

@sushmak2216 please don't hijack issues for your questions, not only is it annoying to the maintainers it also won't get your question answered. Please use one of the many other avenues available instead of hijacking issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by Duddy67** [comment] 2020-07-17 12:36
@LukeTowers  Yes, it's still an issue for me.
Has a solution been found, or is the problem still unresolved ?

**Comment by LukeTowers** [comment] 2020-07-17 15:12
@Duddy67 sounds like you're not initializing your List widget correctly. Please post your code.

**Comment by Duddy67** [comment] 2020-07-17 15:25
Here it is:
```
    public function onLoadCategoryList()
    {   
        $config = $this->makeConfig('$/codalia/bookend/models/category/columns.yaml');
        $config->model = new \Codalia\Bookend\Models\Category;
        $config->recordsPerPage = 10; 
        $config->showPageNumbers = true;
        $config->recordOnClick = 'selectCategoryItem(:id);';
        $widget = $this->makeWidget('Backend\Widgets\Lists', $config);
        $widget->bindToController();
        $this->vars['modelList'] = $widget;

        return $this->makePartial('modal_category');
    } 
```

**Comment by LukeTowers** [comment] 2020-07-17 16:38
@Duddy67 that's the problem. If you aren't initializing the List widget on every request made to the backend when your ReportWidget is present then it will not be present when you attempt to call an AJAX handler that is defined by the Lists widget (i.e. pagination). You need to initialize that widget in the init() method of your ReportWidget

**Comment by Duddy67** [comment] 2020-07-17 16:59
@LukeTowers  Thanks for your help, but what do you mean by ReportWidget ? 
The only widget I have is the one I create in my controller (see the code above):  
`$widget = $this->makeWidget('Backend\Widgets\Lists', $config);`
As for the init() method where should it be declared ?
Would you have an example ?

**Comment by LukeTowers** [comment] 2020-07-17 17:40
@Duddy67 this issue is about Report widgets. Show me the entire file you're using for your code.

**Comment by Duddy67** [comment] 2020-07-17 18:17
@LukeTowers Sorry I didn't notice it was about Report widgets, but I guess the principle remain the same whatever the widget.
Here's my controller's code:

```
<?php namespace Codalia\Bookend\Controllers;

use Flash;
use Lang;
use BackendMenu;
use Backend\Classes\Controller;
use Codalia\Bookend\Models\Book;
use Backend\Behaviors\FormController;
use BackendAuth;

/**
 * Books Back-end Controller
 */
class Books extends Controller
{
    public $implement = [ 
        'Backend.Behaviors.FormController',
        'Backend.Behaviors.ListController',
    ];

    public $formConfig = 'config_form.yaml';
    public $listConfig = 'config_list.yaml';

    public $requiredPermissions = ['codalia.bookend.access_books'];


    public function __construct()
    {
        parent::__construct();

        BackendMenu::setContext('Codalia.Bookend', 'bookend', 'books');
    }


    public function index()
    {
        // Calls the parent method as an extension.
        $this->asExtension('ListController')->index();
    }   


    public function create()
    {   
        BackendMenu::setContextSideMenu('new_book');

        return $this->asExtension('FormController')->create();
    }

    public function update($recordId = null, $context = null)
    {
        return $this->asExtension('FormController')->update($recordId, $context);
    }

    public function onLoadCategoryList()
    {
        $config = $this->makeConfig('$/codalia/bookend/models/category/columns.yaml');
        $config->model = new \Codalia\Bookend\Models\Category;
        $config->recordsPerPage = 10;
        $config->showPageNumbers = true;
        $config->recordOnClick = 'selectCategoryItem(:id);';

        $widget = $this->makeWidget('Backend\Widgets\Lists', $config);
        $widget->bindToController();
        $this->vars['modelList'] = $widget;
    
        return $this->makePartial('modal_category');
    }

    public function listExtendQuery($query)
    {
        if (!$this->user->hasAnyAccess(['codalia.bookend.access_other_books'])) {
            // Shows only the user's books if they don't have access to other books.
            $query->where('created_by', $this->user->id);
        }
    }

    public function index_onDelete()
    {
        if (($checkedIds = post('checked')) && is_array($checkedIds) && count($checkedIds)) {

            foreach ($checkedIds as $recordId) {
                // Checks that book does exist and the current user has the required access levels.
                if ((!$book = Book::find($recordId)) || !$book->canEdit($this->user) || $book->checked_out) {
                    continue;
                }

                $book->delete();
            }

            Flash::success(Lang::get('codalia.bookend::lang.action.delete_success'));
         }

        return $this->listRefresh();
    }
}
```

**Comment by LukeTowers** [comment] 2020-07-17 21:22
The principle isn't the same, this issue has nothing to do with your issue.

The problem you are encountering is that when you try to use an AJAX handler provided by your CategoryLists widget, it doesn't exist, because it's only created when `onLoadCategoryList()` is run. To fix this, you need to create the widget in your construct() method instead.

**Comment by Duddy67** [comment] 2020-07-18 08:10
@LukeTowers Thanks again. It makes sense now.
Here's my code modified according to your explanation. Hope it helps.

```
<?php namespace Codalia\Bookend\Controllers;
    
use Flash;
use Lang;
use BackendMenu;
use Backend\Classes\Controller;
use Codalia\Bookend\Models\Book;
use Backend\Behaviors\FormController;
use BackendAuth;
    
    
/**     
 * Books Back-end Controller
 */     
class Books extends Controller
{
    public $implement = [
        'Backend.Behaviors.FormController',
        'Backend.Behaviors.ListController',
    ];  
    
    public $formConfig = 'config_form.yaml';
    public $listConfig = 'config_list.yaml';
    
    public $listWidget = null;
        
    public function __construct()
    {   
        parent::__construct();
        
        $this->createListWidget();

        BackendMenu::setContext('Codalia.Bookend', 'bookend', 'books');
    }   

  ...

    public function onLoadCategoryList()
    {   
        $this->vars['modelList'] = $this->listWidget;
        return $this->makePartial('modal_category');
    }   

    public function createListWidget()
    {   
        $config = $this->makeConfig('$/codalia/bookend/models/category/columns.yaml');
        $config->model = new \Codalia\Bookend\Models\Category;
        $config->recordsPerPage = 10; 
        $config->showPageNumbers = true;
        $config->recordOnClick = 'selectCategoryItem(:id, \':name\');';

        $this->listWidget = $this->makeWidget('Backend\Widgets\Lists', $config);
        $this->listWidget->bindToController();
    }   

  ...

}
```
