### ISSUE TITLE
Composer Autoload Is Broken For Backend

### ISSUE THREAD

**Issue by shoguniphicus** [octobercms/october#5196] opened 2020-07-02 01:28 UTC
- OctoberCMS Build: 465
- PHP Version: 7.2.24
- Database Engine: MySQL

**Description:**
It's been a while since we update anything to the system, but that's also because we were never really logged out of the backend. But our last patch to the server broke it.

We encounter the issue of missing library that is supposed to be loaded with October.Drivers. We checked the plugin files and realized that OctoberCMS will find vendor/autoload.php and loads in in the frontend properly.

But when it comes to /backend/backend/auth or any backend pages that require the session to work with Redis. We encounter a problem where the system complains it cannot find 'Predis\Client'. So I went ahead and check the trace stack. and found that backend loads differently and bypasses the plugin autoload.php portion, hence the plugin's composer's vendor files are never loaded when we use Redis as cache.

![image](https://user-images.githubusercontent.com/5608586/86305831-366b7a00-bc45-11ea-8549-d2da3d60d583.png)

We notice that if we intentionlly creating errors is loading. The proper sequence happens when october loops through the plugins hence will load the dependencies properly. But when such errors happen in backend, such sequence is skipped, not sure if it's by design, but definitely broken the classes that depend on autoload.php from the plugins.

![image](https://user-images.githubusercontent.com/5608586/86306161-17211c80-bc46-11ea-9a9d-a25328eb4d7d.png)

What we are doing now, is to rename the autoload.php to autoload_.php. And did the worst type, which is to add in 
`require __DIR__.'/../plugins/october/drivers/vendor/autoload_.php';`
to bootstrap/autoload.php

This way, we prevented double declaration in the frontend, and autoload.php not loaded properly when redis cache is used.

Having said that, right now we just disabled the cache using redis, but using database. So our problem is temporarily averted, but the performance of database as session may slow down our application. 

Please advise

**Comment by LukeTowers** [comment] 2020-07-02 03:02
Duplicate of #5110. This has been fixed in https://github.com/octobercms/october/commit/8dba43ba0b3d356761675402b58c0bbe4d09dc9a and will be available in a couple days at most when we release 467. For now you can just apply those changes manually in your installation.

**Closed by LukeTowers** 2020-07-02 03:02 UTC

**Comment by LukeTowers** [comment] 2020-07-02 04:11
Build 467 is now available.
