### ISSUE TITLE
Issue when using widgets and dropdown properties on report widgets

### ISSUE THREAD

**Issue by ariponce** [octobercms/october#1096] opened 2015-04-30 15:36 UTC
**Reproduce steps:**
* Create a reportwidget that uses a list widget and has a property of type dropdown
* Initialize the list widget on the reportwidget's init method
* Add the reportwidget to the dashboard
* Click on the cog icon to display it's properties

**Expected result:** The dropdown options are shown

**Actual result:** A javascript alert is thrown with the message "Undefined property: Class::$widget on line 114 of /home/ariel/Sites/opentext/modules/backend/classes/WidgetBase.php"

If the list widget is initialize on the render method, the dropdown properties work, but when you try to sort the list, an error saying that the widget is not bound to the controller is thrown.

After some research, i noticed that sometimes the reportwidget class itself is set as the widget controller, causing the undefined property error.

I have partially solved the issue by checking that the widget controller is an instance of \Backend\Controllers\Index before trying to initialize the list, but the problem persists if i use more widgets.

**Comment by daftspunk** [comment] 2015-05-09 03:53
It would be helpful if can provide a [test plugin](https://github.com/daftspunk/oc-test-plugin) that exhibits this behavior.

**Comment by ariponce** [comment] 2015-05-11 08:13
You can find the test plugin here https://github.com/ariponce/october-test

**Comment by cyril-oria** [comment] 2015-07-29 15:54
+1

**Comment by daftspunk** [comment] 2016-08-13 02:15
Duplicate of #2229 =)

**Closed by daftspunk** 2016-08-13 02:15 UTC
Labels: duplicate
