### ISSUE TITLE
Cannot add image in richeditor when no image classes are defined in editor settings

### ISSUE THREAD

**Issue by Fl0Cri** [octobercms/october#3068] opened 2017-08-28 15:25 UTC
This doesn't occurs in fresh october installation, only after customizing the editor "Markup classes" in the settings and removing all classes for the images. This issue only occurs on images, other types such as tables or links are ok.
As a quick fix, adding back a single random line for the image solves the issue.

##### Expected behavior
- Dragging an image to the richeditor should upload and display the image.
- Adding an image to the richeditor by browsing the media gallery should add the image

##### Actual behavior
In both cases, the image to add appears with a white semi-transparent overlay.
The upload doesn't start (no network request is made).
An error shows in the browser console: `TypeError: d is null` in `/modules/backend/formwidgets/richeditor/assets/js/build-min.js:114:37775` (I assume you don't need the stack trace, ask me if you do).
If switching to the code view of the editor, the image is stripped, only leaving an empty `<p></p>`
If looking at the displayed image using the browser dev tools, something like this can be seen in place of the image: 
```HTML
<img src="blob:http://localhost/b98effc2-79c9-4032-879d-73846e2a97f8" style="width: 300px;" class="fr-fic fr-dib fr-uploading fr-draggable">
```

##### Reproduce steps
1. From the backend, go to "Settings" -> "Editor settings" -> "Markup Classes" tab
1. Remove all rows from the "Image" table and save the settings
1. Find any rich editor you have in the backend
1. Try to add an image

##### October build
420

**Comment by LukeTowers** [comment] 2017-08-29 16:09
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment] 2019-04-26 17:29
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Closed by LukeTowers** 2019-04-26 17:29 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug

**Comment by sqwk** [comment] 2019-05-02 19:30
This still occurs in build 447. To reproduce, remove all image classes from Settings > Editor settings > Markup classes.

**Comment by w20k** [comment] 2019-05-02 20:38
Could you try in the dev build?)

**Comment by Fl0Cri** [comment] 2019-05-03 07:10
Still occurs on the develop branch.

Compared to my initial post long time ago, now the image can be added by browsing the media gallery using the "Insert Image" button of the RichEditor.

There is still an error in the console and the image's toolbar cannot be displayed but at least when saving it is realy saved.

However the upload image still doesn't work.
