### ISSUE TITLE
after fresh installation js error in code editor 

### ISSUE THREAD

**Issue by niradler** [octobercms/october#2661] opened 2017-02-07 22:38 UTC
after fresh installation js error in code editor, in build-min.js
i tried to take the file from the repo and replace the file just in ending with editor undefined error in my console

**Comment by LukeTowers** [comment] 2017-02-08 04:38
You're going to have to be more specific in what the problem is. We can't help if we can't reproduce what's happening.

**Comment by daftspunk** [comment] 2017-02-08 08:10
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by LukeTowers** [comment] 2017-10-18 23:14
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-18 23:14 UTC
Labels: Status: Revision Needed, Type: Unconfirmed Bug
