### ISSUE TITLE
removing an image doesnt remove its thumbs

### ISSUE THREAD

**Issue by ctf0** [octobercms/october#2683] opened 2017-02-17 10:30 UTC
##### Actual behavior
if u deleted an image, its thumbs will remain under `temp > public`

##### Reproduce steps
1- uploaded an image with the media manager
2- delete that image

##### October build
i believe its v1.0.398

**Comment by LukeTowers** [comment] 2017-03-10 18:08
Why'd you close this?

**Comment by LukeTowers** [comment] 2017-10-18 23:18
Closing as it has been over a month since any activity on this occurred.

**Comment by maartenmachiels** [comment] 2018-03-21 14:22
Hi Luke, I can confirm this bug. In my usecase, I've got a custom model that has a bunch of images as file attachments (`attachMany`). When deleting the model, I can delete the attached images by adding the following code to my model:

```
   public function afterDelete() {
        foreach ($this->images as $image) {
            $image->delete();
        }
    }
```
The problem is that this does delete the connected images, but that it orphans the generated thumbnails. They remain in the filesystem untill they are purged.

The problem is that at present we can only purge ALL the thumbnails, and not just the deleted ones. Might you have an idea about how to clear the generated thumbnails `afterDelete`? 

(getThumb() also seems to create another copy of the original image, without extension in the folder where it stores the thumbnail, causing excessive disk space usage).

Thanks for looking into this.

**Comment by LukeTowers** [comment] 2018-03-21 17:04
@maartenmachiels I don't have time to look into this right now myself, but perhaps you could and then keep us updated on what you find?

**Comment by maartenmachiels** [comment] 2018-03-21 17:15
Thanks Luke, I honestly don't know where to begin, but I'll dive off the deep end and see what I'll come up with.

**Comment by LukeTowers** [comment] 2018-03-21 17:23
Thumb generation happens in \October\Rain\Database\Attach\File if that helps

**Comment by maartenmachiels** [comment] 2018-03-21 17:35
Luke, a quick question: I've seen that in some cases, a temp folder is generated and filled. Can't find any documentation on this and how it relatest to getThumb(). Shouldn't this temp folder be cleared automatically? `php artisan cache:clear` doesn't take effect there. Any ideas?

**Comment by LukeTowers** [comment] 2018-03-21 17:39
Probably should get cleared after it's done being used. Best documentation to look at is the code itself in this case.

**Comment by Samuell1** [comment] 2019-08-07 07:22
This is duplicate of https://github.com/octobercms/october/issues/3605 and outdated issue

**Comment by bennothommo** [comment] 2019-08-07 10:21
Duplicate of #3605.

**Closed by bennothommo** 2019-08-07 10:21 UTC
Labels: duplicate
