### ISSUE TITLE
dependsOn not working for datepicker with time format

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/october#4268] opened 2019-04-17 23:28 UTC
- OctoberCMS Build: 451
- PHP Version: 7.1

### Description:
When having a form with a datepicker field in time mode, other fields that depend on that field by the dependsOn configuration, don't update.

The same is happening for datetime fields, but then it only updates on changing the date.

### Steps To Reproduce:

Create a form like this:

```
field1:
    type: datepicker
    mode: time

field2:
    type: datepicker
    mode: time
    dependsOn: field1
```

Changing the time in field 1 doesn't trigger the filterFields method.

**Comment by obuchmann** [comment] 2019-04-30 14:22
I can confirm this bug.
It happens for mode: time and mode: datetime too for the time part of the widget.

**Comment by evanlihou** [comment] 2019-05-18 22:20
I just ran into this issue as well, it looks like the event from the time picker doesn't bubble up to the div used in fieldElements in [october.form.js](https://github.com/octobercms/october/blob/7e6800ea6e00637619a0d10eef3eaa82d5c4b255/modules/backend/widgets/form/assets/js/october.form.js#L124), though it does bubble up properly in the date picker.

Ideally the behavior should be that the change doesn't fire until both date and time have been chosen in datetime mode (currently the value is the chosen date with the current time when just the date has been filled in).

I'm continuing to look into where this error is coming from, hopefully I'll be able to get a PR in for it so I can get my plugin working properly.

**Comment by evanlihou** [comment] 2019-05-31 14:44
Are there any updates on this issue? I did try to look into the root cause but I'm not well-versed enough with the JS running the backend to wrap my mind around what's happening there.

**Comment by evanlihou** [comment] 2019-10-07 00:06
I missed the first bot post, can we get this opened back up?

**Comment by evanlihou** [comment] 2019-11-07 00:10
Still hoping to get this resolved at some point, but maybe this needs to be reopened in the forked repo

**Comment by LukeTowers** [comment] 2019-11-10 21:09
@evanlihou fork's no longer happening, we'll address it in this repo

**Comment by bennothommo** [comment] 2019-11-29 16:11
Fixed by 128312106955d894528d448700f1fc66792b7826. Please let us know if there's any further problems.

**Closed** 2019-11-29 16:11 UTC
Labels: Status: Completed, Type: Bug
