### ISSUE TITLE
Media manager bug with cirillic and opcache = 1

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#4050] opened 2019-01-11 09:58 UTC
- OctoberCMS Build: 446
- PHP Version: 7.1, 7.0
- Database Engine: mysql
- Plugins Installed: nothing

### Description:
![rfg](https://user-images.githubusercontent.com/8817759/51026766-21aea880-15b1-11e9-8f75-1cdda7d060db.gif)

### Steps To Reproduce:
Upload files with cyrillic symbols to media manager.

### Result
in php-fpm off opcache

**Comment by LukeTowers** [comment] 2019-01-11 22:38
@pavelmgn so the issue is that uploading files with the same name (when that name is cirillic characters) the original file gets removed as well as the new one? And does this happen when opcache is disabled?

**Comment by pavelmgn** [comment] 2019-01-13 13:47
> @pavelmgn so the issue is that uploading files with the same name (when that name is cirillic characters) the original file gets removed as well as the new one? And does this happen when opcache is disabled?

@LukeTowers deletes the file name and leaves only the extension. Хвоя.jpg -> .jpg

**Comment by LukeTowers** [comment] 2019-01-13 17:56
Duplicate of #3354

**Closed by LukeTowers** 2019-01-13 17:56 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
