### ISSUE TITLE
insert html tags in backend editor causes "save" to fail

### ISSUE THREAD

**Issue by D3m1urg0** [octobercms/october#1757] opened 2016-02-06 22:44 UTC
as soon as an html tag 
es. `<div></div>`
is inside a backend editor
(pages, layouts, partials, contents at the same)

pressing the save button (or clicking ctrl+s) results in nothing (the spinner just stops, no green alert is displayed and nothing get saved in the filesystem.

**Comment by hybridvision** [comment] 2016-02-06 23:18
Have you checked the Network section in the browser's developer tools to see what the actual response is from the server? It sounds like there may be some kind of security measure that is blocking the save on your host.

See: https://github.com/octobercms/october/issues/1742

**Comment by D3m1urg0** [comment] 2016-02-07 00:56
@hybridvision   i dont know what to look for... it gives the exact same response.. but i managed to do more tests:

- [x] `<div>` Works
- [ ] `<div></div>` Dont Work
- [x] `<div>test</div>` Works
- [ ] `<div><span>test</span></div>` Dont Works
- [x] `<div  /div>` Works
- [ ] `<div>    </div>` Dont Works
- [x] `<div>    test   </div>` Works
- [ ] `><` Dont Works
Looks like he dont like the presence of those 2 characters ">" and "<" without another character in between...

Network always gives me status 200 ok at every test

**Comment by D3m1urg0** [comment] 2016-02-07 01:03
I correct myself, i found where to look for:

when i give him a valid entry (the save button works)

i get this:

`{"templatePath":"home.htm","templateMtime":1454806751,"tabTitle":"Demonstration","pageUrl":"http:\/\/kindsgard.pcriot.com","#layout-flash-messages":"    <p data-control=\"flash-message\" class=\"flash-message success\" data-interval=\"5\">The template has been successfully saved.<\/p>\n","X_OCTOBER_ASSETS":{"js":["http:\/\/kindsgard.pcriot.com\/modules\/cms\/widgets\/mediamanager\/assets\/js\/mediamanager-browser-min.js?v314","http:\/\/kindsgard.pcriot.com\/modules\/cms\/widgets\/assetlist\/assets\/js\/assetlist.js?v314"],"css":["http:\/\/kindsgard.pcriot.com\/modules\/cms\/widgets\/mediamanager\/assets\/css\/mediamanager.css?v314","http:\/\/kindsgard.pcriot.com\/modules\/cms\/widgets\/assetlist\/assets\/css\/assetlist.css?v314"],"rss":[]}}`
and then this:
`{"#TemplateList-pageList-template-list":"    <ul>\n       `

when the save fails it gives me
at first

> the Whole backend dom as response

then again
`{"#TemplateList-pageList-template-list":"    <ul>\n       `

**Comment by D3m1urg0** [comment] 2016-02-07 01:14
ok looks like the only differences in the response are those:

**The working one:**
```
Accept-Ranges:bytes
Age:0
Cache-Control:no-cache
Connection:keep-alive
Content-Length:750
Content-Type:application/json
Date:Sun, 07 Feb 2016 00:59:11 GMT
Set-Cookie:october_session=eyJpdiI6Ijg2Mlp1alQwMWx2WVZGU1ZFam9oOGc9PSIsInZhbHVlIjoidmhBZ3RxVVlpWGxiQ2VIMDM0XC81TldCdjV0UHgrNDZRb2t4ZXN2UUFVMDJ5N0UralJcL0I2bHZOWjF0N2FDMm1hUm1Vdml0MHB0OGU0VzB1QjhkRjY1QT09IiwibWFjIjoiMjY3ODM5OGY3ZmZlMDBiMzEwZWM0ZTFlYWM2ZmE2MmI5ODFhOTdjMWRjNWM5ZDdiNGNiZTAzZWUzZmE1MjE3MiJ9; expires=Sun, 07-Feb-2016 02:59:11 GMT; Max-Age=7200; path=/; httponly
X-Cache:MISS
X-Varnish:189825416
```

**The failing one**
```
Accept-Ranges:bytes
Age:0
Cache-Control:no-cache
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Sun, 07 Feb 2016 00:59:49 GMT
Set-Cookie:october_session=eyJpdiI6IitFeGpQbW5MZHlVZkdVUXpkbHdNMmc9PSIsInZhbHVlIjoiQjZcL1orTmNkaTNwTklQdFZsXC9ld250QkhnbTZYNkNTZnI4QmRhUzl4YWlGTWZyWHVLdXBxUmdNb2FWVWNoQzNrYWJDMXNmQnVVejZvSnArVnZxUUtPUT09IiwibWFjIjoiYmIzM2Q1YjhlOWE1YmI0NTM2NTY1MzUzMWRhZDY4ZWQzMjQ3MTIxNjk4ZTRhNzI5Zjk2MWFmYzNkNDBiZDUxZSJ9; expires=Sun, 07-Feb-2016 02:59:50 GMT; Max-Age=7200; path=/; httponly
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Cache:MISS
X-Varnish:184389152
```

And i can notice only a missing content lenght, a chuncked encoding and a gzip encoding

**Comment by hybridvision** [comment] 2016-02-07 11:11
Nice detective work @D3m1urg0 :)

The reason I suggested looking at the network log was to see if the server was returning some kind of error message that would give us some clues about what is going on. Often with AJAX requests, these unexpected messages are obscured.

It seems like your host is blocking it silently so the next thing I'd suggest is that you talk to the hosting support and ask them about it directly. They will hopefully be able to suggest a solution that works within their restrictions. If not, it may be time to find a better host...

**Comment by daftspunk** [comment] 2016-02-19 21:49
Duplicate of #1742

Contact your hosting provider for a solution. Their security is too tight, it is perfectly acceptable to post `><` to your server without it curling up in to a little ball and dying from fear.

**Closed by daftspunk** 2016-02-19 21:49 UTC
