### ISSUE TITLE
Folder issues with S3 media uploads

### ISSUE THREAD

**Issue by shortformblog** [octobercms/october#3445] opened 2018-03-12 02:53 UTC
##### Expected behavior
I'm using the Drivers Plugin to manage my images through Amazon S3. I would like to use the main directory of my bucket to manage those images, which would help as I'm trying to use an existing base of images I have managed via imgix.

##### Actual behavior
However, two things happen that prevent me from doing so:

1. Selecting the root of the bucket fails to add the initial slash after the domain/bucket name, so the link shows up broken (e.g. http://mybucket.comimage.jpg instead of http://mybucket.com/image.jpg). However, the image does appear to upload. Setting a non-root folder solves the issue, but I would like to use the root folder for this.

2. I cannot open up some of my existing folders in the Media interface, so as a result, I cannot access my cache of images which is currently organized in a /year/month/ format. However, a folder I created in October works fine. I believe this could possibly be a permissions issue in my bucket but I checked AWS and no permissions were set on the folders.

I did not find a prior Github Issue about these problems, but they seem to have been mentioned on the October forums in the past: https://octobercms.com/forum/post/amazon-s3-andor-cdn-image-linking-issue

##### Reproduce steps
Set Amazon S3 for media uploads, put the "folder" in cms.php at the root of the bucket. Putting in nothing throws out an error.

```
 'media' => [
  'disk'   => 's3',
  'folder' => '/',
  'path'   => 'https://mybucket.com/',
],
```

##### October build
(October build number)

Build 434

**Comment by rajakhoury** [comment] 2018-03-17 00:09
@shortformblog  I reproduced the steps you mentioned. 
1) yes the Media item url is missing a slash between the bucket name and file path 
2) I created folders manually and through the backend Media Library but there's is not problem in accessing those folders/files from the backend just the urls are missing the slash..

**Comment by shortformblog** [comment] 2018-03-17 00:31
@rajakhoury Yeah, I'm admittedly not 100 percent sure that folder issue isn't on my end—though when I checked there didn't seem to be anything on the folder preventing its use. But that said, it might be helpful, as a possible addition to that, for October's media folder to offer more feedback to the end user as to why a folder won't open or a file won't function. Currently it does nothing and it would be useful for troubleshooting to state if there's a problem.

I'm glad to have confirmation on the first issue being a problem, though, as that was the thing that clearly seemed like a bug to me.

**Comment by rajakhoury** [comment] 2018-03-17 01:29
I am sharing the steps I did and let's see if others can confirm. 

### Default Test ###
1. Using default config

        'media' => [
            'disk'   => 's3',
            'folder' => 'media',
            'path'   => 'https://october-test-bucket.s3.amazonaws.com/media',
        ],
2. Upload a file from the backend's Media Manager
3. Result as expected the path is correct to the media folder - [Live Link](https://october-test-bucket.s3-us-west-1.amazonaws.com/media/Koala.jpg)
4. Note: the uploaded object didn't have any permissions at all, I had to manually set Public Read

### Second Test ###

1. Removed the media and added a slash to point to the root

        'media' => [
            'disk'   => 's3',
            'folder' => '/',
            'path'   => 'https://october-test-bucket.s3.amazonaws.com/',
        ],
2. Upload a file from the backend's Media Manager - No prob
3. File is uploaded to the bucket's root folder but the link is broken missing slash & the file name is in lower case it should be `Koala.jpg` -[ Live Link](https://october-test-bucket.s3.amazonaws.comkoala.jpg/)

![test2](https://user-images.githubusercontent.com/4506434/37550144-03f6eb36-294e-11e8-9977-0eb4569fe309.png)

### Third Test ###

1. Removed the slash from folder

        'media' => [
            'disk'   => 's3',
            'folder' => '',
            'path'   => 'https://october-test-bucket.s3.amazonaws.com/',
        ],
2. Upload a file from the backend's Media Manager - No prob
3. Same as test 2 - missing slash and incorrect file name -[ Live Link](https://october-test-bucket.s3.amazonaws.compenguins.jpg/)

![test3](https://user-images.githubusercontent.com/4506434/37550188-9c059684-294e-11e8-9d05-baaf58d616c6.png)

### Fourth Test ###

1.  Same Config as Test 3 - Create a Folder from the Backend
2. Folder created - No prob 

![test4](https://user-images.githubusercontent.com/4506434/37550213-09409c44-294f-11e8-8204-3143df80899b.png)
3. Open Folder and upload object from backend - Object is upload to that folder but the link is broken missing slash -[ Live Link](https://october-test-bucket.s3.amazonaws.comtestfolder/Desert.jpg)

![test41](https://user-images.githubusercontent.com/4506434/37550235-5b919426-294f-11e8-9316-c2a9411db492.png)

**Comment by wackywired135** [comment] 2018-03-20 03:00
I'm also seeing the issue where the slash is missing after the domain when using the root of an S3 bucket. Although, I've only noticed this issue in the media manager. (Also logged out, cleared cookies, etc) The media filter in twig, however, works fine.

This HTML snippet generates the correct URL on a page:
`<a href="{{ 'documents/legal/policies/terms/xyz.pdf'|media }}">Jun 15, 2016</a>`

I could also reproduce @rajakhoury steps with the same results.

**Comment by LukeTowers** [comment] 2018-03-20 04:32
Anyone able to look into making a fix for this?

**Comment by rajakhoury** [comment] 2018-03-20 06:13
Here is a guess, In the [getMediaRelativePath()](https://github.com/octobercms/october/blob/master/modules/system/classes/MediaLibrary.php#L512) method of the Media Library there's

      // Will remove the slash 
       if (substr($path, 0, $this->storageFolderNameLength) == $this->storageFolder) {
            return substr($path, $this->storageFolderNameLength);
        }

`storageFolder` is `'/'` in either case if the media folder is set to an empty string or `'/'` in the cms config because of the normalization on `validatePath`

`$this->storageFolder = self::validatePath(Config::get('cms.storage.media.folder', 'media'), true);`

so `return substr($path, $this->storageFolderNameLength);` will always extract the first slash from the relative path.

Adding the below solves the issue, because the path is already in the root : 

       if (substr($path, 0, $this->storageFolderNameLength) == $this->storageFolder) {
            return $path;
        }

A better way is to use the same method as the media twig filter, as @wackywired135 mentioned the url is correct so changing the `publicUrl` in the [initLibraryItem](https://github.com/octobercms/october/blob/master/modules/system/classes/MediaLibrary.php#L577) method 

From 

` $publicUrl = $this->storagePath.$relativePath;`

to

 `$publicUrl = $this->getPathUrl( $relativePath) ;`

Should work because the Twig media filter uses the `getPathUrl()` method

What do you think ?

**Comment by wackywired135** [comment] 2018-03-20 06:15
I have very little experience in how October works, and I'm not sure if this would adversely affect other CDNs (like Rackspace, which I have no access to), but this fix seems to work for me:

Adding the following:
```php
else {
    if ($this->storageFolder === '/') {
        $this->storagePath .= '/';
    }
}
```
to this if statement: https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/system/classes/MediaLibrary.php#L71-L73

Since the trailing slash in the `cms.storage.media.path` config directive gets removed, it makes no difference if there is one in the config file. My "fix" simply re-appends the slash if the storage path begins with an http-like protocol. I don't really like it, and it seems like a hack, but perhaps it's a step in the right direction.

Tested creating folder and files, all URLs produce working links.

I haven't dug too deep into changing the storage folder instead of the path, but anything I did try created more problems. I don't know if there's better ways to lay out what I have done so far, as I'm still getting comfortable with git/github.

**Comment by wackywired135** [comment] 2018-03-20 06:27
I was just about to post this, before @rajakhoury came up with a more elegant solution. It makes sense to me, as the issue appears to be with the slash being removed.

> I have very little experience in how October works, and I'm not sure if this would adversely affect other CDNs (like Rackspace, which I have no access to), but this fix seems to work for me:
> 
> Adding the following:
> ```php
> else {
>     if ($this->storageFolder === '/') {
>         $this->storagePath .= '/';
>     }
> }
> ```
> to this if statement: https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/system/classes/MediaLibrary.php#L71-L73
> 
> Since the trailing slash in the `cms.storage.media.path` config directive gets removed, it makes no difference if there is one in the config file. My "fix" simply re-appends the slash if the storage path begins with an http-like protocol. I don't really like it, but perhaps it's a step in the right direction.
> 
> Tested creating folder and files, all URLs produce working links.
> 
> I haven't dug too deep into changing the storage folder instead of the path, but anything I did try created more problems. I don't know if there's better ways to lay out what I have done so far, as I'm still getting comfortable with git/github.

**Comment by LukeTowers** [comment] 2018-03-20 16:57
Thanks everyone for the work on fixing this, I've merged @rajakhoury's PR.

**Comment by shortformblog** [comment] 2018-03-20 16:59
Excellent work all. Thank you for checking into this.

**Closed** 2018-06-02 11:10 UTC
Labels: Status: Completed, Type: Bug
